### ISSUE TITLE
Sent using economic fee, transaction does not confirm

### ISSUE THREAD

**Issue by Aufik138** [bitcoin-wallet/bitcoin-wallet#1079]
Указал минимальную комиссию при отправке биткойнов жду уже почти 10 дней и без толку, кнопки увеличить комиссию нет в приложении у меня, как решить проблему помогите пожалуйста?  Как увеличить комиссию?

**Comment by Aufik138** [comment]
I indicated the minimum commission when sending bitcoins, I’ve been waiting for almost 10 days and to no avail, I don’t have a button to increase the commission in the application, how can I solve the problem, please help? How to increase the commission?

**Comment by Aufik138** [comment]
![IMG_20231213_161932](https://github.com/bitcoin-wallet/bitcoin-wallet/assets/153737397/3fe3ddc9-1eeb-43fe-a5f7-f5677ac1d9c2)

**Comment by YuriMB** [comment]
I'm experiencing the same issue. Is there anything we can do? When browsing the transaction it states "Invalid BTC Transaction"

**Comment by Galinagaudinastoyshiinik** [comment]
Ну конечно, это тройка, ну о чем здесь можно говорить? Уважаемая карта google, не нужно , переживать, вы молодая команда, ещё всё впереди, превратите минус себе в плюс!! Решение о регистрации нашего кандидата уважаемой карты Google, не могло быть принято из-за незначительных, ни на что не влияющих неточностей, а также, мы не до конца уверены, что все найденные несущественные нарушение порядка регистрации в какой-то момент исчезнут сами с собой раз и навсегда, тем более если вообще имели место.

**Comment by YuriMB** [comment]
Fixed the issue for me, it's not a software bug but rather a limitation of the way bitcoin works. Miners can choose which transactions they add in a block, and they only add the ones paying the most. Currently the majority of transactions has a reward of > 24 sat/vB. If your transaction is below that, tough luck. Chances are it is completely dropped. You can republish your transaction using bitcoin transaction boosters (free), but it still won't get picked up if there are higher paying transactions.

I republished the transaction using one of the boosters, and then saw the transaction with 0 confirmations on my other wallet. Then I used a technique called CPFP (Child Pays For Parent), which effectively uses the transaction with a very low fee and publishes a new transaction with a higher paying fee. I've made the new fee fairly high (~100 sat/vByte) and saw confirmations within the hour.

**Comment by schildbach** [comment]
Closing this, as the app cannot do anything about the high fees.

In general, **if you care about confirmation time, don't use economic fee**. Stay with the standard setting, which cuts a compromise between priority and costs.

**Comment by Galinagaudinastoyshiinik** [comment]
Ну конечно, это тройка, ну о чем здесь можно говорить? Уважаемая неоднозначность относительно вопроса размера самостоятельной установки правильной комиссии перед непосредственным решением об отправке транзакции, как ровно и отсутствие любого варианта исключения главной ошибки из-за недостатка развития, во многих случаях даже не хватки базовых способностей процесса аналитической деятельности, так что не нужно , переживать, вы молодая команда, ещё всё впереди, превратите минус себе в плюс!! Решение о регистрации нашего кандидата уважаемой карты Google, не могло быть принято из-за незначительных, ни на что не влияющих неточностей, а также, мы не до конца уверены, что все найденные несущественные нарушение порядка регистрации в какой-то момент исчезнут сами с собой раз и навсегда, тем более если вообще имели место.
