### ISSUE TITLE
Smartphone died, restore failed

### ISSUE THREAD

**Issue by Apehaenger** [bitcoin-wallet/bitcoin-wallet#1080]
Hi!

My daughters old Samsung S6 died.

She has a backup named `bitcoin-wallet-backup-2015-11-06` with about 30kB in size, but trying to restore always fails with Fehler "Could not decrypt bytes".
Because she's pretty sure that she knows her password I thought: May be something changed since 2015 and manually installed release 4.36 (which is the latest before 2015-11-06), but unfortunately also no luck :-/

Anything I could do/try before thinking about writing some kind of brute-force password finder?

Also: Is there a way to pin the App on an old version without getting automatically updated by Android?

**Comment by lawodion** [comment]
Try contact the customer service

**Comment by schildbach** [comment]
Most likely, the password is not correct. You could try to follow these instructions to find out more:

https://github.com/bitcoin-wallet/bitcoin-wallet/blob/main/wallet/README.recover.md

The date and file size hints at protobuf-based backup format. A downgrade of the app doesn't make any sense in this case.

**Comment by doge2021** [comment]
there is high chance your password is wrong. you may reach [BTC2doge](https://btc2doge.org) to bruteforce the correct password. @Apehaenger
