### ISSUE TITLE
Attempting restore of wallet results in empty wallet

### ISSUE THREAD

**Issue by Greydesk** [bitcoin-wallet/bitcoin-wallet#1099]
Hi,
I am attempting to move my wallet from an older phone to a newer phone. I have created a backup with a custom key. Then I moved that file to the new phone and did a restore using the same key. The program reports that the restore happened correctly and that it will be verified on next network check. Then it shuts the program down. I have waited some time but nothing seems to be restored.

**Comment by schildbach** [comment]
Go to Options Menu → Network Monitor → Blocks and see how old is the latest block? Is it updating, are more blocks arriving?

**Comment by Greydesk** [comment]
Yes, that was the problem. It had 34 months of data to download. Once I was home on my faster network, a line popped up saying it was updating and transactions started to appear.
Thanks!

Feb 12, 2024 6:04:38 p.m. Andreas Schildbach ***@***.***>:

**Comment by schildbach** [comment]
Thanks for the feedback! Glad it works now.
