### ISSUE TITLE
Sync stuck at block 849137

### ISSUE THREAD

**Issue by yuanyangzi** [bitcoin-wallet/bitcoin-wallet#1152]
The android bitcoin wallet version is 10.14. It's stuck even if I download a new apk and start a new sync.Always stopped at 849137.

**Comment by 32xxl** [comment]
Have you fixed already? 
If no, don't panik, today is sunday. 
I have the same issue. 
Just make copy of private keys, and wait for updates from devs.

**Comment by yuanyangzi** [comment]
> Have you fixed already? 
> If no, don't panik, today is sunday. 
> I have the same issue. 
> Just make copy of private keys, and wait for updates from devs. 

Thanks. Not fixed, I saw you have the same problem and my phone is Samsung too. I copied my private key and download desktop version to see if there's the same problem.

**Comment by schildbach** [comment]
Duplicate of #1154.
