### ISSUE TITLE
Sync is stuck

### ISSUE THREAD

**Issue by DTUBBS08** [bitcoin-wallet/bitcoin-wallet#1153]
Sync is stuck at 849198. Sync is 14 hours behind.

**Comment by 32xxl** [comment]
Have you fixed already? 
If no, don't panik, today is sunday. 
I have the same issue. 
Just make copy of private keys, and wait for updates from devs.

**Comment by DTUBBS08** [comment]
Thank you, 32xxl

**Comment by DTUBBS08** [comment]
My apologies, no it's not fixed yet

**Comment by schildbach** [comment]
Duplicate of #1154.

**Comment by Laye27** [comment]
Thanks
