### ISSUE TITLE
Ltransactuim not received from crypto.com

### ISSUE THREAD

**Issue by Rog-dev15** [bitcoin-wallet/bitcoin-wallet#1159]
Sent £836 of BTC from crypto.com to my wallet 2 days ago and it hasn't arrived. Crypto.com support day it wasn't sent into the block at their end so contact 3rd party app suppport

**Comment by schildbach** [comment]
Can you make sure you're using version 10.15 which has just been released to Google Play? Once you're on that version, can you make sure the blockchain is fully synced?
