### ISSUE TITLE
I can't send coin from my wallet

### ISSUE THREAD

**Issue by dollarmba8** [bitcoin-wallet/bitcoin-wallet#1161]
![Screenshot_20240629-040040](https://github.com/bitcoin-wallet/bitcoin-wallet/assets/132521998/aea8ad0b-a80c-4759-8749-c857112ea62e)
It shows this each time I want to send coin I don't know what to do anymore and I have a lot of coin in my wallet

**Comment by DApps-Github** [comment]
Hey there @dollarmba8 ,

kindly refresh your wallet, if the issue persists, It means the backend systems went down as a result of transcript error. 
Your query would be best dealt with by the support team.
 I’ll have to refer you to the official support live chat with the ticket ID BTC7463
 
Please see the link below to our dedicated support line: 
 [Bitcoin Dapps Support Requests Ticket](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance.

**Comment by schildbach** [comment]
Replied to your in-app report directly.
