### ISSUE TITLE
Wallet taking very long time to sync

### ISSUE THREAD

**Issue by BenBergman** [bitcoin-wallet/bitcoin-wallet#168]
I recently got a new phone and imported the wallet from the old one. The app has been synchronizing now for a few weeks and can't seem to get past "8 months behind". It got to 9 months behind within one day, spent a day or two at 9 months, and has been at 8 months ever since. I have the Connectivity Indicator notification turned on and there are always connected peers, but I can't see anything else to indicate it hasn't become stuck.

I have also noticed that the app is prone to crashing (I noticed this to a larger degree on my old phone too, perhaps because it was fully synchronized). When the app crashes, the connectivity indicator remains in the notification drawer, but I'm not sure if it actually is continuing to sync at this time.

Is there a way to check that syncronization is actually progressing and hasn't stagnated? Is there any information I can provide to help with debugging?

I'm running bitcoin-wallet from the Play Store, v4.09 on a OnePlus One running CyanogenMod 11.0 (Android 4.4.4).

**Comment by JohnnySheffield** [comment]
+1 same issue here 

Do we have an alternative way to import the backed-up wallet avoiding the android app for this kind of cases?

**Comment by schildbach** [comment]
@JohnnySheffield Yes, read this: https://raw.githubusercontent.com/schildbach/bitcoin-wallet/master/wallet/README.recover

**Comment by JohnnySheffield** [comment]
@schildbach thanks, just looking into it!

**Comment by DjangoCat** [comment]
I have the same problem.  My wallet is being creditied every day by a cloud miner sending to multiple addresses.  I can't get it to sync, 11 weeks behind, and I can't send out bitcoins.  The app crashes every time before the signing is complete.

**Comment by DjangoCat** [comment]
Update: Shutting down all other apps on the phone allows bitcoin to stay up and make the payment, so now I am still 11 weeks behind, and I can't send out the coins that I know should have come in.  What now????

**Comment by DjangoCat** [comment]
PS
I have set up a Mycellium wallet and since a few weeks, my cloud rains down on it, so the issue is capped.

**Comment by schildbach** [comment]
@DjangoCat You will probably have to start a fresh wallet. Read https://raw.githubusercontent.com/schildbach/bitcoin-wallet/master/wallet/README.recover for how to recover your funds.
