### ISSUE TITLE
Swipe Wallet - if API error inside i see as 'zero' balance

### ISSUE THREAD

**Issue by Perlover** [bitcoin-wallet/bitcoin-wallet#204]
Hi,

I tried to swipe not-zero paper wallet (2015-02-01 20:20 UTC). But the Bitcoin Wallet shows to me balance as 'zero'. I tried from two different ISPs.
I checked by Mycelium - there is non-zero many-confirmed banance.
I think in Bitcoin Wallet was and is temporaly problem with your balance provider (biteasy.com?) but i as a user don't see that there is problem. I see only "loading" and after i see "0". And i could think that there is no money (stolen, swiped and etc.)

I gifted my friends some paper wallets and what happens if right now they will decide to swipe money from where?! :( They will think that this was done by me because before gift i putted this paper wallet a noticing that i have copies of private keys and after from 1 Feb 2015 i will swipe myself from theirs wallets if they will not do it.

I think your Bitcoin Wallet should warn about network problem in any case of problem.

**Comment by Perlover** [comment]
Or if network is ok any strange response from balance provider -> "temporaly error"

**Comment by Perlover** [comment]
Or may be to use two balance providers? For example blockchain.info for total balance and current provider for getting TxOuts to this bitcoin address? If balance is not equal -> error

**Comment by Perlover** [comment]
And other strange thing now
For previously scanned paper wallet (when there it showed to me zero) the Bitcoin Wallet shows to me right balance but for other private key (encrypted already) - zero (but i know that there is non-zero).
May be resulted code from your provider is ok and as zero balance. It could mean that provider some time doesn't work properly. But it is not good behaviour. Many people could throw away paper wallets after this - they will think that they get empty wallets (from bitcoin ATMs, from friends, from bitcoin merchants).

**Comment by schildbach** [comment]
The app does have an error message for I/O errors. I suspect what you're seeing is Biteasy being back on blocks. It's currently at 341414 while it should be at 341533. If you just created the paper wallet this means Biteasy will not see its balance and report 0. I'm afraid there is not much I can do.

**Comment by Perlover** [comment]
Yes, i see created for last 24 hour paper wallets.
I think if you will check balance thourgh Blockchain.info and if balances will not equal with Biteasy you could show warning to try later. It will be more better than to show zero balance

**Comment by schildbach** [comment]
I could special case if Biteasy thinks it has never seen the address and add a special warning. Strictly speaking, a paper wallet only has a balance of 0 if it exists. What do you think?

**Comment by Perlover** [comment]
May be to check top blocks of blockchain between current and BitEasy's top block? :)

**Comment by Perlover** [comment]
I sent donation for priority this feature :)
Ok? :)
https://blockchain.info/tx/d396700446b18a5501063352ab3ab29864495af615f724cab66e988d918b7e0e

**Comment by Perlover** [comment]
I noticed already that BitEasy is as slowly clocks. They have regulary slowly lag.
May be in future to use Electrum's servers for getting TxOuts of any address? I think it could a fine solution.

**Comment by schildbach** [comment]
Thanks for the donation. I will add the special message for if the wallet seems to be not existing. I will not ask different services at this time, too much work. Using Electrum servers is a pretty good idea, I wonder why I didn't think of that earlier. Another alternative would be querying bitcoin core 0.10 nodes via its new JSON API.

**Comment by schildbach** [comment]
Ah yes, forgot to close this. The app is using Electrum servers since a while.
