### ISSUE TITLE
Users should have control when/whether to sync

### ISSUE THREAD

**Issue by alexanderadam** [bitcoin-wallet/bitcoin-wallet#227]
Modern mobile apps [give control when to sync (or not to)](https://support.google.com/nexus/answer/2840875?hl=de).

So the sync options for apps like twitter, [OpenKeychain](https://github.com/open-keychain/open-keychain), Firefox etc can be found there and the sync could also be turned off.

PS: It was also mentioned at [Google+](https://plus.google.com/110634720637776971069/posts/PfV9M8SWENS) and I think it would be a nice idea
PPS: Thank you for your work!

**Comment by rkfg** [comment]
This is a must. The app had an exit menu item in the past which was removed for some reason. I don't get why and the developer always says about restricting background data. But there's a usecase when this is not enough: when you use the wallet really occasionally. Say, once in several months. Why should the app sit in memory and eat battery all the time when I only need it this rarely? What exactly was wrong with the exit feature (and why should it be called a feature when it's a natural user's choice?)? So many questions, so few answers...

**Comment by zoff99** [comment]
+1
waiting for this for a long time.
make an option to control syncing

**Comment by schildbach** [comment]
There is support for that already in the Android settings. It's called "Restrict app background data". You can enable this globally or per app.

**Comment by alexanderadam** [comment]
@schildbach thank you for your response.

However, the Android feature does not care about the app runners itself - right? So the battery 🔋 issue as [mentioned here by @rkfg](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/227#issuecomment-167670336) and people mentioned [on Google Plus](https://plus.google.com/110634720637776971069/posts/PfV9M8SWENS) is still open. Correct?

**Comment by schildbach** [comment]
If you run the app manually you'd expect an up to date balance. So in this case it needs to sync. That's how all cloud-based apps work by the way.

The way forward is to make the sync faster and use less CPU.

**Comment by alexanderadam** [comment]
I still understand your point. Which is why I absolutely think that it would be useful that there would be a text written at the option that says something like `"be aware that deactivating sync will use more CPU on app runtime and less CPU and battery power when you aren't actively using the app"`.

PS: The point that "all cloud-based apps work" like this may be not quite correct. As mentioned earlier even a service like Twitter allows you to control and turn off the sync within the app (see `Settings > Notifications > Advanced`). And I guess, we both agree that Twitter requires much less number crunching than Bitcoin Wallet.

**Comment by schildbach** [comment]
I don't use Twitter on my phone. Does the setting also cause the app to not update any more if you're seeing your twitter stream in the app? That would surprise me.

**Comment by zoff99** [comment]
what about an option, for people who use the app not so often.
if this advanced option is turned "on" the app would just catch up with the blockcahin and then stop the sync service.
if the app is restarted (is in the forground again) the same thing would happen again -> just catch up then stop syncing.

would you consider doing this? (default setting to "off" of course)

**Comment by schildbach** [comment]
I'm against anything that would make the user a wrong balance he/she opens the app. It's simply confusing and it will cause a lot of support issues. Even if it's just a switch – people tend to forget and mail support anyways.

I could imagine sensible changes to how background syncing works though. For example, the app could trigger a sync if the user is connected to both power and WLAN. That would make any subsequent on-demand sync quick and cheap.
