### ISSUE TITLE
Nexus 5X camera flipped

### ISSUE THREAD

**Issue by instagibbs** [bitcoin-wallet/bitcoin-wallet#269]
Due to physical placement of the camera sensor, and the older android.hardware.camera API, the camera is flipped upside-down.  

Upgrading to camera2 API should fix this.

>android.hardware.camera2

**Comment by schildbach** [comment]
Thanks for reporting. Unfortunately, the camera2 API is only for Android 5+ so we'd need to keep support for both APIs.

**Comment by schildbach** [comment]
How about if we start a new ScanActivity that only uses the camera2 API and at the same time deals with the new Android 6 permission model? We could enable this activity for Android 6+ to start with, and later extend to Android 5+.

At any rate, volunteers welcome! I do not own any affected device so I will not be working on this soon.

**Comment by instagibbs** [comment]
Yeah I took a stab at it, but it's a completely new API. I also tried a suggested patch on the bug tracker, to no avail.  

Like you say, it's low priority. Scanning QR codes doesn't have to look good.

**Comment by schildbach** [comment]
This is fixed in v4.63.
