### ISSUE TITLE
App does not close automatically after payment is done through an intent using bip21

### ISSUE THREAD

**Issue by abeikverdi** [bitcoin-wallet/bitcoin-wallet#301]
When the app is opened through an intent using bip21 URI format from another app to make a bitcoin transaction, after the transaction is made and broadcast, it does not close the application and return back to the other initiating app automatically. It requires user to press back manually to proceed.
However, it fortunately returns the transaction id back to the other app.
It would be great if it closes the app automatically.

**Comment by schildbach** [comment]
The change would be very easy. We currently keep the activity open so the user can watch her/his transaction.

**Comment by abeikverdi** [comment]
Yea I understand but its not really necessary. You can just display a toast message like the way Mycelium does it. It makes the process more streamline from the third party apps point of view.

**Comment by schildbach** [comment]
Ok what about the following. The send coins dialog closes shortly after it hears the transaction back from the network at least once. It will stay open as long as there is no sign the transaction has already been broadcasted.

**Comment by abeikverdi** [comment]
well, that sounds good. I assume that should take few seconds. Would be good to show a progressbar or something during that period.

**Comment by schildbach** [comment]
The progress is currently a textual one, in the button at the lower right. After pressing send, it switches to "signing" then "sending" then "send" or "failed".

I just added a commit that will auto-close the dialog 500 ms after the progress switched from "sending" to "sent". The user can disable auto-close in the prefs (default is enabled). Note that if a payment fails the dialog will stay until manually closed. Or if the internet connectivity is spotty and the app doesn't hear anything back, it will stay as well.

**Comment by abeikverdi** [comment]
Sounds perfect. Good job. Keep it up.

**Comment by schildbach** [comment]
The change went live already a few weeks ago.

**Comment by abeikverdi** [comment]
Awesome. I noticed that few weeks ago.
