### ISSUE TITLE
Translations for zh-tw are not updated

### ISSUE THREAD

**Issue by iongchun** [bitcoin-wallet/bitcoin-wallet#303]
It seems strings.xml for zh-tw (Chinese / Taiwan) is not synced as other resources.

**Comment by iongchun** [comment]
Notice that strings_help.xml is not synced as well.

**Comment by schildbach** [comment]
I'll update zh-tw from Transifex with the next round of language updates. It's a manual process unfortunately.

**Comment by iongchun** [comment]
Thank you.

**Comment by schildbach** [comment]
I'm sorry I didn't sync the zh-tw translations for so long. I just noticed I had a mistake in how I synched, so for this language I didn't see changes in strings.xml and strings_help.xml. This is fixed now, and your transaction is in v4.49. Thanks a lot for your work, it's much appreciated!
