### ISSUE TITLE
Vote for the fork with your wallet and transactions

### ISSUE THREAD

**Issue by HostFat** [bitcoin-wallet/bitcoin-wallet#305]
> I think the last and definitive word about the fork will be uttered by the users. My suggestion is this, to make users count and express their opinions: Wallet developers (mainly SPV wallets) should allow a way to tip miners that support a particular fork (today 2 MB, tomorrow everything put at a vote).
> My suggestion is to include a feature in SPV wallets that allow the user to automatically tip a determined sum (say 1 cent) or percent (10%-100%) of the fee to the last block with a valid vote for the fork (say the last block in the last 1000 blocks).

https://www.reddit.com/r/btc/comments/471jqg/vote_for_the_fork_with_your_wallet_and/

**Comment by schildbach** [comment]
I'm afraid almost none of the users understand what this is about.

Bitcoin Wallet is not a voting app, I suggest creating a different app for that.

**Comment by luke-jr** [comment]
@schildbach If someone implements a sane stake-polling system (*not* the linked tipping concept), would that be on the table, or will Bitcoin Wallet users need to export their keys to a different app? :/

**Comment by schildbach** [comment]
@luke-jr Is there a concrete proposal I can read? I assume it involves signing custom data with the private key(s)?

The current way of "voting" for a hardfork is installing the desired forked app and move funds over. That's the idea of open source / free software. This idea is supported by using a source repository format that makes forks incredibly cheap (git).

**Comment by luke-jr** [comment]
@schildbach There is no concrete proposal yet, but probably would involve that, yes.

(There is no actual current way of "voting" for a hardfork. Software forks are unrelated to network hardforks.)
