### ISSUE TITLE
bitcoin never gets available

### ISSUE THREAD

**Issue by theScrabi** [bitcoin-wallet/bitcoin-wallet#307]
as for a small test, i transmitted a small amount over to my bitcoin wallet, and althoug blockchain.info says the transaction was confirmed 31 times. Bitcoin wallet still says the payment should be available in a few minutes.
Also I'm using the f-droid version.

**Comment by schildbach** [comment]
Is the app up to date on the blockchain?

**Comment by theScrabi** [comment]
No but it also just keeps telling me its nine weeks behind.

**Comment by schildbach** [comment]
Then that's a connectivity issue. Check the internet connection on your device. The blockchain needs to be up to date, otherwise you won't see all payments to your wallet.

**Comment by theScrabi** [comment]
Jep I fixed it by telling the App to download everything again. Now it works. Sorry for issue.

**Comment by kattylopez** [comment]
Holle
