### ISSUE TITLE
Currency in lithuania is no more litas, it's euro now

### ISSUE THREAD

**Issue by techwebpd** [bitcoin-wallet/bitcoin-wallet#310]
Please change lithuanian currency to euro

**Comment by schildbach** [comment]
What's the currency symbol (three letters) for litas?

**Comment by techwebpd** [comment]
LTL litas doesn't exists anymore

**Comment by schildbach** [comment]
Ah, now I understand. The first step is to remove it from BitcoinAverage: https://bitcoinaverage.com/#LTL-millibit
Can you mail them?

**Comment by schildbach** [comment]
The second step is the manufacturer of your phone needs to update the default currency for lithuania/lithuanian.

**Comment by techwebpd** [comment]
android 4.4 is in my smartphone

**Comment by schildbach** [comment]
You can change the selected currency in Options > Exchange rates then tap on your desired currency then tap the "pin" action button in the upper right corner.

I'm closing this issue because the default needs to be changed in Android as described (Google needs to find a better update mechanism).
