### ISSUE TITLE
Add support for BIP39 Italian wordlist

### ISSUE THREAD

**Issue by HostFat** [bitcoin-wallet/bitcoin-wallet#316]
https://github.com/bitcoin/bips/pull/306

**Comment by schildbach** [comment]
First step is adding BIP39 at all.

**Comment by peterquek1983** [comment]
https://github.com/peterquek1983/bitcoin.org.git

**Comment by 3824409A28** [comment]
Help me active my issue again

**Comment by jonathancross** [comment]
I suggest closing this as [BIP 39 is not even supported](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/245) yet.

**Comment by schildbach** [comment]
Yes, indeed. I think it's too far off. And if BIP39 arrives at some time, it's still the question if we want multiple wordlists.
