### ISSUE TITLE
Failed to resolve:org.bitcoinj:orchid:1.2

### ISSUE THREAD

**Issue by recwert** [bitcoin-wallet/bitcoin-wallet#318]
when a compile the project with android studio, throw the error:
Failed to resolve:org.bitcoinj:orchid:1.2

When i update the dependency instead of 
compile ('org.bitcoinj:bitcoinj-core:0.14'){
        exclude(group: 'org.bitcoinj', module: 'orchid')
    }
the project compile success and run success. but i don't know weather some features would crash

**Comment by schildbach** [comment]
Orchid is now removed from bitcoinj.
