### ISSUE TITLE
Bitcoins lost when sent to the same address as less than 24hrs before

### ISSUE THREAD

**Issue by insaneoperative** [bitcoin-wallet/bitcoin-wallet#319]
Well, I sent 2k worth of bitcoins to the same address I used yesterday for 2k as well and now I am here with no coins :(. I believe electrum or bitcoinwallet owns this wallet and can help me with getting my coins back. Here is my proof that these are in fact my coins.
My current electrum balance(Notice 2k transaction yesterday): http://prntscr.com/b3snsl
Wallet IDs from my 2k transaction yesterday: http://prntscr.com/b3so06 (notice 12ozu...)
2k Transaction that occured today: http://prntscr.com/b3sooz (notice receiving 120zu.. same address)
Screen shots of it being sent from the wallet i carry on my phone(have not set up electrum on mobile device, i messed up i know): http://prntscr.com/b3spdz

I hope you guys can help me some how, 2k is a hefty loss to someone like me.

**Comment by HashEngineering** [comment]
As of the time of my writing this, the 2nd transaction has 12 confirmations on the blockchain, according to blockchain.info and therefore is not the fault of Bitcoin Wallet, which shows in your screenshots that the payment was sent and confirmed at least 6 times (by full red circle).

The shows the transactions for the address in question:
https://blockchain.info/address/13ozuCankB5mkjKVunZvoHBZR2GPbYCYQn

This looks to be an issue with Electrum (either on your system or with their servers).

**Comment by schildbach** [comment]
@insaneoperative In future, please post support questions to the community: https://plus.google.com/communities/105515929887248493912
