### ISSUE TITLE
403 Error on Sweeping Paper Wallet

### ISSUE THREAD

**Issue by rbscebu** [bitcoin-wallet/bitcoin-wallet#320]
Using Bitcoin Wallet 4.53 on Android 4.0.4. I have 0.001BTC in a paper wallet (1P6zfkMaZcoCQGEZWNG6AbRTu84a1XTmwq).

When trying to sweep this paper wallet into my Android Bitcoin Wallet, after scanning the private key QR code, I get "LOADING WALLET BALANCE FAILED HTTP error 403: Forbidden".

**Comment by schildbach** [comment]
We cannot do anything about HTTP errors, other than reporting them to the user. The app queries the BitEasy API for the balance of the paper wallet.
