### ISSUE TITLE
Failed in parsing de/schildbach/wallet/integration/android/BitcoinIntegration.class

### ISSUE THREAD

**Issue by davidkhala** [bitcoin-wallet/bitcoin-wallet#327]
Dear All,

Since StackOverflow could not help much, I posted my question here.

I just clone the source and tried to using in 
Android Studio 2.1.2
JRE 1.8.0_92
Gradle 2.10

The first time I build the APK there are 30+ errors. After investigating them a little bit I guessed they came from 
build.gradle for Module:integration-android
`compileJava {
    sourceCompatibility '1.5'
    targetCompatibility '1.5'
}
`

In the second trial, I commented these block and rebuild. Only 1 error left as below

```
Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing de/schildbach/wallet/integration/android/BitcoinIntegration.class
Error:1 error; aborting
:wallet:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':wallet:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_92\bin\java.exe'' finished with non-zero exit value 1
```

**Comment by schildbach** [comment]
This is not a support forum. Can you use the G+ group to ask questions? https://plus.google.com/communities/105515929887248493912

I suggest following the building instructions from https://raw.githubusercontent.com/bitcoin-wallet/bitcoin-wallet/master/wallet/README.
