### ISSUE TITLE
Wallet import/export from/to Bitcoin-core

### ISSUE THREAD

**Issue by blamb5** [bitcoin-wallet/bitcoin-wallet#328]
Hello,
please kindly advise me how to either import my wallet (private keys) from my bitcoin-core into this android app, or export the wallet (private keys) from this app and import them into bitcoin-core. Maybe I am blind or dumb but I can't find a way how to do it. Surely it must be possible, at least one direction.
Thanks in advance.

**Comment by schildbach** [comment]
This is no support forum. Can you ask questions in the G+ community: https://plus.google.com/b/101256420499771441772/communities/105515929887248493912

Private keys cannot be exchanged betweens apps. Use a standard Bitcoin transaction to transfer value.

**Comment by blamb5** [comment]
If private keys can be backed up and restored then what's the difference between exporting and importing them? Please don't lie, at the very least, if you are unwilling to help.

**Comment by schildbach** [comment]
The difference is you can only backup and restore entire wallets.
