### ISSUE TITLE
app takes long to start / after startup it freezes from a long time

### ISSUE THREAD

**Issue by zoff99** [bitcoin-wallet/bitcoin-wallet#331]
version: 4.68 from f-droid

after the update to 4.68 the app takes about 30 seconds to start (shows a black screen until then)
after start it freezes for another some seconds where its not possible to press anything or scroll the list.

this is the 2nd update in a short time that does this

**Comment by schildbach** [comment]
Is this on every start of the app, or just on the first which creates the wallet? Does your wallet already have lots of transactions? If yes, can you send us a wallet dump through the app (see Settings > Diagnostics > Report issue)?

And finally, if you install the testnet version from https://github.com/bitcoin-wallet/bitcoin-wallet/releases in parallel, does it happen with that version too?

**Comment by zoff99** [comment]
the wallet has a moderate amount of transactions already. after the update every start takes a very long time.
but now after about 1 or 2 days its working normal again. very strange.
that same thing happend (about) 2 versions ago already.

its a if some background task is running. reminds me of the mediascanner on android 2.3 back then, which could also run for a long time and when interrrupted would start from the beginning

**Comment by schildbach** [comment]
Logs would be helpful.

**Comment by zoff99** [comment]
no, just moved to mycelium
