### ISSUE TITLE
Bitboat services support

### ISSUE THREAD

**Issue by AlphaOmega3** [bitcoin-wallet/bitcoin-wallet#336]
Add an ability to connect with the bitboat services (bitboat.net) for buy bitcoins. 

This is a first service for buy bitcoins in my country (Italy) and allows you to buy bitcoins through reload PostePay through code neosurf or with the service jiffypay. 

Practically, the purchase comprises 4 steps: 
1) send the purchase request 
2) confirm your order by mail 
3) pay cash in tobacconist 
4) receive bitcoins on your wallet 

This is a simple, safe and effective service. I think the app improve a great deal if add these services

**Comment by schildbach** [comment]
I don't plan to implement direct support for any exchanges. That said, exchanges can use the standard Bitcoin request APIs to send and receive coins to/from the app.
