### ISSUE TITLE
World Bitcoin Merchants and ATM

### ISSUE THREAD

**Issue by AlphaOmega3** [bitcoin-wallet/bitcoin-wallet#337]
Add an ability to search merchants that accept bitcoin, in the world, in 5 different ways: 
- by proximity
- by city
- by category
- by name
- by map

And add an ability to view all Bitcoin ATM in the world.

If possible, for protect the privacy, don't use the location access permissions and use the OpenStreetMap Contributors

**Comment by schildbach** [comment]
I think this would be better suited to a separate app, like a Coinmap app. That said, you're free to implement.

**Comment by 3824409A28** [comment]
I WANT TO CLOSE MY ACCOUNT IN THIS PAGE,CAN YOU HELP ME.

**Comment by 3824409A28** [comment]
Close my bank account in this page

**Comment by 3824409A28** [comment]
Close all my avatar on this page
