### ISSUE TITLE
Wallet seed?

### ISSUE THREAD

**Issue by DavidGriffith** [bitcoin-wallet/bitcoin-wallet#340]
Is it possible to get a wallet seed phrase from this app?  I could have sworn I did it before, but now I cannot find the button or option to do this.

**Comment by schildbach** [comment]
Not in the UI. You can use bitcoinj wallet-tool to print the phrase, but be aware most apps use a different derivation scheme so it's not interchangeable.

Please ask question on the community: https://plus.google.com/b/101256420499771441772/communities/105515929887248493912
