### ISSUE TITLE
Remove biteasy.com API access. Domain ownership not clear, or domain hijacked

### ISSUE THREAD

**Issue by cassiniNMC** [bitcoin-wallet/bitcoin-wallet#359]
biteasy.com is currently down despite domain expiration date still 7 months ahead. Therefore Sweep Paper Wallet feature etc. not working. API results could be manipulated soon.

**Comment by 3824409A28** [comment]
Close my account on the page github

**Comment by 3824409A28** [comment]
Iam poor man do not took my account

**Comment by schildbach** [comment]
I just contacted the owner to get a statement on the future of Biteasy.

**Comment by 3824409A28** [comment]
Help me exit this page

**Comment by 3824409A28** [comment]
Do not make fee with me iam poorest

**Comment by schildbach** [comment]
Apparently it's back up again.
