### ISSUE TITLE
send bitcoins denomination accepts more then 8 decimals

### ISSUE THREAD

**Issue by raedah** [bitcoin-wallet/bitcoin-wallet#360]
^

**Comment by schildbach** [comment]
Can you explain in detail; maybe add a screenshot?

**Comment by doso123417** [comment]
........

**Comment by raedah** [comment]
Go to send dialog, for bitcoin amount put  1.123456789999999999999999999.

**Comment by schildbach** [comment]
Yes. If you leave the field it will round the amount to Satoshi precision.

**Comment by 3824409A28** [comment]
Yes
