### ISSUE TITLE
feature request: send dialog, max amount

### ISSUE THREAD

**Issue by raedah** [bitcoin-wallet/bitcoin-wallet#361]
Have a button for max amount so that its easy to send the remaining funds without having to guess the exact amount needed to send with fee in order to empty the wallet.

**Comment by schildbach** [comment]
Send Coins > Options > Empty wallet.

**Comment by 3824409A28** [comment]
Thank you so much

**Comment by doso123417** [comment]
2559-11-17 17:32 GMT+07:00, TRAN VAN VU <notifications@github.com>:
