### ISSUE TITLE
Configurable fee rates

### ISSUE THREAD

**Issue by braydonf** [bitcoin-wallet/bitcoin-wallet#363]
It would be useful to be able to set an option for satoshis-per-byte in the *settings* view for each priority category, and be able to select the priority, normal, economy rates on the *send coins* view. I haven't been able to find this option with latest prerelease of 5.06.

The defaults are currently creating transactions that take longer than 1-12 blocks *(about 4 hours for confirmation)* for a 226 byte transaction (with 45 satoshis per byte). While it may be desirable to keep the fees low and wait, there is also the need to send quickly with an option to bump the priority in advance without creating a second transaction to raise the fee *(child-pays-for-parent policy does not seem to be active with miners yet)*.

Looks like dynamic fees were added in 5.02 to help address this, however the current values returned from https://github.com/bitcoin-wallet/bitcoin-wallet/commit/067115374109e1c1fd5aab5b5233dbd8ff578eaa#diff-b78401012ef4433bbf5f6c011edc80f2R106 are the same values as https://github.com/bitcoin-wallet/bitcoin-wallet/commit/067115374109e1c1fd5aab5b5233dbd8ff578eaa#diff-89ff4677de1f2796e54b26e412f5297d and isn't configurable.

Rates could optionally be suggested based on the current estimates from the `estimatefee` bitcoin rpc method. (See: https://github.com/bitcoin/bitcoin/blob/d932159f3467cc197caaf281f34f3324e6b5bea8/src/rpc/mining.cpp#L774) This is currently available via https://blockexplorer.com/api/utils/estimatefee?nbBlocks=2,3,4,5

Snapshot of current fees from http://bitcoinfees.21.co/

![2016-11-29-bitcoin-fees](https://cloud.githubusercontent.com/assets/544777/20703515/ed3cb43a-b5e9-11e6-8c38-2c1d05c4fcb0.png)

**Comment by schildbach** [comment]
You can switch between the fee categories in the Send Coins options menu. If you absolutely must get your tx into the next block, use priority fee (though still there is no guarantee of course – it's up to the miners).

Normal fee is meant to be as cheap as possible, while under _normal_ network conditions you should still make it into the next block. This means if the network is overloaded, you run the risk of a delay (until the fee for that category is increased).

I'm reluctant to letting the user decide on something abstract as a fee rate. It will for sure generate lots of support cases. The three categories should be enough; however some documentation should be added.

FWIW: From my obversation, the various fee estimator websites and Core's estimatefee all estimate too high.

**Comment by braydonf** [comment]
Aha, I have somehow missed the options in the *send coins* view for selecting the rate, I'll give this a try, thanks.

Including the *satoshis-per-byte* in an advanced setting could provide the functionality without introducing complexity. Ideally, changing these settings would not be necessary. This has been the only time it's been an issue.

**Comment by braydonf** [comment]
Right now it looks like the rates reported are a bit higher than what is current default for normal.

blockexplorer.com (bitcoin core) 0-3 blocks is at:
77893 to 69844

bitcoinfees.21.co 0-3 blocks is at:
51000

wallet.schildbach.de/fees normal (0-3 blocks?) is at:
45000

**Comment by 3824409A28** [comment]
Withdraw funds

**Comment by erdmark** [comment]
Why not setting fees manually in sending dialog with a warning

**Comment by schildbach** [comment]
@erdmark Because calculating the correct fee manually is way too complicated for the average user.

I'm closing this because as far as I know, nobody is working on this. If anybody has a PR to contribute, your welcome to submit and I'll review.

**Comment by braydonf** [comment]
Current solution of selecting priority fixes immediate concerns, though I still think it would be useful to have an advanced expert option hidden in the application settings for the constant fee-per-kilobyte values. Currently the dynamic values are coming from wallet.schildbach.de/fees with a fallback to the static values.

FYI, the "raise fee option" on a transaction, using child-pays-for-parent works to clear a congested transaction now. Tried it with another wallet, that did not support this, by manually constructing a transaction, and it was confirmed almost instantly after.
