### ISSUE TITLE
[Regression?] Exchange rate window: position list focus on the standard currency (e.g. "EUR"), but not on "AED"

### ISSUE THREAD

**Issue by Wikinaut** [bitcoin-wallet/bitcoin-wallet#366]
On my Android 6.0 device, in former app versions, the **standard** currency was on top of the screen when I started the Exchange rate view.

This is not the case any more, looks like a regression:

In the latest versions, the view starts with letter A, ie. "AED", but as I have set "EUR" as standard currency, I wish to have the view centered around "EUR".

**Comment by schildbach** [comment]
Fixed in 7fe8d63c6dd6d9057c4efbf570b2373dd24ac2b4.

**Comment by Wikinaut** [comment]
:cool: danke!

**Comment by Wikinaut** [comment]
Regression again! My selected currency standard (EUR) is not on top any more.

* wallet 7.61

**Comment by anhhaibg1** [comment]
G

**Comment by schildbach** [comment]
It's marked as selected.
