### ISSUE TITLE
Maintain current identity option

### ISSUE THREAD

**Issue by AlfaOmega33** [bitcoin-wallet/bitcoin-wallet#368]
Hi! Please add, in the settings, the button "maintain current address" and let the users choose wheter change and/or when change it. I would like to keep the same address to receive donations and other (es app published with a bitcoin address inside of the same app, for not change the address constantly).

Sorry for my bad english, I use Google Translator

**Comment by BangLy** [comment]
What Is the api key,hơ can i send my coin or sell all.please help me

**Comment by schildbach** [comment]
Nothing stops you from just reusing one of the addresses, they all stay valid. No action from the app necessary.

**Comment by AlfaOmega33** [comment]
And a command "changr now"? For changing the address manually?

**Comment by rkainemac** [comment]
changr
