### ISSUE TITLE
RFE: Add blockchain.info as block explorer

### ISSUE THREAD

**Issue by pludi** [bitcoin-wallet/bitcoin-wallet#370]
Currently, only blockexplorer.com is available. blockchain.info uses for all intents and purposes the same endpoint for transactions, eg. ```https://blockchain.info/tx/<transaction_id>```, while IMO having a better interface.

**Comment by schildbach** [comment]
Afaik, blockchain.info isn't available for testnet.

**Comment by pludi** [comment]
On a hunch I checked:
https://testnet.blockexplorer.com/block/0000000000001c19acdbaa37a8cbd4ad7757f68b1a1d452f74776141fde9e262 vs
https://testnet.blockchain.info/block/0000000000001c19acdbaa37a8cbd4ad7757f68b1a1d452f74776141fde9e262

**Comment by schildbach** [comment]
Ok so have added testnet. Good news!

**Comment by micressor** [comment]
+1 for blockchain.info

**Comment by schildbach** [comment]
bc.i was added in fbb0fe365ac5d6740596f8db72515762e03a738c.
