### ISSUE TITLE
Sweep does not work

### ISSUE THREAD

**Issue by deafboy** [bitcoin-wallet/bitcoin-wallet#371]
Unable to sweep from private key. After I capture the QR code containing the private key, I'm stuck at the following screen:
![screenshot_20170117-224257](https://cloud.githubusercontent.com/assets/908822/22041614/cfdc4442-dd07-11e6-8504-afc8a0e4bbad.png)

Captured from logcat:
`01-17 22:48:05.247  3674 31846 I RequestWalletBalanceTask: [backgroundThread] fetched unspent outputs from https://api.biteasy.com/v2/btc/mainnet/outputs?per_page=MAX&operator=AND&spent_state=UNSPENT&address[]=1HRVnp4w6skMot2LFxDcxegkqXcTJvs8mi`

Reply from API:
`{"status":200,"data":{"outputs":[],"pagination":{"page":1,"per_page":200,"previous_page":false,"next_page":false}}}`

**Comment by deafboy** [comment]
Looks like Biteasy is only working with confirmed transactions and it's currently 36 blocks behind. I'll close this issue when I confirm that this was the only problem.

**Comment by schildbach** [comment]
And also, Biteasy will shut down on Friday. There is a new version 5.12 on full rollout which switches from Biteasy to Electrum servers for determining UTXOs. It would be nice if you could upgrade to that version and try again. Thanks.

**Comment by deafboy** [comment]
Upgraded to 5.12 and it works like a charm. Thanks :)

**Comment by schildbach** [comment]
Great to hear, thanks for testing!
