### ISSUE TITLE
regtest mode?

### ISSUE THREAD

**Issue by chainhead** [bitcoin-wallet/bitcoin-wallet#372]
Can I use this app to connect to my private blockchain running in regtest mode? I will have a WiFi router to which my laptop (running the regtest chain) and my phone will connect. Therefore, all IP addresses will be 192.168.*.

I am working on a demo and would love to demo the same with a quality app like your's than build one afresh.

**Comment by schildbach** [comment]
Please ask usage questions in [G+ community](https://plus.google.com/b/101256420499771441772/communities/105515929887248493912) or [Bitcoin stack exchange](https://bitcoin.stackexchange.com/tags/bitcoin-wallet-app).

It should be possible, but you need to configure and build your own APK. The version on master is configured for testnet3.
