### ISSUE TITLE
Marking transactions in red and green

### ISSUE THREAD

**Issue by pryds** [bitcoin-wallet/bitcoin-wallet#375]
I noticed that you show received payments in green and sent payments in red. It is probably not wise to use those exact two colours, unless you change to a very light red and a very dark green, or vice versa, or unless you plan to let users choose alternative colour codings, since roughly 8% of all male users will have problems differentiating them.

Here are a couple of articles on how to avoid problems like this:
https://designshack.net/articles/accessibility/tips-for-designing-for-colorblind-users/
http://understandinggraphics.com/design/designing-for-color-blindness/

**Comment by schildbach** [comment]
For the color blind, there are +/- signs in the amount. The colors are entirely redundant.
