### ISSUE TITLE
enabling dynamic prices on static QR codes - reconsider BIP 72 compliance?

### ISSUE THREAD

**Issue by shesek** [bitcoin-wallet/bitcoin-wallet#377]
I have an interesting use case that is made impossible due to the [BIP 72 incompatibility](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/94): enabling dynamic prices on static QR codes.

We are selling some products at the Tel Aviv Bitcoin emBassy using static BIP 21 QR codes that are printed and attached to the products (see the jars on the right [here](http://cryptopotato.com/wp-content/uploads/2016/07/EMBASSY_8275.jpg), or a closeup [here](http://www.bitembassy.org/wp-content/uploads/photo-gallery/IMG_8590.jpg) [0]). The problem is that keeping these QR codes updated to reflect the current exchange rate is quite an hassle, leading to prices constantly getting out of sync (our bamba is currently twice more expensive than it should be!) 

My solution was to create a little service ([shesek/bitcoinuri](https://github.com/shesek/bitcoinuri)) that dynamically generates payment requests based on the current exchange rate. The final bitcoin URI, with this service embedded, looks like that:

    bitcoin:1EoNrcZmCpZK1Zzpo5Yey9dvtFQk8t9aiU?amount=0.015&r=https://bitcoinuri.herokuapp.com/1EoNrcZmCpZK1Zzpo5Yey9dvtFQk8t9aiU/15/USD

I was hoping that this would allow older wallets to use the BIP 21 static price, while newer wallets use the BIP 70 payment request to fetch the updated price from the server. But, as you probably already figured out... I learned that this doesn't actually work :-(

So, my question is: is there any chance you would reconsider relaxing the rules relating to the BIP 70 payment request matching the BIP 21 details? I see two options here:

1. Skip the checks when no address/amount is specified (the `bitcoin:?r=https://...` URI format). This would be an improvement, but it won't work at all for wallets without payment protocol support.

2. Just skip the checks entirely, even if the address/amount is specified. This would be the most ideal solution for my needs, as it would gracefully degrade on older wallets.

I understand that there are some security concerns here, but I think that at least for the case of scanning a QR code they're pretty negligible. Unlike with clickable payment links, where the user can be deceived by showing him one amount in the BIP 21 URI (when he hovers the link) and then using a different amount in the actual BIP 70 payment request, users scanning a QR code have nothing to compare the BIP 70 amount to (unless they're able to [manually read QRs](http://blog.qartis.com/decoding-small-qr-codes-by-hand/)), meaning that there's no option of deceiving anyone due to the mismatch.

Are there any other security concerns that I'm not considering?

[0] For anyone wondering, that sign in Hebrew reads *"donate 2 millibits and the snack is on us. full retail price: 100 shekels (~$25)*" :smiling_imp:

**Comment by shesek** [comment]
Two more interesting use-cases:

- Updating the product prices from the server, without having to replace the QR codes. (that is, non-conversion-rate related changes, but simply us wanting to change the prices)

- Avoiding address re-use by having the payment protocol server derive a new one for each request. This is a major one for me - re-using the same address causes a serious privacy leak to both the emBassy and its customers. This would give us an easy way to fix that, at least for BIP 70 supporting wallets.

**Comment by schildbach** [comment]
Rather than breaking the trust chain, I propose the following idea:

- Your server signs the payment request (it probably already does).
- You put a hash of the (public) key/certificate being used for signing into the QR code (we need to come up with a standard).
- Wallet apps would check that hash before proceeding with the payment request.
- Instead of pinning the direct signing key, the hash could also PIN one of the intermediary keys/certs all the way up the X.509 trust chain. This would be somewhat similar to what DANE does.

This should support all of your above usecases.

P.S. Great little shop you have there!
