### ISSUE TITLE
Add language switcher

### ISSUE THREAD

**Issue by verdulo** [bitcoin-wallet/bitcoin-wallet#380]
Please add language changer to the options, so user could display the program in any language he wants (for example Esperanto) instead of system language.

**Comment by schildbach** [comment]
I think the localization mechanism for a feature like this would complicate the app a lot. Feel free to try and propose a technical solution via PR.

**Comment by ligi** [comment]
you could do it like this on 17+ - technically: https://github.com/linkedin/test-butler/blob/master/test-butler-library/src/main/java/com/linkedin/android/testbutler/TestButler.java#L220

but I do not really see the use-case. And would not do it for my apps
