### ISSUE TITLE
[feature request] Allow spending of unconfirmed "change" outputs

### ISSUE THREAD

**Issue by jonathancross** [bitcoin-wallet/bitcoin-wallet#385]
After a payment is made, the wallet balance can become unusable until the previous transaction is mined.  The user is not informed, but rather gets a strange error indicating that not enough funds are available.

Considering transactions can now take a very long time to confirm, this becomes a serious usability issue and may even lead people to believe they have lost money temporarily.

Other wallets like Mycelium do not have this restriction.

**Comment by schildbach** [comment]
I take it you're running in trusted peer mode?

**Comment by luke-jr** [comment]
To do this safely, the wallet would need to be prepared to re-sign the transaction in the event that the one generating the change is malleated before getting mined. (True whether a trusted peer is used or not.)

With an untrusted peer, perhaps someone could make an invalid transaction spending the wallet's coins, but it should be possible to detect these being invalid at least.

**Comment by jonathancross** [comment]
Yes, I'm running with a trusted peer ([via Tor for authentication & encryption](https://github.com/jonathancross/jc-docs/blob/master/Bitcoin_mobile_privacy.md)).  Is that causing cause the behaviour I am seeing?

**Comment by schildbach** [comment]
Yes, it's a known limitation of the Bitcoin protocol. If you're connected to only one peer you won't hear back any transactions you created and sent so we cannot know they are broadcasted and propagated.

**Comment by jonathancross** [comment]
Thank you both for your input.
In my particular situation, I had sent a payment which was a few hundred satoshi too small, so I was upset when there service timed out before I could add the last few cents...

After a few days, the wallet allowed me to spend the "change" in a new transaction, even though the first tx was not yet mined.  I added a larger fee this time and both got mined (Child-Pays-For-Parent).

> If you're connected to only one peer you won't hear back...

Since my wallet created the transaction, why does it need to wait to "hear back"?

The concerns about an attacker deliberately manipulating the first transaction (and therefore invalidating the second) seems unlikely and not particularly dangerous.  This can happen with any transaction today from what I gather and just needs to be handled by recreating the second transaction and rebroadcasting.  Or am I misunderstanding?

**Comment by schildbach** [comment]
The "hearing back" is usually no big deal, but it gives confidence the transaction will be mined so we can build on it. Maybe in the single trusted peer usecase we should open two connections to the same peer. Though I'm not sure if Core is ok with that.

**Comment by roffl1990** [comment]
I have trouble with an unconfirmed transaction too. It is an donation with low fee. 

I'm running the client in normal mode without trusted peers.

Is it planned to implement a option to spend unconfined change?

**Comment by schildbach** [comment]
@roffl1990 Your problem is different as in your case its an incoming payment. We can't do anything about these cases.

**Comment by roffl1990** [comment]
No it was an outgoing transaction. On replays of the blockchain it was mysteriously shown as a income.

I higherd the few and the traction passed.

For next time: when I wait a few days and​ the transaction removes out the mem-pool and replay the blockchain I can spend the coins again. Right?

**Comment by schildbach** [comment]
Ah, actually this has been implemented some months ago, by disconnecting (and reconnecting) peers that have had transactions broadcasted to.

**Comment by jonathancross** [comment]
Ah, great to know  :-)
