### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by francwalter** [bitcoin-wallet/bitcoin-wallet#386]
I imported the project in an actual Android Studio but I got this error:

Gradle sync failed: Gradle version 2.10 is required. Current version is 3.3.

Could the fitting Gradle version in this project could be updated?

Thanks, frank

**Comment by schildbach** [comment]
The build target is Ubuntu LTS (16.04 at the moment), and it only has Gradle 2.10. Even the latest Ubuntu zesty, due to be released in a few days, only contains Gradle 3.2.1.

**Comment by francwalter** [comment]
So how to compile it on an actual Android Studio?

**Comment by schildbach** [comment]
I'm not sure about Android Studio, I'm using Eclipse. You should be able to use an old version though, as it used to work a couple of months ago. Or you can adapt the Gradle version on your local branch.

**Comment by shkschneider** [comment]
I'm using Android Studio and just re-imported the project, fresh from this repository.
Let Android Studio add the gradle wrapper and dont update anything else.
It compiles and runs fine on my Ubutun 16.04 LTS.
Recommend to close that issue.

**Comment by schildbach** [comment]
@shkschneider Thanks for retesting this.
