### ISSUE TITLE
Please make the fee setting visible before sending on the Send Bitcoins screen

### ISSUE THREAD

**Issue by bdimych** [bitcoin-wallet/bitcoin-wallet#392]
Several last weeks there is a flood of transactions and to set correct fee is very important if I need to send it quickly,
but I often just forget to set priority because it is not visible and by default it is "Normal"

**Comment by accumulator** [comment]
I agree, you should get a confirm screen which displays clearly the fee before actually sending. My 10$ transaction a few days ago had a 6$ fee attached :(

**Comment by schildbach** [comment]
The fee is clearly shown before you press "Send".
