### ISSUE TITLE
Push to fdroid

### ISSUE THREAD

**Issue by matlink** [bitcoin-wallet/bitcoin-wallet#397]
Fdroid version of bitcoin-wallet is stuck at version 5.18. And google play store version of this apk has not the same signature I guess (conflicting package name when installing).
Any info on it not to compromise the trust chain?

**Comment by schildbach** [comment]
I'm not sure who's responsible for the fdroid version these days. We suggest you examine the build logs and see what's wrong.

**Comment by schildbach** [comment]
Apparently before the current version can be built again, this issue needs to be resolved: 
https://gitlab.com/fdroid/fdroidserver/merge_requests/275

**Comment by schildbach** [comment]
The version at f-droid is up to date again.
