### ISSUE TITLE
Backup file corrupted?

### ISSUE THREAD

**Issue by megadan76** [bitcoin-wallet/bitcoin-wallet#398]
I'm wonder if it's possible to confirm if a backup file is corrupted. 

I've decrypted the backup file using the openssl enc -d -aes-256-cbc -a -in <filename> command and it did  not throw a password error. 

However, the decrypted file is just garbage, it's not protobuf or Base58 format.

Is there anyway to know for sure if the actual backup file got corrupted? I originally restored it from my old phone which was dropped and screen destroyed (100% black/unusable), by copying it off the SD card.

Should I keep guessing passwords for the rest of my life, or is there a way to prove the file is corrupt so I can just accept the lost value and move on? The original backup would have been created in February 2014 if that matters.

**Comment by omersiar** [comment]
you said openssl did not throw wrong password error, decrypted wallet file should look like either as protbuf or as base58 key list. what is the output look like, did you follow the steps from this link? http://gary-rowe.com/agilestack/2011/12/28/how-to-recover-lost-bitcoins-from-an-android-wallet/

**Comment by omersiar** [comment]
can you open *encrypted* file with notepad++ ?

**Comment by megadan76** [comment]
That link looks to be out of date, I used the steps that are copied here: https://github.com/zeitcoin/zeitcoin-android-wallet/blob/master/wallet/README.recover

The output looks like garbage to me, here's the first characters: ©çïËðåi|ðX¡ÂÒU½õWÁ½ÓIµžÇÿ1wŽµ¹éE¥«šlªX#Ð.ÂmVuå‰Âf0)

The original encrypted file opens fine in Notepad++ and looks like a standard encrypted file (standard characters not garbage like the decrypted version.

**Comment by schildbach** [comment]
The first thing you should check is if the base64 armoring is still intact. Also check for correct padding at the end. On Linux, you can use `base64 -d` to base64-decode the file.

**Comment by omersiar** [comment]
if the *encrypted* file looks ok and has padding at the end chars, i strongly believe your *encrypted* wallet file is not corrupted.
i do not know if there is a sanity check for the encryption, or checksum, i would check that too
if you think you had set a short passward back in the day you can brute force it.

**Comment by megadan76** [comment]
Thanks, I'll boot a linux distro now and check that... how do I confirm if the padding at the end is correct?

Is it possible for a file to decrypt using a password that is close to but not an exact match? I was under the impression that that wasn't a thing. I'm fairly confident in the password, which is not short - it's a proper multiword and number passphrase, the only thing I'm unsure about is the exact capitalisation I used, but the password I am using that decrypts (both in command line and in the app)  matches the type of pattern I would have been using for my passphrases at that time.

**Comment by omersiar** [comment]
padding should go all the way to end of the column,

password should match

**Comment by schildbach** [comment]
@megadan76 The last line needs to contain a multiple of 3 of characters. This is achieved by adding either no padding, or '=', or '=='. If you see padding, this is a good indicator the backup file wasn't truncated somehow. If you don't see padding and the last line does not follow the 'multiple of 3' rule, the file probably isn't complete (but could perhaps still be used to recover the wallet).

**Comment by megadan76** [comment]
So attempting to decode using base64 command spits out  "Salted__>�1T��u�:��[" and continues with the garbage characters, like the decrypted file. 

I don't see anything that resembles padding; the encrypted file is 249 bytes and ends in "==" which seems like it could be just a coincidence or it could be your padding, not sure. 

Given that the only password that's made it further than 'bad password' is the one I'm using and it makes sense to me as being the password I remember, I'm fairly confident that it is right - using slightly different caps or numbers throws a normal bad password error.

**Comment by megadan76** [comment]
Thanks @schildbach sounds like the padding is intact, then. 

So the million dollar (fortunately not literally) question remains, why is it decoding to garbage? Is it theoretically possible to decode garbage due a password that "works" but is wrong?

**Comment by schildbach** [comment]
The `Salted__` prefix in the encrypted but base64-decoded file is another indication that the encrypted file is intact.

The thing with decrypting is there are no "bad private keys". If you pick the "wrong" one, you simply get a different plaintext (in most cases). It is up to the application developer to check the resulting plaintext for consistency. The [README.recover](https://raw.githubusercontent.com/bitcoin-wallet/bitcoin-wallet/master/wallet/README.recover) describes how to do that manually.

**Comment by megadan76** [comment]
Thanks - so it sounds like it's still a bad password, but maybe it's close... I guess I will keep trying password combos... might have to hack together a script to try different capital/space/number combos until I find the right one.

**Comment by megadan76** [comment]
Sorry just to chase this down one more time for my own sanity: If i take the output (the decrypted file) and view it it's just junk like above, however if I decode it using a base64 command it displays "normal" but encrypted looking data, larger than the original backup file but with a single "=" ending.

I'm assuming that all I've done here is decode a file with a bad password and simply decrpyted it into meaningless plaintext,  like you described above. 

The only thing that irks me is that I'm fairly confident this is the right password, since none of the close variations work, and this backup is from February 2014 which is right before the backup formats changed...

Not sure if there would be any value to trying to load an old version of the app, considering that it's not decrypting properly on a PC either, but if any one has any other wild or out there suggestions I'm all ears. 

If not I will close this out - thank you all again for the help.

**Comment by omersiar** [comment]
with base64 -d command you are decoding a base64 encoded data which is still encrypted. i made some google search on openssl behaviour, if openssl does not throw a password error this does not always mean the given password is correct, but with the correct password always outputs correct data.

**Comment by megadan76** [comment]
Right, that makes sense - it's just showing that the data never decrypted, even though it took the password - which I guess makes it a false positive.  

That certainly sounds like the only explanation, though I see that other people  have had the exact same issue: https://github.com/bitcoin-wallet/bitcoin-wallet/issues/135 - identical situation for those 2 users around the same time frame. 

Again seems odd but entirely within the realm of possibility - the Occam's razor explanation is probably just that we used similar passwords elsewhere and are just remembering them wrong. Frustrating but ultimately probably not a software glitch I guess.

**Comment by omersiar** [comment]
did you just make a backup within the app and give the password and nothing else right? you backed up the data and now you are trying to get your private keys. i did exactly that a couple days ago in order to just check if its working.

human brain tend to believe its going to remember the passphrases but in fact not using passphrase in a long time makes it fade away from your memory. i bet the password was not the one that you believe it is, right now. since you said the password should be complex (if you always set strong passwords) brute forcing will take long time perhaps infinity.

you may also dealing with the wrong backup.

memory can fail, this is why most wallet apps suggest you the write it down on secure place.

we are learning it the hard way.

**Comment by megadan76** [comment]
Yeah exactly, this was a backup created in the app and then later restored to my new phone and PC, enter the password to restore and it fails. This is the only backup, alas. 

I think so, I guess in this case we will have to blame the wetware and not the software :D

**Comment by omersiar** [comment]
can i take a look at your encrypted wallet? if you willing to take the risk to lose yor coins? mail me at omer_baysal {at} msn dot com and your possible password

**Comment by megadan76** [comment]
Sure, I have nothing to lose, so if you steal all my coins I'm still in the same place, so why not...

**Comment by omersiar** [comment]
normally this is not feasible approach, but i have time nowadays. let's see what happens and do not forget to treat your private keys as real money. bitcoin is now at 2.400 usd levels. who knows after 2 years what it will become, even if your wallet has only a few satoshis in it.

**Comment by megadan76** [comment]
Yeah it's not much but with the current price it's just enough to bug me, hah, especially if the price keeps going. 

Fortunately I had a separate wallet on my PC that was unaffected as well with a different stash, so I'm still in the game. 

Sent you an email, good luck.

**Comment by schildbach** [comment]
Closing this, as I believe nothing can be done on our end.
