### ISSUE TITLE
Wallet will not send bitcoin

### ISSUE THREAD

**Issue by amundae** [bitcoin-wallet/bitcoin-wallet#399]
Hi All,
I have used the app for years and it only recently started having issues. The issues started a few weeks ago when I tried to transfer to a different wallet, and it never confirmed, this happened twice, one of the transactions is still sitting there unconfirmed, the other disappeared after I rebuilt the block chain.
See said transaction here: https://blockexplorer.com/tx/a9f1b29ad83928235c627c84cc6f4d3be1a6a71702cfdc89f45ea045d3564ef6

And now it says I have 39.59 mBTC, but when I try to send any it seems to think I only have .05 mBTC. What can I do to fix this? I'd be happy to provide the extended pub key if anyone needs it, not much besides back and forth with Coinbase in there.

**Comment by schildbach** [comment]
Can you use Options > Report issue?
