### ISSUE TITLE
I can't send bitcoins

### ISSUE THREAD

**Issue by Narfware** [bitcoin-wallet/bitcoin-wallet#400]
I found this bug when i try to send my bitcoins to another wallet.
![screenshot_2017-05-27-15-22-01-487_de schildbach wallet](https://cloud.githubusercontent.com/assets/22813609/26521800/26528066-42f2-11e7-8734-70f00f736c48.png)
![img_20170527_152302](https://cloud.githubusercontent.com/assets/22813609/26521802/2b38411a-42f2-11e7-9111-6c81a95b0548.jpg)

**Comment by schildbach** [comment]
Can you use Options > Report issue?
