### ISSUE TITLE
Use 'last' from BitcoinAverage exchange rate response insted of daily average. 

### ISSUE THREAD

**Issue by m-schmoock** [bitcoin-wallet/bitcoin-wallet#401]
In time of writing this (28.May2017) the app shows a Eur exchange rate of 1870 Euro (which is the btcavg daily average. However prices currently are very volatile. So there is a gap of ~10% which can be a huge problem.

```
https://apiv2.bitcoinaverage.com/indices/global/ticker/short?crypto=BTC

 "BTCEUR": {
        "last": 2041.11,
        "averages": {
            "day": 1872.274352
        }
    },
```

My suggestion: always use the 'last' indication as the exchange rate and maybe have a refresh button somewhere. Refresh the data before each send/receive action and also when the app goes to foregound. Myceilium for example seems to be using the 'last' indication of BtcAvg and they dont seem to have a problem.

Alternatively we could indicate visible a warning incase 'last' and 'day' (averages) diverges by a threshhold of i.e. 3%.

**Comment by schildbach** [comment]
The whole point of using an average is to reduce the volatility. Euro prices are not very exact anyway, because of the market differences.

**Comment by m-schmoock** [comment]
It's true that averaging reduces seen volatility, but that does not solve any roblem. I guarantee you that neither Bitpay, Coinbase, Xapo, Shapeshift or any other exchange or service would charge you rates that are 10% off against their own interest in any moment.

By relying on the daily average you are almost certain to have the wrong value whereby using the 'last' estimate you are at least close in the moment you do the transaction. You do not gain anything by using the average. Only in good case scenarios you can be close.

So the thing is not to try to 'reduce' Bitcoins inherent volatility, but to deal with it addequatley. Showing users simply wrong values by design does not solve any pain but causes it.

Please reconsider why not using the 'last' estimate?

**Comment by schildbach** [comment]
I suggest thinking a bit outside the Dollar. Even the Euro, not a small currency, can produce extreme (+/- 50%) spikes in low-volume markets (e.g. https://bitcoinwisdom.com/markets/bitcoinde/btceur). It gets even worse for tiny (but important) markets all over the world.

So some time-averaging is needed. I agree we could try a 12 hour window or maybe even 6 hour, but BA does not provide this data atm. Maybe you would like to convince them to provide more windows?

**Comment by NiKiZe** [comment]
Or just make this a user selectable option?

**Comment by m-schmoock** [comment]
Im sorry, but I think you are mistaken. I dont think that a time average, regardless the interval, has any benefit. Let me explain:

BitcoinAverage data (especially for large currencies like EUR or USD) is already averaged and weighted accross a wide variety of exchanges. Note: this is not time average but cross market average. They let you access this momentary cross market average using the `last` field. It is quite accurate, and a good measurement when not focusing on only one exchange.

But when using any form of time average (especially huge intervals like daily) will only give you bad user experience results especially when having a very volatile day. You will notice that when you buy any good using providers like Bitpay, your rate will then significantly differ from the rate that you are charged. You feel confused or even tricked in this case.

Hence you dont gain anything from time averaging. You only confuse people. The `last` estimate is aready averaged and weighted accross a wide range of exchange, sudden spikes here are "not bad" or something rather than just the correct indication that the price is fluctuation accross board already. Why "hide" that from the user?

By using any time average (be it daily, 12Ht 6Hr, ...) you dont gain anything. If you think otherwise, please explain what you expect to gain from using a distorted time average, especially like the daily interval?

**Comment by kitsuphat2528** [comment]
ทำต่อให้เสร็จ

**Comment by m-schmoock** [comment]
Thx for implementing this anyway <3
