### ISSUE TITLE
Document fees

### ISSUE THREAD

**Issue by wernight** [bitcoin-wallet/bitcoin-wallet#404]
On that same note the [`wallet/README.md`](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.md) shows where one can change the fees, but there is not unit in [`wallet/assets/fees.txt`](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/assets/fees.txt).

From the code it does:

    sendRequest.feePerKb = fees.get(feeCategory);

So it looks like they are Satoshis per KB.

**Comment by schildbach** [comment]
Fixed in 6415f24054ae00bcab1fd67ada056d9e3933bb81.
