### ISSUE TITLE
Show estimated translation confirmation time

### ISSUE THREAD

**Issue by wernight** [bitcoin-wallet/bitcoin-wallet#405]
Naively everyone would select the lowest transactions fees. Especially since the block size isn't show in the UI, it'd be very useful to use something like https://bitcoinfees.21.co/ to estimate the transaction confirmation time.

**Comment by schildbach** [comment]
Currently we're mostly using https://jochen-hoenicke.de/queue/ to adjust the values.

**Comment by wernight** [comment]
Both look great, my point is showing an rough estimated time for each priority. For example knowing that it costs 0.16 for economy may sound fine... until you see that you'll likely get confirmation only after a few days or more.

**Comment by schildbach** [comment]
It's impossible to estimate confirmation time. Sites like bitcoinfees look at the past, but the future can be totally different.

You have probably noticed the warnings that come with each fee level. They give a rough explanation.

**Comment by wernight** [comment]
Could we give a rough idea?

**Comment by schildbach** [comment]
Feel free to PR a suggestion to the `send_coins_fragment_hint_fee*` strings.
