### ISSUE TITLE
How to compile bitcoinj / wallet-tool on windows?

### ISSUE THREAD

**Issue by jonjonez** [bitcoin-wallet/bitcoin-wallet#406]
Hello, I have decrypted the backup file  using the gitbash: "opensssl enc -d -a -in bitcoin-wallet-yyyy-mm-dd > bitcoin-wallet-decrypted-backup" and entered my backup password. But now according to the document readme.recover I have to use the tool: wallet-tool to finally decode the file that is in the protobuf format. And I want to extract the seed to import some keys for my bitcoin-qt. For in the bitcoin wallet application do not have the option to sign and verify signatures of the wallet addresses because and if I need to sign an address to prove to another person that I am the owner of the address both to receive or to prove that I own the private key address.

But for starters, how can I compile this tool and finally extract the 12 mnemonic words inside the backup? I found the document very technical and I'm not familiar with this, so could you tell me which command to use without complications? And where do I have to use the wallet PIN to decode and access the 12 mnemonic words?

**Comment by schildbach** [comment]
Windows is not supported. You can use Ubuntu in a virtual machine.

**Comment by jonjonez** [comment]
I am already in Ubuntu, I execute the command: "sudo apt install git"
and then: "git clone -b release-0.14 https://github.com/bitcoinj/
bitcoinj.git" only then came the problem, from now on I do not know what to
do.

In short: I have the backup already decoded by openssl, I already have
Ubuntu, I have bitcoinj / tools / bitcoinj / tools ready, but ...

When I try to give the command: "./wallet-tool reset.
--wallet=/tmp/bitcoin-wallet-decryted-backup
./wallet-tool sync. --wallet=/tmp/bitcoin-wallet-decryted-backup.
--debuglog" he returns me: "Compiling WalletTool to a JAR
./wallet-tool: Line 9: mvn:  command not found"

That is, the decoded backup is in the same directory as the /bitcoinj/
tools/bitcoin-wallet-decryted-backup

Please, tell me what am I doing wrong? give me a light

Em 02/07/2017 13:37, "Andreas Schildbach" <notifications@github.com>
escreveu:

**Comment by schildbach** [comment]
> I execute the command: "sudo apt install git"

Where did you get that from? Please follow the instructions carefully.

**Comment by jonjonez** [comment]
here... https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md

**Comment by jonjonez** [comment]
What is the command to dump wallet? Please, give me an example.  As the
wallet is HD it no longer imports the backup file for the multibit classic
and the bitcoin wallet application neither import anymore multibit classic
private keys.
I followed the instructions of
https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md
but it did not help me.

2017-07-02 15:26 GMT-03:00 Andreas Schildbach <notifications@github.com>:

**Comment by schildbach** [comment]
Study the "apt install" command again carefully. It should solve your above problem.

**Comment by jonjonez** [comment]
Thank you I will take look at it.

2017-07-03 11:50 GMT-03:00 Andreas Schildbach <notifications@github.com>:
