### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by PanderMusubi** [bitcoin-wallet/bitcoin-wallet#409]
Please, add badges for Google Play and F-Droid app stores to the README and technical details files. For example, see https://github.com/AnySoftKeyboard/AnySoftKeyboard how to do this. This will make user install quickers the app when they land at the GitHub repo.

**Comment by schildbach** [comment]
PR welcome.

**Comment by DerPaca** [comment]
#432

**Comment by schildbach** [comment]
Implemented via c16bda142134b8b93294fec9f62dbda146828f38.

**Comment by Tib5743** [comment]
I need help on setting up a bitcoin account, I am 75 yr old  something I do not understand.





-----Original Message-----

**Comment by DerPaca** [comment]
You Have to pay on the wallet for bitcoins BUT you pay and invest for the
50.tiest. ..
IT Means wenn you gave 100e you started with 5000e
And wenn you started with 1000e you became a extra bonus 52.000,00€

You have the choice of your Luck

Tib5743 <notifications@github.com> schrieb am Do., 13. Sep. 2018 18:29:

**Comment by PanderMusubi** [comment]
Badges added via https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1461

**Comment by PanderMusubi** [comment]
Badges added via https://github.com/bitcoin-wallet/bitcoin-wallet/pull/558
