### ISSUE TITLE
Refer to app store in general

### ISSUE THREAD

**Issue by PanderMusubi** [bitcoin-wallet/bitcoin-wallet#410]
Please refer to 'app store' instead of 'Google Play' because this app is also available in other app stores such as F-Droid. For this, only change 4 strings in https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/res/values/strings.xml and let the translation at Transifex do the rest of the work.

**Comment by schildbach** [comment]
Those strings should only show if you've installed via Google Play. F-Droid will get their own strings as soon as we can publish on F-Droid with our own signature.
