### ISSUE TITLE
Support Android adaptive icons

### ISSUE THREAD

**Issue by TheCraftKid** [bitcoin-wallet/bitcoin-wallet#415]
Since the Android O final release is coming up, it's recommended that Bitcoin Wallet supports [adaptive icons](https://developer.android.com/preview/features/adaptive-icons.html) to be consistent with other apps targeting O. I'd be happy to submit a PR.

**Comment by schildbach** [comment]
Yes, please. However, we're not yet targetting O.

**Comment by TheCraftKid** [comment]
Is there an ETA for when Bitcoin Wallet will target O? The final release is around the corner.

**Comment by schildbach** [comment]
There is no hurry. Apps targetting "only" N will run fine on O.

**Comment by schildbach** [comment]
I've got a branch that has this implemented. Will PR soon.

**Comment by TheCraftKid** [comment]
How's this going?

**Comment by schildbach** [comment]
@TheCraftKid Generally great, see #424.

**Comment by schildbach** [comment]
Fixed.

**Comment by 011000110110000101110100** [comment]
Are adaptive icons already implemented? I'm using lawn chair launcher on android 7 and bitcoin wallet doesn't provide an adapted icon.

**Comment by TheCraftKid** [comment]
Adaptive icons are only supported on Android 8.0 and above. Bitcoin Wallet on the Play Store gained them a couple versions back.

**Comment by schildbach** [comment]
I don't know how they do it, but Nova Launcher supports adaptive icons back to Android 5.

**Comment by 011000110110000101110100** [comment]
I'm using bitcoin wallet downloaded on fdroid, and lawn chair launcher supports adaptive icons on android 7. Though the feature is backported so that might be the reason why it doesn't work for me.
