### ISSUE TITLE
Support notification channels (Critical)

### ISSUE THREAD

**Issue by TheCraftKid** [bitcoin-wallet/bitcoin-wallet#416]
Apps targeting Android O [must support notification channels](https://developer.android.com/preview/features/notification-channels.html) or else notifications will not be shown. I propose adding a default notification channel for transactions which will include notifications for received bitcoin and user activity updates. Ideas for more notification channels are welcome.

EDIT: While I know this app isn't targeting O yet, even apps not targeting O that are running on O will have [reduced functionality](https://issuetracker.google.com/issues/62907528), so this is still somewhat important.

**Comment by schildbach** [comment]
Sounds reasonable.

**Comment by schildbach** [comment]
I've got a branch that has this implemented. Will PR soon.

**Comment by schildbach** [comment]
Fixed.
