### ISSUE TITLE
Recovery lost phrase backup .dat

### ISSUE THREAD

**Issue by int211** [bitcoin-wallet/bitcoin-wallet#417]
Sirs, someone know any way to recovery a pass-phrase from a backup .dat maked some time ago in bitcoin-wallet.

Best regards.

**Comment by schildbach** [comment]
Our backup files are not .dat files. You're probabyl looking for [Bitcoin Core](https://bitcoincore.org). And no, there is no recovery as far as Bitcoin Wallet goes.
