### ISSUE TITLE
write todo reg. how to get BCC from your bitcoin wallet

### ISSUE THREAD

**Issue by DennisFantoni** [bitcoin-wallet/bitcoin-wallet#419]
If you had stored 10BTC in your bitcoin wallet, you would be entitled to about 3 BTC at the current BCC to BTC rate as of 2017-08-03 06:12

However, it seems to be fairly non trivial to get the private keys out of a bitcoin wallet, in order to get them into a BCC compatible wallet and send the BCC to an exchange.

The docs indicate you control your keys, but we need a readme that details how to get keys out, and preferrably how to get them into a BCC wallet, for instance the bitcoin core clone bitcoinABC wallet.

i have gotten as far as to using wallet-tool dump --dump-privkeys on a decrypted wallet backup but i can't seem to find any private keys in the resulting output.

output looks like this , i can't find anything that can be imported into e.g. a bitcoin core style wallet (bitcoinABC for instance)

Keys:
Earliest creation time: 2017-04-22Tnn:nn:nnn
Seed is encrypted
Seed birthday: nnnnnnnnnn  [2017-04-22T22:30:06Z]
Key to watch:  xpubxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  addr:1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  hash160:5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  (M/0H/0/0)
  DeterministicKey{pub HEX=0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, isEncrypted=true, isPubKeyOnly=true}
  addr:1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt  hash160:2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  (M/0H/0/1)

also tried raw-dump --dump-privkeys in that case there was some encrypyted_private_key fields, containing what looked like encoded binary data, but these data did not look like anything that could be pasted into a core wallet as a private key.

I could give up, but then I would lose BCC equivalent to about BTC 3 at current rates, because i believed that it was possible to get the private keys out of  bitcoin wallet, that claims that it makes you control your private keys.

so... please put in a readme explaining how people can get at their BCC if they had BTC stored in their schildblatz going into the fork.  it's quite a lot of money that's gone missing, for me alone it's more than 7000 USD at current rates.

**Comment by HashEngineering** [comment]
The private key is after this text:  priv WIF=

What follows the = is a compressed private key.  The format of Private Key WIF Compressed is 52 characters base58 and starts with a 'K' or 'L'

A wallet may have more than one private key.

**Comment by schildbach** [comment]
@DennisFantoni Your wallet is encrypted, because you set the spending PIN. Use the `--password=<pin>` option.

**Comment by DennisFantoni** [comment]
Thanks for replying. Unfortunately i cannot get things to work. 

I have no luck with using --password=pinpinpin  the output is exactly the same no matter what i put in place of pinpinpin.

my commandline is this

./wallet-tool dump --dump-privkeys --wallet=./wallet_filename --password=pinpin  -  >output_file

the output_file.txt does not have the text WIF anywhere
the output_file.txt does not have the text priv  anywhere

am i using the correct commandline above ?

**Comment by DennisFantoni** [comment]
@AndreasSchildbach

I used the --password=1234  option ( with 1234 replaced by the correct
spending pin ).
still, no WIF text in the file, and no priv text in the file.

i tried therse with no success :

./wallet-tool dump --dump-privkey --wallet=./walletfile --password=1234 >
outfile.txt
./wallet-tool dump --dump-privkeys --wallet=./walletfile --password=1234 >
outfile.txt


the file output is in both cases like this  :


Wallet containing 0.00080248 BTC (spendable: 0.00080248 BTC) in:
  0 pending transactions
  1 unspent transactions
  23 spent transactions
  0 dead transactions
Last seen best block: 478788 (2017-08-03T02:12:54Z):
00000000000000000056b1869264b9825a767c6e139ddcefd4c888bef0eeabb5
Encryption: AES-256-CBC, Scrypt (N: 65536)

Keys:
Earliest creation time: 2017-04-22T22:30:06Z
Seed is encrypted
Seed birthday: nnnnnnnnnn  [nnnn-nn-nnT22:30:06Z]
Key to watch:
 xpubnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
and a lot of repeats of :

  addr:nnnnnnnnnnnn  hash160:nnnnnnnnnnnnnnnnnnnnnnnn  (M/0H/0/0)
  DeterministicKey{pub HEX=nnnnnnnnnnnnnnnnn, isEncrypted=true,
isPubKeyOnly=true}

**Comment by AlldayBoutique** [comment]
Hi dennis
