### ISSUE TITLE
Bitcoin cash

### ISSUE THREAD

**Issue by gekkehenkie2** [bitcoin-wallet/bitcoin-wallet#421]
Hello,

So after reading about bitcoin cash i understand that i need to get a bitcoin wallet that supports bitcoin cash to get bitcoin cash. From what i understand is that i loose the bitcoin cash if i just transfer the bitcoins in the android wallet to lets say bitcoin core wallet on my desktop. I have to get the private keys and import them into the new wallet to get the bitcoin cash. Is this true and if so how do i get my keys from the wallet. I already managed to decrypt my backup file with openssl but all i can see is a lot of characters that dont make much sense to me.

Or will this wallet support bitcoin cash anytime soon?

**Comment by hcw70** [comment]
Hi. I would second that. Or is there a way to export the key into another wallet in a standard way? 

Kind Regards Hauke Wintjen

**Comment by tabooki** [comment]
I am also in this same situation but possibly worse. I transferred my coins to a wallet that supported Bitcoin cash. Now I have a feeling I won't be able to ever get them. I have a backup of this wallet from before the transfer if that helps.

**Comment by Fclem** [comment]
Solution is here :

`[](https://bitcoin.stackexchange.com/a/57549/56844)`

**Comment by tabooki** [comment]
I did everything there but in the dump output there is only keys starting with xpub68vqZNKPpaQ284m7  I don't get a xpriv key. When I import this key into another wallet I get the bitcoin cash showing up but it is a watch only wallet because I don't have the priv key. Any ideas?

**Comment by jivanpal** [comment]
You must use the `wallet-tool` from bitcoinj, the backend that this Bitcoin Wallet uses. Follow the directions [here](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md) (which it looks like you did).

If you have a spending PIN set, you should disable it and create a new backup from which to go through the procedure linked above, as mentioned in the issue I opened [here](https://github.com/bitcoinj/bitcoinj/issues/1431).

**Comment by esuiru** [comment]
Thanks for the info guys. :) Especially @Fclem

**Comment by tabooki** [comment]
Thanks Jivanpal. Disabling the pin and expressing the keys again did the trick. I now have .47 bitcoin cash coins.  ;)

**Comment by schildbach** [comment]
It's best to start such discussions in the [G+ community](https://plus.google.com/101256420499771441772). The question of how to extract the private keys has been [stickied there](https://plus.google.com/101256420499771441772/posts/7ygWZgHLnFK). Instead of entirely removing the spending PIN we suggest to the the `--password=<pin>` option with wallet-tool.

Bitcoin Wallet will not support other cryptos other than Bitcoin, but anyone can fork the app and do so.

**Comment by jivanpal** [comment]
As already mentioned by myself, the `--password` flag does not work as expected. You should look into this, @schildbach.
