### ISSUE TITLE
[Feature Request] Add Bitcoin-Cash support

### ISSUE THREAD

**Issue by Mannshoch** [bitcoin-wallet/bitcoin-wallet#425]
Please add support for Bitcoin-Cash to this app.

**Comment by sanktk** [comment]
Since mobile wallets might get alot more useful again on a chain with low fees (like Bitcoin Cash). I support this request. A mobile wallet on a chain with 5$ fees per transaction doesn't have many use cases on the other hand.

**Comment by DavidGualda** [comment]
Users are migrating to another wallets in order of getting their Bitcoin-Cash associated to their private keys.

**Comment by shkschneider** [comment]
That is the only reason why people want this app to support Bcash: getting their private keys. I'm sorry to say that this is something that should have been prepared _before_ the fork. I managed to get my private keys out of this wallet (using bitcoinj's tools) anyway.
I think this wallet should support whatever main blockchain has the most hashrate -- which is bitcoin, and disagree with this feature request.

**Comment by schildbach** [comment]
Yes, the way forward to full bitcoin cash support is forking this app (and bitcoinj) to create a bitcoin cash version. You could then use the wallet backup and restore feature to use your wallet as a BCH wallet.

This app will not follow other chains than the Bitcoin blockchain (the chain with the most accumulated work, aka longest chain) in the forseeable future.

**Comment by giodegas** [comment]
I am starting to think all of this BCH hype is to revive old wallets to know were their BTCs goes.

**Comment by Mannshoch** [comment]
What is that thing with the private key? I'm not that informed, I got the news about the splitting from the media and thought there would be no problem in using both versions with Bitcoin-wallet. Why should I install a second app only to use Bitcoin cache?

**Comment by jmdugan** [comment]
A better solution would be to have a bitcoin-cash android app that reads the native bitcoinj protobuf format that this client uses.  keep the clients separate, the dev teams are separate at this point anyway

**Comment by schildbach** [comment]
@jmdugan I've heard this is coming.

**Comment by hheexx** [comment]
How about private key export option?

**Comment by mm88mm** [comment]
WHY THE FUCK DO YOU ASK A DUMB FUCK WHO BARELY KNOWS SHIT ABOUT IT?

On Sep 21, 2017 2:48 PM, "Boris Prpic" <notifications@github.com> wrote:

How about private key export option?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitcoin-wallet/bitcoin-wallet/issues/425#issuecomment-331277292>,
or mute the thread

**Comment by jleni** [comment]
I had the same problen and wrote a simple python script to simplify this process.

https://github.com/jleni/wallet-decrypt

You can later get the mnemonic into electrum cash and move Bitcoin cash to another safer wallet.

**Comment by haplo** [comment]
I'm adding some documentation in #450 about how to export the private keys so they can be swept into a Bitcoin Cash wallet.

**Comment by CliffS** [comment]
> This app will not follow other chains than the Bitcoin blockchain (the chain with the most accumulated work, aka longest chain) in the forseeable future.

@schildbach As the Bitcoin Cash chain is now longer than the Bitcoin Legacy chain, does that mean you will be switching to Bitcoin Cash?  In the meanwhile, many thanks to the devs who produced this wallet but I will be using a different wallet in the future as I am currently only holding Bitcoin Cash.

**Comment by schildbach** [comment]
That's why I said "the chain with the most accumulated work" above. "Longest chain" is a sloppy wording. Bitcoin Cash has fallen behind in accumulated work, so our app will not follow it.

**Comment by schildbach** [comment]
I'm closing this now, since no one has implemented support for Bitcoin Cash in Bitcoin Wallet. Rather, there is now a Bitcoin Cash wallet on Google Play: https://play.google.com/store/apps/details?id=com.hashengineering.bitcoincash.wallet
