### ISSUE TITLE
Import wallet

### ISSUE THREAD

**Issue by bom64** [bitcoin-wallet/bitcoin-wallet#426]
I have just installed walleten bitcoin.com to android and I try to import my Mycelium seed. 
I start the app and select 
Restore from backup
I in the tab Recovery I paste the seed.
I don't change any setting in advance.
and select Import backup.

Then I get a long red error message.
 
I dont ue pwd so not that problem.

The D. path is m/44'/0'/0' and as far I know used by Mycelium.

The URL is as default OK?

**Comment by din0146** [comment]
ไช่ โมบายค้าง ผมจึง ทำการรีเซ็ทเพื่อไห้ทำการเข้าระบบได้

**Comment by schildbach** [comment]
You're using a different Bitcoin wallet app. Please go to bitcoin.com.

**Comment by bom64** [comment]
I see.
