### ISSUE TITLE
[Feature Request] Please Made the Bitcoin app enhancable by addon

### ISSUE THREAD

**Issue by Mannshoch** [bitcoin-wallet/bitcoin-wallet#430]
I do not wish a general Add-on Feature.

In my Idea the add-on tool should be really limited an has the only purpose to add other blockchain based currencies.

**Comment by schildbach** [comment]
As a user, an interface for such add-ons would put your bitcoins at risk.

As a developer, please fork the app to add your enhancements.

This app is not multi coin by design. There are forks of this app for lots of other coins, you can easily install the forks you want in parallel to this app.
