### ISSUE TITLE
Add Segwit support

### ISSUE THREAD

**Issue by trampster** [bitcoin-wallet/bitcoin-wallet#431]
Please add segwit support. To allow us to make transactions with lower fees.

**Comment by shkschneider** [comment]
I believe bitcoinj does not support it yet. I also would like SW to be support by bitcoinj...

**Comment by schildbach** [comment]
We're working on it. See https://github.com/bitcoinj/bitcoinj/commits/segwit.

**Comment by prusnak** [comment]
Seems that the development in the branch has stalled, but the SegWit issue is active.

Adding it here, for the reference: https://github.com/bitcoinj/bitcoinj/pull/1441

**Comment by stachrom** [comment]
Is there a ETA around the corner? 

http://segwit.party/charts/

**Comment by artofthesmart** [comment]
Same. Would rather not have to switch wallets to get lower fees. 🙂

**Comment by Wullee** [comment]
Hello, I have this address: 1BTHbHj8s7C1zoSK4EJWWEkfs5V3dJZNLu I have been waiting for a few minutes from the app. But in my pocket, my wallet does not. Can someone give me some advice?

**Comment by kenspratt** [comment]
I've read that after the Segwit2x hard fork every existing Btc holder will receive B2X in the ratio 1:1 and a pleasant bonus. Will users of this wallet also get the extra coins and bonus?

**Comment by bitsabhi** [comment]
@schildbach Will the segwit branch be merged in master? As in will there be production ready release of BitcoinJ with SW? Thanks

**Comment by schildbach** [comment]
It will be merged as soon as it's ready to merge. Currently, at least the HD derivation for segwit addresses is missing. Also, lots of testing.

**Comment by Elijahmtshweni** [comment]
What can I do to regain the lost bitcoin wallet service provider website if
I still have the wallet address. I do not know if I must deposit bitcoins
to this address because I maybe unable to get them again.

**Comment by robotamer** [comment]
I don't want Segwit, I hope you will give us a choice when you add it.
Thanks

**Comment by anonymous73** [comment]
Hi Robotamer,

Please explain why you do not want segwit. Everyone says it will help to solve the scaling issue, although I admit I have yet to see a good explanation of segwit, and the lightning network for that matter.

**Comment by schildbach** [comment]
This is not a good place to discuss likes/dislikes.

I'm closing this issue as segwit has been added to the app. The testnet version is already creating new wallets as Bech32 / P2WPKH by default. The mainnet version will follow.
