### ISSUE TITLE
recover keys from bitcoinj protobuf format without creating and syncing a completely new client

### ISSUE THREAD

**Issue by jmdugan** [bitcoin-wallet/bitcoin-wallet#434]
How do we extract the private keys from the decrypted backup without having to run a complete client instance of bitcoinj?

These instructions:
https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md

show correctly how to decrypt the backup, but then with all backup files after 2014, "RECOVERING FROM PROTOBUF WALLET FORMAT" doesn't have instructions on getting the private keys.  All it basically says is: /download and run this java client, and it can read our format/. That's really not a solution to extracting the keys.

**How do we extract the private keys from the decrypted backup**?

**Comment by schildbach** [comment]
When you get to the point of dumping your wallet, add `--dump-privkeys` to the command line (and `--password` if you're using a spending PIN). It will print the private keys for each of your addresses in WIF (wallet import format).

**Comment by janfjones1992** [comment]
hi sir
i am really tired now, i am done with the process of decrypting and i am stuck on the process of recovering from protobuf format, as the commands given in that master help is showing as invalid commands, after the decrypting i did get the org.bit.production which means my backup file and the password is good and i get some rubbish language as a result now what to do next ?
pls help

**Comment by iwoolf** [comment]
Did you ever solve it? I have a protobuf dogecoin wallet from a whole-phone backup, and none of the tools will work. Wallet-tool from dogecoinj complains about it being dogecoin network instead of bitcoin. I even tried encrypting it with ssl, but the dogecoin app can't import it. I'm stuck with a wallet-protobuf and keys-backup-protobuf. No encryption, but o tools that will let me get my coins.

**Comment by schildbach** [comment]
@iwoolf You should report this to dogecoinj, rather than here.
