### ISSUE TITLE
[Bug?] Scanning "Private Key WIF compressed": problem

### ISSUE THREAD

**Issue by Wikinaut** [bitcoin-wallet/bitcoin-wallet#437]
When scanning a "Private key WIF Compressed 52 characters base58, starts with a 'K' or 'L'" as generated via the generator of https://www.bitaddress.org 

#### Problem
the bitcoin-wallet app appears to try to fetch a wrong bitcoin wallet because I see then 0,00 BTC instead of the correct value.

The correct value is shown when I use the 

* 51 character base58 WIF, starts with a '5', or 
* after adding the password on the BIP38 Format (58 characters base58. starts with '6P').

**Comment by Wikinaut** [comment]
Looks to me like an uncaught NPE.

**Comment by schildbach** [comment]
What version of the app are you using? Can you paste the logs? Why are you assuming a NPE? What's the Bitcoin address of the private key in question?

**Comment by Wikinaut** [comment]
* wallet 5.3.1
* NPE assumed, because: when I scan the 51 character WIF private key after I saw "0,00" for the compressed WIF key, then I saw (often, but not now) the already reported IOERROR. (This is not the case at the moment)
* BTC address sent to you via mail

**Comment by schildbach** [comment]
Can you try version 5.32? I just pushed a fix for a NPE when sweeping wallets. If the problem persists, can you attach a logfile?

**Comment by Wikinaut** [comment]
Unfortunately, the problem persists.

**Comment by schildbach** [comment]
Can you attach a logfile after reproducing this bug?

**Comment by Yahiaelsawiabd1974** [comment]
I ask help from all cause I lose all and don't have one doler please help me as u can I am in a very bad situation  I trust there a lot will help cause it was my money but I am with out experience but I hope all injoy with his money now and I asked God place all of u and u money and I forgive all and ask God forgive all  ,,,, put really i don't have one dollar and I was prepared this money for my coner operation but  I lost all specially the site for my wallet  BTC.com hacked the rest a lot. ... any way it Is u choice for helping or no  , in any choice I ask God place u and u family from any bad thing and enjoy u life and don't trust BTC.COM  .... it is my address 

For  BTC
 1JmPry6jv8kGGaPo5PwYisQKmiCnQtLTbm

For  bitcoin cash 
qrmuw07q8ak0txwvgh5pmfl7whp7s2p46sekcp8ljv

For dash 
XhAodpuABN7pJawqbjsc1uCVbb6RQvZnhM

For cash and Ethereum and more
P83724538    payerr
Please believe me I need your help in this address cause as I told you I don't have experience for make  any transfer or any technical step 
I have a documents for the site BTC and the company who huck all what I have but I am not American but I need help for make a report in the American embassy and the interpol  ,,,  cause if I dead in the operation my kids can't live so I ask if any can help to return my right ....... sorry for all this drama and thank you in any case God place all of you .

**Comment by dodga69** [comment]
I cannot get my money out of my bitcoin wallet it comes up unspent and when I click on it nothing happens

**Comment by schildbach** [comment]
Closing this issue, as the reporter didn't get back.

**Comment by Wikinaut** [comment]
oops, I am still around, will check later.

**Comment by schildbach** [comment]
@Wikinaut If you try to reproduce the problem, please make sure to use version 7.07+ of the app. It has been tested to be able to sweep both Base58 and Bech32 addresses of compressed private keys and just Base58 addresses of uncompressed private keys.
