### ISSUE TITLE
Geting my private keys

### ISSUE THREAD

**Issue by AngelClaw** [bitcoin-wallet/bitcoin-wallet#438]
Hello, I really don't know if this is the best place to ask this but I've been looking all over the net and can't find an understandable way to get my private keys fom my wallet. I've been using the app since 2015 and I'm interested in getting the key to receive the BCH from the btc/bch fork. How can I get it?

**Comment by Cetee** [comment]
Hello, i need help for the same issue. 
Please help!

**Comment by golam9590** [comment]
hello and thanks
please support me and help
