### ISSUE TITLE
Bitcoin Cash help

### ISSUE THREAD

**Issue by jgostylo** [bitcoin-wallet/bitcoin-wallet#442]
I was trying to figure out how best to separate out my Bitcoin Cash that is currently on my mobile wallet.  I am assuming that Bitcoin Cash is not an option in the wallet.

I saved a backup of the wallet and wanted to just use the backup with my desktop QT client.  I did not see any documentation about that and the mobile backup wallet does not look like the typical wallet.dat files.

What is the best practice for this?

**Comment by axel-lasseur** [comment]
I'm in the same situation. I'm lost with my backup file

**Comment by lviggiano** [comment]
Me too
