### ISSUE TITLE
F-droid builds out of date

### ISSUE THREAD

**Issue by tspacepilot** [bitcoin-wallet/bitcoin-wallet#443]
Latest build in fdroid is 5.25 from July.  Looks like actual latest version is 5.32 from just a few days ago.

**Comment by schildbach** [comment]
Yes, that's a known issue. As far as I understand it, F-Droid currently cannot deal with newer sdk-tools versions. They need to build a new image.

**Comment by Dionis0s** [comment]
+1
Can you push this to the F-Droid maintainers?

I think to update this app is very important and critical for security reasons?

**Comment by ligi** [comment]
@Dionis0s you can also do this: https://forum.f-droid.org / https://f-droid.org/issues/

**Comment by schildbach** [comment]
The problem was solved, version 5.37 is now available on F-Droid too.
