### ISSUE TITLE
App not working.

### ISSUE THREAD

**Issue by Unityeid** [bitcoin-wallet/bitcoin-wallet#448]
Hello.

I have a big problem.

Two days ago, I have installed Bitcoin Wallet for the first time.
On the same evening i sent a bit of money to my wallet adress shown in the app.

they said it will take two days until my bitcoin will be shown on my wallet.

So today i recieved an e-mail with the confirmation, that my bitcoins have been transferred to my wallet.

When i tried to start the app there was only the message "App kann nicht geöffnet werden" (= App can not be opend).

I tried everything(restarted my phone etc.) but it still not worked.

So i had to reinstall the app.

BUT: The adress was not longer shown in the app and even the money was not there.

I have no backup because i only used the app once.

I hope you can tell me if there is anything what i can do now or if my money is away forever :(

Thank you!

Sincerly yours

**Comment by shkschneider** [comment]
By reinstalling the app you wiped your wallet, and since you did not backup the wallet you're SOL.
Not sure what happened before that. This application works great for me.

**Comment by schildbach** [comment]
@Unityeid This is no support forum. Use Options > Report issue in the app.
