### ISSUE TITLE
bitcoinj dump only gives public keys

### ISSUE THREAD

**Issue by hsachdevah** [bitcoin-wallet/bitcoin-wallet#449]
I followed your instructions of dumping private keys form recovery document by adding --dump-privkeys.
This is what I get

```
Keys:
Earliest creation time: 2017-03-04T17:46:11Z
Seed is encrypted
Seed birthday: <10 char num>  [2017-03-04T17:46:11Z]
Key to watch:  <111 char key>
  addr:<34 char addr>
  hash160:<40 char hash>  (M/0H/0/0)
  DeterministicKey{pub HEX=<66 char hex>, isEncrypted=true, isPubKeyOnly=true}
```
How can I get my private keys?

**Comment by schildbach** [comment]
Looks like your wallet is encrypted (spending PIN is set). Add `--password=<PIN>` to your command line, and also make sure you're using wallet-tool from the bitcoinj master branch, as this feature wasn't working properly on 0.14.

**Comment by hsachdevah** [comment]
Thanks @schildbach It worked
