### ISSUE TITLE
Acquire Bitcoin destination address, through QR-Code ?

### ISSUE THREAD

**Issue by Siltaar** [bitcoin-wallet/bitcoin-wallet#451]
What about being able to (micro) pay content we like (in a flattr manner) by scanning a QR-Code on the project or article we want to support ?

Easy, rapid, this is something new in the society that Bitcoin could allow.

The idea is to minimize the steps through this process…

**Comment by schildbach** [comment]
There are several companies who are doing this already, and in fact its one of the oldest ideas about Bitcoin services. Technically, look for "(micro)payment channels".

Anyway, it's out of scope for this app so I'll close this for now.
