### ISSUE TITLE
Android Backup

### ISSUE THREAD

**Issue by Harmitage** [bitcoin-wallet/bitcoin-wallet#452]
Good day!

It's more of a cry for help than an Issue. I have my .bak file, created by android, and I don't have backup file created by program itself, since I've never made it.

So, in .bak file I can see key-backup-protobuf section, but I have no idea how to extract it correctly, since it should be 4k and mine is 12k, and I have no idea what "password" to pass to openssl in case of decyphering it.

Can anybody share any ideas about what can be done to restore wallet using this information?

**Comment by schildbach** [comment]
About the Android backup file format it's probably best to ask on some Android support forum. For questions about the Bitcoin Wallet app please go to https://plus.google.com/b/101256420499771441772/communities/105515929887248493912

The backup file can have any size, mainly depending on how many payments your wallet has.
