### ISSUE TITLE
Add check to make sure BTC chain is followed

### ISSUE THREAD

**Issue by ndrchvzz** [bitcoin-wallet/bitcoin-wallet#454]
Code should be added to download block 494784 and check that its blocksize is valid.  
It should be a fairly straightforward change, will only require 1M to be downloaded, and will make sure that users stay on the BTC chain, rather than being hijacked to the B2X chain.  
Separate wallets could be developed that follow the B2X chain, and clearly inform the users about it.

**Comment by schildbach** [comment]
We could probably add such code, but it would work a little bit different. This app (Bitcoin Wallet) will continue to stay on the chain with most accumulated work, and a second app could be made for those who wish to stay on the minority chain. If someone wants to work on this, [bitcoinj](https://github.com/bitcoinj/bitcoinj) is where such logic needs to go first.
