### ISSUE TITLE
permission denied for decrypting wallet

### ISSUE THREAD

**Issue by stoner87** [bitcoin-wallet/bitcoin-wallet#455]
I have followed the steps in this guide https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md but i get the error line bash: bitcoin-wallet-decrypted-backup: permission denied. I dont get asked for a password and i dont have a pin on my wallet for the spending either. Any advice please.

**Comment by schildbach** [comment]
Sounds like a filesystem permission problem. But anyway, this is not a support forum. Please post to https://plus.google.com/communities/105515929887248493912.
