### ISSUE TITLE
Extract Bitcoin cash and gold from android wallet

### ISSUE THREAD

**Issue by Gun78** [bitcoin-wallet/bitcoin-wallet#462]
Hi

Is there an easy way of extracting Bitcoin Cash and Gold from the Android Bitcoin wallet?

Will there be support for this in future versions?

BR

**Comment by HashEngineering** [comment]
This app, which is maintained by me under a separate project, can be used to extract Bitcoin Cash:
https://play.google.com/store/apps/details?id=com.hashengineering.bitcoincash.wallet

I have no plans to make apps for other Bitcoin Forks.
