### ISSUE TITLE
Please made it possible to add an at moment empty qr-code 

### ISSUE THREAD

**Issue by Mannshoch** [bitcoin-wallet/bitcoin-wallet#467]
If I get a paper wallet from a Bitcoin ATM i have to wait until the bitcoin is loaded and im able to empty it.
Please add a delay option which store the Qrcode until the app is able to empty it.

**Comment by schildbach** [comment]
We strongly advise against using ATMs that print you a paper wallet. It's inherently insecure.

Rather, use an ATM that scans your QR code and sends Bitcoins directly into your wallet. E.g. one of the [Lamassu](https://www.youtube.com/watch?v=it3h4sjj45o)'s.

**Comment by Mannshoch** [comment]
This ATM prints a paper Wallet which I have to scan, so it could be loaded. If I try to scan my own QR-Code the ATM say I have to use this printout.
In Zürich I only know the ATM from bitcoinsuisse.
