### ISSUE TITLE
[Feature] Add BIP32 Mnemotic code

### ISSUE THREAD

**Issue by alsternerd** [bitcoin-wallet/bitcoin-wallet#468]
Hi,

it whould be very nice to have this to import and export wallets from and to this app, as I want to change from another app, but don't want to change the adresses everywhere again and again. :)

**Comment by schildbach** [comment]
This has been discussed a couple of times. The problem is mnemonics are not compatible between apps. It's much safer and more convenient to simply send your Bitcoins over.

Mnemonics are planned to be used as a form of backup though.
