### ISSUE TITLE
lost money

### ISSUE THREAD

**Issue by ekudritski** [bitcoin-wallet/bitcoin-wallet#470]
I lost all my paper money.
I tried to import paper wallet into my phone. Instead, it made a transaction. (visible in the link.)
And when I checked the wallet later it showed 0 transactions.
Why sweeping toes the transaction at all, it seems pointless waist?
Is there any data export or anything to try to recover it?

https://blockchain.info/address/136As8cYSVxXoTwpUiaLHsd1Fxss2FCrHK

**Comment by schildbach** [comment]
Use Options > Report issue.
