### ISSUE TITLE
Bitcoin Recovery

### ISSUE THREAD

**Issue by RafTim** [bitcoin-wallet/bitcoin-wallet#471]
Hi, 
I found out, that I have half a bitcoin left on my old Galaxy Nexus. After an update to the latest version I cannot open the app. It crashes from the start. Lucky me I have root and found a file named 
"key-backup-base58" which seems to contain my Bitcoin private key. So I extracted it, but I cannot figure out, how to import it on another phone, where the app works. It always tells me, that it did not find a file in /Download (which is /sdcard/Download/ i guess). I put it there, but still no success. 
How can I get my wallet back?

**Comment by schildbach** [comment]
This is no support forum. Use Options > Report issue or post into the G+ community.

**Comment by billyblaze5566** [comment]
Try a different phone or send it through a download though a different email?

**Comment by btc2dogecom** [comment]
> Hi,
> I found out, that I have half a bitcoin left on my old Galaxy Nexus. After an update to the latest version I cannot open the app. It crashes from the start. Lucky me I have root and found a file named
> "key-backup-base58" which seems to contain my Bitcoin private key. So I extracted it, but I cannot figure out, how to import it on another phone, where the app works. It always tells me, that it did not find a file in /Download (which is /sdcard/Download/ i guess). I put it there, but still no success.
> How can I get my wallet back?

do you get that back? we may help you if you have the backup
www.btc2doge.com
