### ISSUE TITLE
Allow to spend unconfirmed change 

### ISSUE THREAD

**Issue by jimukgb** [bitcoin-wallet/bitcoin-wallet#475]
Now that 3rd-party transaction malleability has been fixed with the November 13th hard-fork, can we allow to spend unconfirmed change (the reference client has the option to do so).

**Comment by schildbach** [comment]
You can spend unconfirmed change since years. The only requirement is that you've received at least network confirmations for the unconfirmed transaction (as can be seen by the grey dot getting larger and larger).
