### ISSUE TITLE
Warning: if compiled with SDK 25 or 26

### ISSUE THREAD

**Issue by alsternerd** [bitcoin-wallet/bitcoin-wallet#476]
It could crash some systems included the ability to remove/unistall the app without root and adb-acccess:

Please read carefully through these linked apps, where it did happen, too.

https://github.com/andOTP/andOTP/issues/76

The issue of crashing the launcher and Settings -> Apps-Menue is solved by using the Adndroid SDK 27 r1 or higher. The issue only occurs with SDK versions 25 and 26 and Android 6.x and the F-droid-Versions, I don't know if any other systems are affected.

Please make sure you have an app that doesn't crash.

I may be a bit extra paranoid since this happened with two other apps now, while the second one did crash the launcher, too. I just want to make sure it's compiled in a way that it won't crash anything again, that's why I'm opening this issue here.

Thank you. :)

**Comment by schildbach** [comment]
What is actually the problem? Can you provide at least a meaningful issue title?

**Comment by alsternerd** [comment]
Read the linked Issue, it's the same issue.

A more meaningful title could be "Don't compile with SDK 25 or 26 it will break devices". Leading to crashes of just the installing/deinstalling of the app as well as crashes while trying to open it.

I've had this issue two times and don't want to take chances anymore.

Am 5. Dezember 2017 16:00:31 MEZ schrieb Andreas Schildbach <notifications@github.com>:
>What is actually the problem? Can you provide at least a meaningful
>issue title?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bitcoin-wallet/bitcoin-wallet/issues/476#issuecomment-349329768

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by schildbach** [comment]
I have built using build-tools 25/26 many times on multiple apps, never has a device been broken. Is there a ticket somewhere in the [Android Issue Tracker](https://source.android.com/setup/report-bugs)?

**Comment by isal29** [comment]
Envoyé de mon iPhone

Le 5 déc. 2560 ère b. à 10:00, Andreas Schildbach <notifications@github.com<mailto:notifications@github.com>> a écrit :


What is actually the problem? Can you provide at least a meaningful issue title?

**Comment by schildbach** [comment]
Seems like no one can reproduce this error.

What exactly do you mean by "use SDK xx"? Do you mean the Android version that *you* are using when running this app? Or are you talking about targetSdkVersion or compileSdkVersion?

**Comment by isal29** [comment]
https://github.com/bitcoin-[image1.png]/bitcoin-wallet/issues/476


Envoyé de mon iPhone

**Comment by isal29** [comment]
Envoyé de mon iPhone

**Comment by isal29** [comment]
Envoyé de mon iPhone

**Comment by isal29** [comment]
https://wallet.bitcoin.com


Envoyé de mon iPhone

**Comment by isal29** [comment]
Envoyé de mon iPhonesupport@bigonbets.co.uk

**Comment by isal29** [comment]
bitcoincash:1J8xfR6sfsz7UhsGAreC9m2ZEwf1Jdr4WG


Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

**Comment by isal29** [comment]
bitcoin:18vxk6Giy5MeoRFRfimGaKyev3b4mJUacQ


Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

**Comment by schildbach** [comment]
I'm closing this as this doesn't seem to be an issue on AOSP.
