### ISSUE TITLE
Split bitcoin cash

### ISSUE THREAD

**Issue by degaray** [bitcoin-wallet/bitcoin-wallet#481]
It would be nice to have an option to split your bitcoin to bitcoin cash inside the wallet.

**Comment by kenspratt** [comment]
I agree. Another option would be to allow the export of the equivalent number of bitcoin cash to another bch wallet.

**Comment by sjalgeo** [comment]
Yes please

**Comment by schildbach** [comment]
Sorry, this won't happen. Use a Bitcoin Cash wallet if you want to access your BCH.

**Comment by sjalgeo** [comment]
@schildbach is there any info on how to do that from a Wallet Backup?

**Comment by HashEngineering** [comment]
@sjalgeo - Check this post in the community -  https://plus.google.com/+BitcoinWalletApp/posts/6aVdM95Wkd6?hl=en

**Comment by sjalgeo** [comment]
@HashEngineering thanks, perfect.

**Comment by azmia** [comment]
Pada 12 Dis 2017 10:50 PM, "degaray" <notifications@github.com> menulis:
