### ISSUE TITLE
sync command: Error reading block chain file mainnet.chain: java.io.IOException: Invalid argument

### ISSUE THREAD

**Issue by Dunnzilla** [bitcoin-wallet/bitcoin-wallet#484]
Hello,

I am restoring my wallet from a Bitcoin Wallet (Android) backup.  Following these instructions:

https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md

I have performed the openssl command to decrypt it, and verified that this is a Protobuf wallet format.  ( `cat bitcoin-wallet-decrypted-backup | tr -cd "[:print:]" | awk '{print $1}'` resulted in "org.bitcoin.production" ).

I then take the decrypted.dat file and copy it into `bitcoinj/tools`.

If we skip most of the build noise of making wallet tool, the final few pages of output from build are:

> [INFO] --- maven-shade-plugin:2.3:shade (default) @ wallettemplate ---
> [INFO] Including org.bitcoinj:bitcoinj-core:jar:0.14.5 in the shaded jar.
> [INFO] Including com.madgag.spongycastle:core:jar:1.51.0.0 in the shaded jar.
> [INFO] Including com.google.protobuf:protobuf-java:jar:2.6.1 in the shaded jar.
> [INFO] Including com.google.code.findbugs:jsr305:jar:2.0.1 in the shaded jar.
> [INFO] Including net.jcip:jcip-annotations:jar:1.0 in the shaded jar.
> [INFO] Including com.lambdaworks:scrypt:jar:1.4.0 in the shaded jar.
> [INFO] Including org.bitcoinj:orchid:jar:1.2.1 in the shaded jar.
> [INFO] Including com.squareup.okhttp:okhttp:jar:2.7.2 in the shaded jar.
> [INFO] Including com.squareup.okio:okio:jar:1.6.0 in the shaded jar.
> [INFO] Including com.google.guava:guava:jar:18.0 in the shaded jar.
> [INFO] Including org.fxmisc.easybind:easybind:jar:1.0.2 in the shaded jar.
> [INFO] Including de.jensd:fontawesomefx:jar:8.0.0 in the shaded jar.
> [INFO] Including net.glxn:qrgen:jar:1.3 in the shaded jar.
> [INFO] Including com.google.zxing:javase:jar:2.0 in the shaded jar.
> [INFO] Including com.google.zxing:core:jar:2.0 in the shaded jar.
> [INFO] Including org.slf4j:slf4j-api:jar:1.7.20 in the shaded jar.
> [INFO] Including org.slf4j:slf4j-jdk14:jar:1.7.20 in the shaded jar.
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] bitcoinj Parent .................................... SUCCESS [  0.251 s]
> [INFO] bitcoinj ........................................... SUCCESS [01:03 min]
> [INFO] bitcoinj Examples .................................. SUCCESS [  0.673 s]
> [INFO] bitcoinj Tools ..................................... SUCCESS [  8.141 s]
> [INFO] bitcoinj Wallet-Template ........................... SUCCESS [  1.555 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:15 min
> [INFO] Finished at: 2017-12-13T03:37:27+00:00
> [INFO] Final Memory: 38M/110M
> [INFO] ------------------------------------------------------------------------

`./wallet-tool` will give me the help text as expected.

`ubuntu@ubuntu-xenial:/x/bitcoinj/tools$ ./wallet-tool reset --wallet=decrypted.dat`

This succeeds with return code 0 and no output.

`ubuntu@ubuntu-xenial:/x/bitcoinj/tools$ ./wallet-tool sync --wallet=decrypted.dat --debuglog`

This however, results in the IO Exception:

> ubuntu@ubuntu-xenial:/x/bitcoinj/tools$ ./wallet-tool sync --wallet=decrypted.dat --debuglog
> 03:40:21 1 WalletTool.main: Starting up ...
> 03:40:21 1 Context.<init>: Creating bitcoinj 0.14.5 context.
> Error reading block chain file mainnet.chain: java.io.IOException: Invalid argument
> org.bitcoinj.store.BlockStoreException: java.io.IOException: Invalid argument
> 	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:131)
> 	at org.bitcoinj.tools.WalletTool.setup(WalletTool.java:1184)
> 	at org.bitcoinj.tools.WalletTool.syncChain(WalletTool.java:1236)
> 	at org.bitcoinj.tools.WalletTool.main(WalletTool.java:358)
> Caused by: java.io.IOException: Invalid argument
> 	at sun.nio.ch.FileChannelImpl.map0(Native Method)
> 	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:926)
> 	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:113)
> 	... 3 more

mainnet.chain is only 641024 bytes, of md5sum 6c85e7f6ba862f1102a7bdc7a6122e05.

Happy to provide other information as needed.  Maybe I don't need to use the sync command to get my private keys?  However, the `dump` command also bails:

> ubuntu@ubuntu-xenial:/x/bitcoinj/tools$ ./wallet-tool dump --wallet=decrypted.dat --dump-privkeys
> Exception in thread "main" org.bitcoinj.store.BlockStoreException: java.io.IOException: Invalid argument
> 	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:131)
> 	at org.bitcoinj.tools.WalletTool.setup(WalletTool.java:1184)
> 	at org.bitcoinj.tools.WalletTool.dumpWallet(WalletTool.java:1460)
> 	at org.bitcoinj.tools.WalletTool.main(WalletTool.java:352)
> Caused by: java.io.IOException: Invalid argument
> 	at sun.nio.ch.FileChannelImpl.map0(Native Method)
> 	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:926)
> 	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:113)
> 	... 3 more

**Comment by schildbach** [comment]
What Java version do you have? Please post the output of `java -version`.

**Comment by Dunnzilla** [comment]
Thanks!

```
$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
(release-0.14)

$ uname -a
Linux ubuntu-xenial 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by schildbach** [comment]
Strange, that's an issue with mmapping. Is there anything special about your filesystem? Is it a standard ext4, is it encrypted?

Also, maybe try to delete `mainnet.chain` and have it created again by wallet-tool.

**Comment by Dunnzilla** [comment]
Standard ext4, nothing fancy.  I erased the mainnet.chain and the same problem happens.  Also tried rebuilding the package just in case, same thing.

Should I look at SPVBlockStore.java ?

**Comment by schildbach** [comment]
Really weird. You could try switchung bitcoinj to the master branch, clean build the project and try again.

Also, perhaps switching to the current HWE kernel (4.10.0-42, package: linux-signed-generic-hwe-16.04) helps?

**Comment by Dunnzilla** [comment]
I was totally wrong.  There _was_ something special: I was running off an NFS mount.  When I ran this from my ext4 mount everything worked.  (master branch fwiw)  Thanks again.
