### ISSUE TITLE
Error in backup / recovery?

### ISSUE THREAD

**Issue by ScreamingHawk** [bitcoin-wallet/bitcoin-wallet#494]
I've followed the steps from `wallet/README.recover.md` but when I get to:

> `./wallet-tool dump --wallet=/tmp/bitcoin-wallet-decrypted-backup --dump-privkeys`
> 
> Look for `priv WIF=<...>`, where `<...>` will be your private keys in wallet import format. 

I'm unable to see `WIF` in the output. 

I can see `priv EXCEPTION=org.bitcoinj.core.ECKey$MissingPrivateKeyException` which leads me to believe something has gone wrong somewhere, but I'm not familiar enough to figure it out. Any help would be appreciated.

**Comment by schildbach** [comment]
This only works on the master branch of bitcoinj. On 0.14-release you need to add another decrypt step. We updated the README a few weeks ago, have you maybe followed an old version?

**Comment by ScreamingHawk** [comment]
I forgot I had a spending PIN. 

Would be nice if the README covered this error as it's not intuitive, 

Would also be nice if users didn't make errors and bug the developers with useless tickets :P

Thanks a lot of this project! It's a life saver.
