### ISSUE TITLE
The fiat value in the widget is not updated

### ISSUE THREAD

**Issue by orium** [bitcoin-wallet/bitcoin-wallet#495]
Hi,

the fiat value of the wallet displayed by the widget does not seem to get updates unless you open the app.

**Comment by schildbach** [comment]
The widget never chances while the respective screen (send or receive) is open/visible. If you go back and reopen the screen, the prices should be fetched again. However, the app also caches the prices for a while to minimize requests on the provider for prices (BitcoinAverage).
