### ISSUE TITLE
add custom fee option in sat/byte

### ISSUE THREAD

**Issue by jonjonez** [bitcoin-wallet/bitcoin-wallet#500]
Many wallets even when the mempool is not full calculate the expensive rate to confirm faster but I know that if I pay a cheaper fee I know how long it can take to confirm on the network through network fee comparator bitcoin that shows all the fees from 0 sat/byte to 1000 sat/byte and the maximum confirmation time, I know the risk of putting a fee low too, my transaction will be stuck in mempool for an indeterminate time, but I also know that some algorithms of wallets calculate the fee out of the ordinary, most more expensive than the network asks that is the case of this wallet, add a warning when the user clicks on custoo fee saying that if he places a fee too low than the network asks, your transaction can be stuck indefinitely, that alone is enough, upon reading this warning the risk is the user.

**Comment by pr3ddi** [comment]
please see also issue #502

**Comment by schildbach** [comment]
Sorry. Your sentence is impossible to read.
