### ISSUE TITLE
Private Key

### ISSUE THREAD

**Issue by Yacine-krk** [bitcoin-wallet/bitcoin-wallet#501]
Hello there,
Sorry for creating an issue for this :/
I want to know how can I get my private key if you want to store them in another wallet for instance.
Moreover, with all the Bitcoin forks happening out there, how can I claim the forked coins ?

I know this is may be not the right place to ask those questions. I'll be happy to go on some sort of support forum :)

Thanks for your help

**Comment by jonjonez** [comment]
see: https://bitcointalk.org/index.php?topic=1997031.0

**Comment by Yacine-krk** [comment]
Thnaks, i'll have a look at it.
But it seems not accessible for noobs. Wouldn't it be great to add this feature to the app ?

**Comment by saremes** [comment]
I have your problems too

**Comment by dr2okevin** [comment]
A simple show or export (and maybe import) private key function would be great.

**Comment by Yacine-krk** [comment]
Yep totally agree to that. That would be great

**Comment by sheehyjohn** [comment]
Agreed, that would save me some time

**Comment by schildbach** [comment]
There is an export, it's Options > Safety > Backup wallet. The keys are written in bitcoinj wallet format (Protobuf).
