### ISSUE TITLE
Improve network fee handling

### ISSUE THREAD

**Issue by pr3ddi** [bitcoin-wallet/bitcoin-wallet#502]
please improve the network fee handling and changing/raising (also issue #500)

problem: using version 5.43 i have sent 50 € and chosen the lowest rate which is running since 2 days without confirmaton. the raise network fee option suggest to add another 50 € which is way to high.

ideas ...
a) add more network fee options, low / low-med / med / med-high / high (at least 5)
   or
b) implement a slider that lets user select the max time he is willing to wait by estimating the size and using bitcoinfees.earn.com to estimate the times. the slider should have at least 5 steps 1h / 2h / 6h / 12h / 24h
   or
c) let advanced users configure the values for low / med / high priority
   and
d) change the raise network fee option to really raise the fee by a selectable amount or rename it
   or
e) your idea

best regards

pr3ddi

**Comment by schildbach** [comment]
a) The existing options tied to use-cases. E.g. the fee rate you have used ("economic") is for payments where you don't care about confirmation times. What additional usecases would low-med and med-high cover?

b) It's impossible to predict the waiting time so accurately; fees are way too volatile for that. It has already become almost impossible to say anything about the projected confirmation time of the "normal" fee level.

c) Keep in mind the app targets novice users.

d) The idea is that if you raise the fee in virtually all cases you've changed your mind and want to confirm your payment as soon as possible. That means you have to pay priority fee anyway, which is how it's currently implemented. I'm not sure if a 'raise to normal fee' option would make any sense.

I have considered to implement a slider between the current economic and priority fee levels, but honestly I don't think it would have any use – it would only provide a fake sense of "being in control".

At some point the Bitcoin community will agree on finally scaling Bitcoin, which will lower the fees to a sane (and predictable) level again.

**Comment by mrgreywater** [comment]
I agree that some more information on the Fee would be nice though.
- Transaction Fee in the selected currency e.g. USD and maybe even Satoshis/B
- Display the estimated time of the transaction with the chosen fee. Could be taken from this API: https://bitcoinfees.earn.com/api .
