### ISSUE TITLE
Unable to pay BitPay invoices

### ISSUE THREAD

**Issue by DivineOmega** [bitcoin-wallet/bitcoin-wallet#503]
I've been unable to pay any BitPay invoices with Bitcoin Wallet recently. After scanning the QR code, I am receiving an error stating:

```
FETCHING SIGNATURE FAILED

Wrong signature!

address, amount
```

with a `Dismiss` button.

Screenshot: https://photos.app.goo.gl/3maq9krFalGKWyBm2

Could this be related to BitPay's recent switch to payment protocol only for their invoices?

**Comment by schildbach** [comment]
Looksl like BitPay has a rounding error in its BIP21 formatter again. Can you attach your logfile (or just the relevant fragment) and state the exact time/date of the error?

**Comment by DivineOmega** [comment]
Just tested again and grabbed the log. This appears to be the relevant fragment:

```
22:13:05 [backgroundThread] RequestPaymentRequestTask - trying to request payment request from https://bitpay.com/i/N5qEfgL2WFNoA9j9VxaTyZ
22:13:05 [main] BlockchainServiceImpl - service start command: Intent { cmp=de.schildbach.wallet/.service.BlockchainServiceImpl }
22:13:06 [AsyncTask #12] DynamicFeeLoader - Dynamic fees not modified at https://wallet.schildbach.de/fees, took 342.8 ms
22:13:07 [backgroundThread] RequestPaymentRequestTask - received PaymentIntent[BIP70,BitPay, Inc., Atlanta, US/The Go Daddy Group, Inc., US,[Output[0.024993,14AMAFCqmQxkUoDRP7P1mvwQEefWGnWZLm]],https://bitpay.com/i/N5qEfgL2WFNoA9j9VxaTyZ,payeeData=7b22696e766f6963654964223a224e35714566674c3257464e6f41396a3956786154795a222c226d65726368616e744964223a224169666d414a346156766f5a7737754366434e463462227d,paymentRequestHash=f7fac8cdab3c35b644ece97ae192fcc14e8b8c95c89d1bee39f2ddf4f2f0c187] via http
22:13:07 [main] SendCoinsFragment - BIP72 trust check failed: address, amount
```

The full log has been sent via email.

**Comment by sevan6** [comment]
Same issue. Never used a bitpay link before but I just stumbled upon the exact same behavior (wrong signature). 
It was a temporary wallet. 

I use Fdroid 5.39 version

**Comment by schildbach** [comment]
Ok, I just looked into it. BitPay does not transmit the BIP21 amount and address any more. That means Bitcoin Wallet cannot validate the authenticity of the BIP70 payment request any more. Hence the error message. Can you open a ticket with BitPay?

**Comment by DivineOmega** [comment]
Thanks for looking into it. I have opened a ticket with BitPay as suggested, stating the following.

> Hello,
> 
> I have recently been attempted to use the Bitcoin Wallet for Android, and have found I am unable to pay any BitPay invoices. I have contacted the developer of the wallet and he has stated the following.
> 
> "BitPay does not transmit the BIP21 amount and address any more. That means Bitcoin Wallet cannot validate the authenticity of the BIP70 payment request any more."
> 
> Please see this GitHub issue that I reported: https://github.com/bitcoin-wallet/bitcoin-wallet/issues/503
> 
> Is this something you are able to look into?
> 
> Many thanks,
> 
> Jordan Hall

Their automated system responded with the following.

> Due to record-breaking interest in bitcoin, we are currently working through a ~1000 inquiry backlog. While we aim to reply within 1 business day, please allow up to *3 business days* for response. 

So, hopefully we'll see a response regarding this in the next few days.

I'm quite surprised this wasn't picked up earlier. Surely it affects quite a large number of their customers.

**Comment by DivineOmega** [comment]
@schildbach I've yet to receive a response from BitPay regarding this, but I've done some more research. 

After taking a look at BitPay's recent blog posts, it seems the removal of the BIP21 amount and Bitcoin address was a recent deliberate move to mitigate payment mistakes. BitPay invoices now only support the payment protocol addresses with '?r='.
 
Relevant blog post: https://blog.bitpay.com/payment-protocol/

Are there any plans for Bitcoin Wallet to accept this version of the payment protocol?

**Comment by DivineOmega** [comment]
Further info about currently compatible wallets is in this post: https://support.bitpay.com/hc/en-us/articles/115005701523

**Comment by schildbach** [comment]
I don't think their change is necessary for separating between BTC and BCH. They write that BCH gets their own URI namespace ("bitcoincash:"). Also, BCH will get their own address format.

Bitcoin Wallet either expects the address/amount pair, or an "h" parameter in order to extend the QR code (or NFC) trust anchor to the payment request message. See https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.specs.md

**Comment by DivineOmega** [comment]
@schildbach Thanks for the link. Let me make sure I understand correctly. 

So Bitcoin Wallet partially implements BIP-72, such that payment protocol requests without the Bitcoin address & amount or hash in the Bitcoin URI (such as those now provided by BitPay) will fail. Is this correct?

If so, would I be right in assuming this is due to the possibility of the request to the 'r=' URL being man-in-the-middled?

**Comment by schildbach** [comment]
Yes, exactly. BIP70 is fully implemented, but I never agreed to BIP72 because of this flaw in the spec. Finally I implemented BIP72 but with this small twist.

Actually there is a third alternative. If BitPay really wants to go payment protocol only, they could put the payment request message directly into the QR code (without any "r=" indirection). It isn't standardized yet, but Bitcoin Wallet supports this.
