### ISSUE TITLE
Sending to Bech32 addresses (BIP 173)

### ISSUE THREAD

**Issue by DivineOmega** [bitcoin-wallet/bitcoin-wallet#508]
Currently Bitcoin Wallet is unable to send to Bech32 format addresses with the send screen failing validation and stating 'Invalid Bitcoin address'. 

Would it be possible to enable sending to Bech32 format addresses within Bitcoin Wallet?

**Comment by schildbach** [comment]
SegWit support is still in the works. Also, for now we're targetting the P2SH address format, Bech32 will come later. I'm closing this as this is mostly in the domain of bitcoinj.

**Comment by jonjonez** [comment]
@schildbach will the segwit P2SH addresses be available in the next version?

**Comment by schildbach** [comment]
@jonjonez It's ready when it's ready. Currently we seem to lack developers who are really interested in  and committed to segwit.
