### ISSUE TITLE
Having trouble decrypting the backup file

### ISSUE THREAD

**Issue by emkaynox** [bitcoin-wallet/bitcoin-wallet#509]
Hi,
I have been trying to follow this [guide](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md) to decrypt my Bitcoin Wallet's backup file.

I have installed the Ubuntu app for Windows 10, but when I try the decrypt command:
openssl enc -d -aes-256-cbc -a -in my_encrypted_wallet > my_decrypted_wallet

I get a "No such file or directory" error.

Can anybody help? 

Thanks.

**Comment by tompreston** [comment]
That means openssl can't find `my_encrypted_wallet`. Are you in the right directory?
