### ISSUE TITLE
Claiming your BCH

### ISSUE THREAD

**Issue by idontgnu** [bitcoin-wallet/bitcoin-wallet#510]
Since nobody here tells you where to go or what to do, instead they close the issue without any guidance at all. I know this isn't a discussing board, but there is NO referencing a discussion board for people who are new here.

I'm here to guide the lost souls on how to claim those BCH.

Go to your Bitcoin Wallet and set a backup.
Next, download the Bitcoin Cash Wallet here: https://play.google.com/store/apps/details?id=com.hashengineering.bitcoincash.wallet
Then finally, restore the wallet you previously backed up and wait for it to sync up. 
That's it. You should see your BCH in your wallet.

**Comment by schildbach** [comment]
The G+ community and stack exchange is mentioned in the [contributing guidelines](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/.github/CONTRIBUTING.md).
