### ISSUE TITLE
blockexplorer.com no is deprecating bitcoin "legacy"

### ISSUE THREAD

**Issue by tompreston** [bitcoin-wallet/bitcoin-wallet#511]
https://blockexplorer.com/ is deprecating bitcoin legacy and switching support to bitcoin cash.

Maybe remove it as the default block explorer?

Announcement in full:
> In August 2017, Bitcoin forked into two variants. These have taken radically different paths.
>
> Looking at the situation one quarter later, it is clear to us that the Blockstream fork of bitcoin diverges so radically from the ideas presented in the Bitcoin white paper, that it is an evolutionary dead end. While it may still have high trading value, as a mere collectible of curiosity, the Blockstream fork of bitcoin is not part of building any future financial infrastructure, which is what Block Explorer is about.
>
> A currency of the future has subcent optional usage fees and instant transactions. The Blockstream fork of Bitcoin ("Bitcoin Legacy") is at $20 usage fees and rising, with no end in sight, and can take days to confirm, despite unfulfilled promises to the contrary on both points when Segwit activated in what can only be described as a community fistfight. We are therefore making the decision to consider the Blockstream fork deprecated, and support it as legacy technology only.
>
> Rather, we have made the decision to support the only bitcoin fork with a postive utility momentum, which is Bitcoin Cash. We took an early decision to deploy a Bitcoin Cash block explorer and will continue to roll out related services. We are also deploying tools for other cryptocurrencies we find on a positive momentum path, such as ZCash, which have increased privacy value.
>
> We will not add future support for the Blockstream fork of bitcoin ("Bitcoin Legacy"), and will be deprecating it entirely at some future point in time to be determined. Developments have revealed it to be a dead end. At such a time, we will refer to Bitcoin Cash as Bitcoin only, but will make some effort to not break API calls by changing URLs of legacy automated systems.
```

**Comment by schildbach** [comment]
Thanks for the notice! I already implemented this via 6a34b0212b0f2a99bcf8121a451b3fa7a081cfef.
