### ISSUE TITLE
Support for export backup

### ISSUE THREAD

**Issue by hnairda** [bitcoin-wallet/bitcoin-wallet#512]
I'm looking for some support on how to access private keys in bitcoin wallet 5.43 to sweep bitcoin cash and gold into other separate wallets. Where should I seek this sort of support for this app? I should mention that my wallet had it's coins sent to it way back in 2015 so pre forks,

**Comment by schildbach** [comment]
For support, please post to the G+ community or to the stack exchange.

**Comment by hnairda** [comment]
google+?

I don't have google +

**Comment by azmia** [comment]
URL: shapeshift.io/btcfee

Method: GET

Success Output:

{

  recommendedFeeInSatoshi_btc: '48601',

  memPoolStat_btc: { count: 5455, size: 4702909.5 },

  lastBlockStat_btc: { 'time-utc': '2016-12-06T20:17:35Z', size: '998168' },

  lastUpdatedStat_btc: 'Tuesday Dec 6th 16, 13:23 GMT'

}

**Comment by azmia** [comment]
URL: shapeshift.io/btcfee

Method: GET

Success Output:10000 

{

  recommendedFeeInSatoshi_btc: '48601',

  memPoolStat_btc: { count: 5455, size: 4702909.5 },

  lastBlockStat_btc: { 'time-utc': '2016-12-06T20:17:35Z', size: '998168' },

  lastUpdatedStat_btc: 'Tuesday Dec 6th 16, 13:23 GMT'

}
