### ISSUE TITLE
java.lang.NoClassDefFoundError: com/android/build/gradle/internal/NdkHandler

### ISSUE THREAD

**Issue by liuxgchi** [bitcoin-wallet/bitcoin-wallet#514]
I want to build and execute the pro,and a problem occurs,the log blow is 
Error:(1, 1) A problem occurred evaluating project ':native-scrypt'.
> java.lang.NoClassDefFoundError: com/android/build/gradle/internal/NdkHandler

I wonder why ? Please help me thanks a lot!

**Comment by schildbach** [comment]
Are you using the exact tools and versions as described in https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.md?

**Comment by Rockung** [comment]
I have built the scrypt successfully by following these steps

1. set ANDROID_HOME, ANDROID_NDK_HOME correctly
2. The c header files are in ANDROID_NDK_HOME/sysroot/usr/include, but have some trouble
    ln -s asm-generic/ asm
3. add '#include' flag in build.gradle in scrypt
   ndk {
      CFlags.add('-I/ANDROID_NDK_HOME/sysroot/usr/include')
   }
   I don't know how to get ANDROID_NDK_HOME in gradle script, just replace it with the real path.
4. run the command
    gradle clean :native-scrypt:copy test build

**Comment by schildbach** [comment]
@Rockung What version of the NDK do you have installed?

**Comment by Rockung** [comment]
@schildbach I use NDK 16.1.4479499 that I got from Android Studio 3.0.1 on Ubuntu 16.04.

**Comment by schildbach** [comment]
Currently, it needs r15c (separate download linked in the README). I plan to adapt to newer NDKs soon.

**Comment by schildbach** [comment]
Fixed by #532.
