### ISSUE TITLE
Backups are corrupting (says bad password when password is correct)

### ISSUE THREAD

**Issue by beefsoda** [bitcoin-wallet/bitcoin-wallet#517]
Android app version 5.45

I am attempting to backup my wallet on a Nexus 6p (android 8.1) - I have attempted backups three times. I am restoring onto a Pixel 2 XL (android 8.1).

Every time I attempt to restore the wallet I get the following message:

---

Wallet could not be restored:

Read more than the limit of 10000000 characters

Bad password?

---

No, this is not a bad password. I have made three different backups, double checking the password and using simple passwords such as "a" or "1234". I am 100% certain that the passwords are fine. I can only conclude that there is a bug with either the backup or restore.

In addition, I am able to decrypt successfully using openssl, proving the password is corrrect.

**Comment by schildbach** [comment]
Indeed this is not caused by a bad password. Your backup file is too large. The resulting wallet would stall the app and make it unusable. This is why we implemented a limit for now.

Please use the [recovery instructions](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md) to empty your wallet into a fresh one and then don't use that fresh wallet for receiving mining pool payouts etc.

**Comment by btc2dogecom** [comment]
> Android app version 5.45
> 
> I am attempting to backup my wallet on a Nexus 6p (android 8.1) - I have attempted backups three times. I am restoring onto a Pixel 2 XL (android 8.1).
> 
> Every time I attempt to restore the wallet I get the following message:
> 
> Wallet could not be restored:
> 
> Read more than the limit of 10000000 characters
> 
> Bad password?
> 
> No, this is not a bad password. I have made three different backups, double checking the password and using simple passwords such as "a" or "1234". I am 100% certain that the passwords are fine. I can only conclude that there is a bug with either the backup or restore.
> 
> In addition, I am able to decrypt successfully using openssl, proving the password is corrrect.

do you get that back? we may help you if you have the backup
www.btc2doge.com
