### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Robigus92** [bitcoin-wallet/bitcoin-wallet#518]
After a double rotation of the WalletActivity there are in heap memory 2 instances more of:

class de.schildbach.wallet.ui.WalletActivity @ 0x13149800
class de.schildbach.wallet.ui.WalletAddressFragment @ 0x13157c00

It should not be like this because the rotations return to the same GUI state and the memory should stay in the same state as well. It could be a symptom of a bad management of the onCreate-onDestroy lifecycle.

**Comment by Robigus92** [comment]
I have found another problem
---
After a double pop-up event (e.g. a dialog that covers partially the activity) of the NetworkMonitorActivity there are in heap memory 2 instances more of:

class de.schildbach.wallet.ui.BlockListAdapter$1 @ 0x12d844c0
class de.schildbach.wallet.ui.PeerListFragment$PeerViewHolder @ 0x12cf3b00
class de.schildbach.wallet.ui.BlockListAdapter$BlockViewHolder @ 0x12cf3c40

It should not be like this because the pop-up events return to the same GUI state and the memory should stay in the same state as well. It could be a symptom of a bad management of the onPause-onResume lifecycle. 

I have encountered this problem on an Android emulator running 7.1.1 os version.

**Comment by schildbach** [comment]
I wonder could you test this again on version 6.09+? A lot changed internally that could affect this memory leak.

**Comment by thawisakprasreod** [comment]
>#

**Comment by schildbach** [comment]
I assume this has been fixed, so I'm closing this. Feel free to reopen if you see this particular issue again with recent versions.
