### ISSUE TITLE
"You've still got Bitcoins on this device!"

### ISSUE THREAD

**Issue by betsythefc** [bitcoin-wallet/bitcoin-wallet#521]
I got a notification from the bitcoin wallet, but I accidentally cleared it. Looking at the notification history, the subject of my issue here is all I can see.

What's going on? It seems like I'm going to lose my bitcoins?

**Comment by schildbach** [comment]
Don't worry, it's just a reminder. Open the app to see how much you've got.

**Comment by JeffreyLeonard** [comment]
How do I open the app
