### ISSUE TITLE
Incorrect exchange rate

### ISSUE THREAD

**Issue by 4val0v** [bitcoin-wallet/bitcoin-wallet#522]
[BitcoinAverage](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/src/de/schildbach/wallet/data/ExchangeRatesProvider.java#L78) displays an incorrectly current course, maybe they cache data.

Please add the option of choosing a course with these sources:

- https://bitpay.com/api/rates ([doc](https://bitpay.com/api/#resource-Rates))
- https://api.coinbase.com/v2/exchange-rates?currency=BTC ([doc](https://developers.coinbase.com/api/v2#exchange-rates))
- https://www.cryptonator.com/api

**Comment by schildbach** [comment]
BitcoinAverage is already on the issue.

**Comment by 4val0v** [comment]
It would be nice to have a choice from which site to take a course

**Comment by schildbach** [comment]
It's fixed now.

As for other sources, unfortunately there is no standard format so it's a lot of work to maintain each source. If anyone wants to contribute, feel welcome!
