### ISSUE TITLE
Request to fix fees in version 5 branch

### ISSUE THREAD

**Issue by lnuser** [bitcoin-wallet/bitcoin-wallet#524]
Would it be possible to fix the fees in version 5 branch? Even when set to economic the fees that the wallets sets are about 20x normal fees. 

I cannot upgrade to version 6 because my phone (Jolla with SailfishOS) doesn't support anything above JellyBean

**Comment by JeffreyLeonard** [comment]
I really don't understand any of that what you just said

Jeffrey Leonard

**Comment by schildbach** [comment]
Can you be more specific about the fee rates?

**Comment by lnuser** [comment]
I just tested to create a transaction and Bitcoin Wallet and it wanted to set the fee to 0.0001 even when the fee setting was at economic. The amount to be sent was a small one so the coin selector wouldn't have any problem to find one unspent output for the transaction.

**Comment by schildbach** [comment]
Bitcoinj 0.14 has a minimum fee (absolute value), but it should be 0.01 mBTC (1000 sat). But usually that minimum doesn't kick in, even with economic fee.

The next version of bitcoinj (0.15, to be released) will get rid of the minimum fee. As soon as that version is released, Bitcoin Wallet will pick it up.

**Comment by lnuser** [comment]
Thanks, great to hear that version 5 is still maintained.

**Comment by JeffreyLeonard** [comment]
What happened to my coins

**Comment by schildbach** [comment]
Closing this, as version 5.x is not supported any more. If you're still using that version, we strongly suggest to update to 7.x.
