### ISSUE TITLE
Wallet could not be restored:  Could not decrypt bytes  Bad password?

### ISSUE THREAD

**Issue by procyon12lotor** [bitcoin-wallet/bitcoin-wallet#525]
Backed up my wallet to move from Lineage 14.1 to Lineage 15.1. Attempting to restore the backed up wallet, and I'm getting this fun error:

"Wallet could not be restored:

Could not decrypt bytes

Bad password?"

I'm definitely using the correct password. Any ideas?

**Comment by schildbach** [comment]
There is no known problem that could cause this. If you're sure about the correct password, can  you try to reproduce the issue by backing up and restoring again using the same password?

**Comment by procyon12lotor** [comment]
I backed up my now empty wallet and successfully restored it with the same password.

**Comment by schildbach** [comment]
Thanks for testing this. If you want to do more testing you could go back to the specific Lineage installation and try again.

Is the password just letters and numbers or does it also contain special characters or umlauts?

**Comment by procyon12lotor** [comment]
The password is 64 characters long with uppercase, lowercase, numerals and the following special characters: !},<?'+_#[).>;"^$&:

Is it possible to decrypt using desktop Linux?

**Comment by schildbach** [comment]
Oh wow, and you're sure you made no mistake?

Backup encryption is compatible to openssl. See this document: https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md

**Comment by ligi** [comment]
@procyon12lotor https://xkcd.com/936 *SCNR*

**Comment by procyon12lotor** [comment]
Yes, I use a password manager, so it's just a copy and paste.

I'll try messing around with openssl, and see if I can get anywhere. Thanks.

**Comment by schildbach** [comment]
Did you activate 'Show password' to verify that you had the right string on the clipboard?

Note: don't copy passwords to the clipboard. It's dangerous!

**Comment by procyon12lotor** [comment]
No password is ever for any reason in my clipboard. I said copy and paste as a shorthand, because it is irrelevant. I use very long, randomly generated passwords with special characters, and store them in a password manager. I use Keepass2Android with the soft keyboard to inject the passwords. Is everyone here satisfied with my password hygiene?

The password I am entering is correct, I promise. It was generated specifically for this backup, and is being entered correctly, the phone is not upside-down, and my shoes are on the correct feet.

My suspicion is that the backup was corrupted when it was moved off of my phone. I am mainly here in the event anyone knows a way to determine if that is the case, or if there are weird unwritten password length or forbidden special character rules.

**Comment by schildbach** [comment]
Your password is used exactly as it was entered, except for stripping leading and trailing whitespace (`String.trim()`). The encrypted data is put inside a Base64 armor. If that armor cannot be decoded due to file corruption, a different error message should be generated.

If you look at the logfile of the app (e.g. using `adb logcat`) you'll see a more specific exception about where exactly the decoding failed.

Did you try openssl?

**Comment by JeffreyLeonard** [comment]
I don't think I ever had time to get a wallet

Jeffrey Leonard

**Comment by JeffreyLeonard** [comment]
Jeffrey Leonard

**Comment by zvone2000** [comment]
I have the same problem. My phone was in repair (before that I made backup and saved it on the safe place and put phone back on factory reset). Now I installeed bitcoin wallet and it says (could not decrypt...). I saved password for it in my password manager so password is right one for sure.

**Comment by JeffreyLeonard** [comment]
How can I fix this

Jeffrey Leonard

**Comment by zvone2000** [comment]
I am not sure what is the problem. What I have is wallet backup file,
password for it (but it says it cant decrypt) and I even have copy of the
key (don't worry, they are stashed in safe place). Appreciate anyone's help
with this.

Regards,

Zvonimir

P.S.


I send report through Bitcoin wallet android app. In there are probably
also logs and stuff necessary to make some analysis.

**Comment by JeffreyLeonard** [comment]
How do I Chang password

Jeffrey Leonard

**Comment by procyon12lotor** [comment]
@ligi Is there any way you can delete the @ mention of my username above? Thanks!

**Comment by JeffreyLeonard** [comment]
Jeffrey Leonard
