### ISSUE TITLE
buildable in osx?

### ISSUE THREAD

**Issue by tofutim** [bitcoin-wallet/bitcoin-wallet#526]
I tried using gradle to do a clean build and got the following error
```
* What went wrong:
A problem occurred evaluating project ':native-scrypt'.
> Failed to apply plugin [class 'com.android.build.gradle.model.AndroidComponentModelPlugin']
   > Gradle version 2.10 is required. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in xxx/bitcoin-wallet/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
```
Is this normal? I installed gradle using `brew install gradle`, will try the suggestion.

**Comment by schildbach** [comment]
Yes, you currently need Gradle 2.10.

**Comment by tofutim** [comment]
How hard do you think it would be to get the project working with gradle 4.6? Is it a long road?

**Comment by schildbach** [comment]
The main blocker for higher Gradle versions is the gradle-experimental plugin, which is where the above error stems from.

**Comment by tofutim** [comment]
i'm curious, is there a reason bitcoinj is used instead of just plunking the c++ code into NDK?
