### ISSUE TITLE
Any chance this can be ported over to Raven coin?

### ISSUE THREAD

**Issue by Cryptonoodle** [bitcoin-wallet/bitcoin-wallet#530]
Interested in seeing this ported over to the sleeping giant that is Ravencoin

https://github.com/RavenProject/Ravencoin

**Comment by HashEngineering** [comment]
If you can find a developer to do it or do it yourself.  It's a lot of work to port this code and to maintain.  I have done it several times, but maintenance and updates on what I have done leave me with no time to take on new projects.
