### ISSUE TITLE
[feature request] Lightning support

### ISSUE THREAD

**Issue by JavierRSobrino** [bitcoin-wallet/bitcoin-wallet#531]
Please add Lightning support, so when it is ready, we can start using with this wallet.

**Comment by schildbach** [comment]
If someone wants to work on this, it needs to be implemented in (or on top of) bitcoinj first.

**Comment by JeffreyLeonard** [comment]
Thank you for your help with everything. I wish I could understand this more I keep trying but I don't think I am getting anywhere with any of this.
