### ISSUE TITLE
Export private keys

### ISSUE THREAD

**Issue by AwSoMe700** [bitcoin-wallet/bitcoin-wallet#535]
As far as i can find there is no easy way to just export your private key directly from the app. I know this is one of the least secure ways to transport and export your wallet but this could be usefull for example to claim forked coins. 

Or is there some way to use the backup file to get your private key unencrypted that i missed?

**Comment by schildbach** [comment]
See https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md
