### ISSUE TITLE
Android wallet no longer opens

### ISSUE THREAD

**Issue by R4FKEN** [bitcoin-wallet/bitcoin-wallet#538]
After the latest update, the wallet doesn't open...

**Comment by R4FKEN** [comment]
That's v6. 25

**Comment by schildbach** [comment]
What's happening?

**Comment by R4FKEN** [comment]
Nothing, really... The opening screen (with the Bitcoin logo) shows for a second, then disappears...

**Comment by schildbach** [comment]
What version have you been on before? What language is your phone configured to use? What Android version is on your phone?

**Comment by R4FKEN** [comment]
Previous version: I have automatic updates turned on, so unless there were a few updates simultaneously, I was on v6.24.
Language: English (UK)
Android version: 8.0.0 (Huawei P20 Lite)

**Comment by schildbach** [comment]
Thanks. Do you have access to "adb logcat" to see what exception occurs?

**Comment by R4FKEN** [comment]
It took me over an hour to figure out how to do it without root, but I think I got something :)

06-14 19:04:08.055 7130-7160/? E/ActivityThread: Failed to find provider info for de.schildbach.wallet.address_book
06-14 19:04:08.341 7130-7180/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: de.schildbach.wallet, PID: 7130
    java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
        at de.schildbach.wallet.data.AddressBookLiveData$1.run(AddressBookLiveData.java:63)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
06-14 19:04:08.348 768-2411/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
06-14 19:04:08.352 768-2411/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
06-14 19:04:08.355 1159-1809/? E/ActivityManager: The same pid with last one, do not add dropbox and clear mLastCrashedPid. mLastAppCrashedPid==7130
06-14 19:04:08.360 768-2411/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
06-14 19:04:08.360 768-2411/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
    FaultDetect: DUMPTOOL_PRINTF return.
06-14 19:04:08.408 1159-3236/? E/ReportTools: This is not beta user build
06-14 19:04:08.474 1419-11958/? E/HsmCoreServiceImpl: onTransact in code is: 103
06-14 19:04:08.485 1159-1271/? E/WindowManager: win=Window{bdd4e14 u0 Splash Screen de.schildbach.wallet EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
06-14 19:04:08.504 768-2411/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
06-14 19:04:08.518 1159-1311/? E/InputDispatcher: channel '6fa6444 de.schildbach.wallet/de.schildbach.wallet.WalletActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-14 19:04:08.518 1159-1311/? E/InputDispatcher: channel 'ba87698 de.schildbach.wallet/de.schildbach.wallet.WalletActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-14 19:04:08.542 1419-11958/? E/HsmCoreServiceImpl: onTransact in code is: 102

Let me know if you need more / something else.

**Comment by schildbach** [comment]
Thanks, that helps! We're on it.

**Comment by schildbach** [comment]
Fixed in version 6.26.
