### ISSUE TITLE
Import Private Key

### ISSUE THREAD

**Issue by KaushikTechcronus** [bitcoin-wallet/bitcoin-wallet#541]
I've imported private key and transfer balance to new wallet.

It will display balance in pending transactions.

In transaction history, when I click on transaction hash then it displays "No transaction found with the hash".

Please help me with this.

**Comment by schildbach** [comment]
This appears to be unrelated to the app. We don't have such a message.

**Comment by KaushikTechcronus** [comment]
I'm talking about "Sweep Paper Wallet" functionality.

**Comment by schildbach** [comment]
Can you add a screenshot with the message?
