### ISSUE TITLE
Restore from 24 word seed

### ISSUE THREAD

**Issue by KaushikTechcronus** [bitcoin-wallet/bitcoin-wallet#544]
Hello,

At time of restore from 24 words seed, I passed **"1409478661L"** creation time and I will get proper balance and all. But it will take half an hour to 

But if I want to pass creation time when seeds were generated then what method should I implement to get creation time when seeds were generated in bitcoinj?

Please help me with this.

**Comment by schildbach** [comment]
Bitcoin Wallet currently doesn't support word seeds.
