### ISSUE TITLE
Battery optimization on Android 8.0 prevents the wallet from syncing

### ISSUE THREAD

**Issue by fedsten** [bitcoin-wallet/bitcoin-wallet#557]
Android 8.0 has introduced a battery optimization change that creates limits on how freely apps running in background can access to the device's resources. This prevents bitcoin-wallet and other apps connected to the Bitcoin network from syncing the blocks when the app is running in background.

Luckily this can be solved by going to "Special app access" in the device's settings and deactivate the battery optimization feature for individual apps.

Since if not addressed this prevents users from being able to use the wallet, I suggest to at least put a helper message somewhere to guide users in deactivating the battery optimization for bitcoin-wallet.

As a reference: https://developer.android.com/about/versions/oreo/android-8.0-changes

**Comment by schildbach** [comment]
Yes, that's a known issue. The plan is to rewrite the background process to use WorkManager, as soon as that component is final.

**Comment by Apollo1993** [comment]
#51

**Comment by schildbach** [comment]
We fixed this by using a combination of WorkManager and a Foreground Service. No "doze exception" needed.
