### ISSUE TITLE
Change Derive Path

### ISSUE THREAD

**Issue by KaushikTechcronus** [bitcoin-wallet/bitcoin-wallet#559]
Hello,

I've used bitcoinj wallet and used derive path as below.

`public static final ImmutableList<ChildNumber> ACCOUNT_ZERO_PATH = ImmutableList.of(ChildNumber.ZERO_HARDENED);`

But I made changes in above path for generating bip44 standard addresses.

`public static final ImmutableList<ChildNumber> BIP44_ACCOUNT_ZERO_PATH =ImmutableList.of(new ChildNumber(44, true), new ChildNumber(0, true), new ChildNumber(0, true));`

Now As I load wallet in application then it loads from backup and app crashes because it took old derive path and I changed it.

So it won't find old derive path and app crashes.

How can I change derive path?

Please help.

Thanks.

**Comment by schildbach** [comment]
The app currently doesn't support an other path than the BIP32 default account.

**Comment by KaushikTechcronus** [comment]
Hello,
I copied and pasted all classes of bitcoinj in my app and then changed the derive path.
