### ISSUE TITLE
massive number of DNS requests

### ISSUE THREAD

**Issue by bjacke** [bitcoin-wallet/bitcoin-wallet#564]
looking at a network trace of my android device, I saw that starting bitcoin wallet generates at startup immediately ~4000 DNS requests for "A bitseed.xf2.org" and "A bitcoin.bloqseeds.net". All those requests are being ent so fast that the server did not even have time to send a single reply. Both DNS names also have broken DNS servers obviously and they time out (maybe they are unreachable because of too many queries from various bitcoin wallet devices?).
My DNS server that is used also logs errors due to the massive amount of DNS queries generated by bitcoin wallet.
Bitcoin wallet should stop those requests as soon as possible and make sure that only a single DNS request for those names is being done.

**Comment by schildbach** [comment]
Interesting find, it certainly shouldn't do that.

Can you tell how you acquired the network trace (perhaps share a bit of that trace), and what device and Android version did you test this on? Also, can you share the Bitcoin Wallet logfile that covers the time peroid of the trace? You can use Options > Report issue and send it to yourself so you get to read the file attachments.

**Comment by bjacke** [comment]
i was sniffing this between the router and the DNS server. Now I figured out how to sniff between the android device and the router wifi port and had to find out that the massive DNS queries actually had been generated by the router and not by bitcoin wallet. The trigger was the unresonsive DNS server of those DNS names but the problem was actually the router. Sorry for the false report.

**Comment by schildbach** [comment]
Ok, never mind. Thanks for the folllow up.
