### ISSUE TITLE
Many wallet addresses

### ISSUE THREAD

**Issue by hoanghiephui** [bitcoin-wallet/bitcoin-wallet#567]
Hi
I see many address(Your address in the Address Book), listed in my wallet. That is how, I will use any address to receive coin.
Thanks

**Comment by schildbach** [comment]
You all addresses under 'Your addresses' can be used for receiving.

**Comment by JeffreyLeonard** [comment]
schildbach what do you mean you will use the wallet

**Comment by JeffreyLeonard** [comment]
I miss understood them I thought they were going to use mine as their own..
Thank you

jffrlnrd

**Comment by JeffreyLeonard** [comment]
jffrlnrd

**Comment by hoanghiephui** [comment]
Thanks

**Comment by hoanghiephui** [comment]
Ssss
