### ISSUE TITLE
How to create raw transaction

### ISSUE THREAD

**Issue by KaushikTechcronus** [bitcoin-wallet/bitcoin-wallet#569]
Hello,

I used bitcoinj for bitcoin transactions.

I want to send btc. For that I want to create raw transaction from unspent output.

Please help me in creating raw transaction.

Thanks.

**Comment by schildbach** [comment]
Please use the mailing list for questions.

**Comment by KaushikTechcronus** [comment]
> 
> 
> Please use the mailing list for questions.

Where's your mailing list?

**Comment by schildbach** [comment]
See https://bitcoinj.github.io/#community

**Comment by a198d22** [comment]
ให้ทำอย่างไรผมทำไม่เป็น
ภาษาอังกฤษก็ไม่เก่งบอกมาเลยต้องทำอย่างไรครับ

เมื่อ 4 ม.ค. 2019 5:06 หลังเที่ยง "KaushikTechcronus" <
notifications@github.com> เขียนว่า
