### ISSUE TITLE
Your contact email is not working

### ISSUE THREAD

**Issue by mshanx** [bitcoin-wallet/bitcoin-wallet#571]
Hello guys.
What's your working contact email? I used the one mentioned in the Google Play but it's not working.
I need to get in touch with you.
Thanks

**Comment by yousifyou** [comment]
yousfani.1966@gmail.com

في الجمعة، ٢٥ يناير، ٢٠١٩ ٧:٢٢ ص jesskie <notifications@github.com> كتب:

> Someone is manipulating with my accouñts
>
> jess
>
