### ISSUE TITLE
F-Droid release is behind

### ISSUE THREAD

**Issue by betsythefc** [bitcoin-wallet/bitcoin-wallet#573]
The newest Release is 7.0, but only 6.35 is available from 3 months ago on F-Droid.

**Comment by schildbach** [comment]
The speed of updates on F-Droid is not in our hands. So I'm closing this.

**Comment by schildbach** [comment]
Just for the record: This issue is tracked at Duplicate of https://gitlab.com/fdroid/fdroiddata/-/issues/1884
