### ISSUE TITLE
Reset blockchain - only 6 months of history is scanned

### ISSUE THREAD

**Issue by andronoob** [bitcoin-wallet/bitcoin-wallet#575]
Historical transactions older than 6 months are discarded & ignored.

**Comment by schildbach** [comment]
What do you mean by "discarded"?
What do you mean by "ignored"?

**Comment by andronoob** [comment]
Sorry. I must have confused two different wallet.
I exported xpub, checked several addresses, then it turned out that this wallet has indeed no transaction at all - I once thought that it was a used&emptied old wallet backup - it's not.
