### ISSUE TITLE
SegWit transaction displayed as "delayed/insecure"

### ISSUE THREAD

**Issue by andronoob** [bitcoin-wallet/bitcoin-wallet#576]

**Comment by schildbach** [comment]
Can you tap on the payment to expand it? Then select 'Report issue' from the payment's context menu and send your report. Thanks.

**Comment by andronoob** [comment]
[report.zip](https://github.com/bitcoin-wallet/bitcoin-wallet/files/2973948/report.zip)
txid: d3e740a72bee105f5ef8245c015906300cb94c8b5c4d91263333ff5a22b80e3c

**Comment by schildbach** [comment]
This has nothing to do with Segwit.

The sender used RBF, which makes the transaction unsafe. As safety has priority, RBF txns are not shown until confirmed. From the point of confirmation on, RBF txns are not unsafe any more. If you expect more payments from the same sender, ask them to not use RBF.
