### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [bitcoin-wallet/bitcoin-wallet#582]
Hello! I really like your project and I'd like to contribute to it by designing a logo. If you'd want that too, please let me know if there are any specific things you'd want this logo to represent, and if you don't have any I'll just implement my own ideas. Looking forward to hearing from you :)

**Comment by schildbach** [comment]
Feel free to propose iterative changes to what we already have.

**Comment by amirziari** [comment]
Thank you and this suggestion and I'm going to see the logo. My priority is my brand.Our in addition to the stock exchange indexes, properties or retail in any situation where the job creates a business, our business is flexible.The mine of the desired 
"ziariholding SE llc"

**Comment by newfinal100** [comment]
So here are some variations I made, if you're interesting in adopting one of these let me know. Also feel free to tell me about any improvements/changes you'd want me to make.

![versions](https://user-images.githubusercontent.com/49202520/55889735-d311aa00-5bb1-11e9-947f-a032f81ad18d.jpg)

**Comment by mary03** [comment]
Fear

**Comment by schildbach** [comment]
I'm afraid the proposals don't appear to resonate. Probably the orange Bitcoin logo is favored by many. Thus, I'm closing this. Thank you for your proposals.
