### ISSUE TITLE
Connect to trusted node on non-standard port

### ISSUE THREAD

**Issue by ruthtern** [bitcoin-wallet/bitcoin-wallet#589]
My node can not listen on port 8333 because it is connected to a commercial VPN service which lets me port forward through the VPN connection, but then offers a limited set of available port numbers - never 8333. I chose one of the available port numbers (29823), then added port=29823 to bitcoin.conf. This works perfectly 

Now I want to connect my Android Bitcoin Wallet to my own node as the only trusted node, but the wallet can only connect to port 8333. Please allow the Trusted peer configuration to use a port which is not 8333

**Comment by schildbach** [comment]
Guess we could support that. Is anyone up for a pull request?

**Comment by amirziari** [comment]
Yes

**Comment by joungakim** [comment]
네~~

**Comment by mrzadik** [comment]
https://get.cryptobrowser.site/9259735?f=sn

**Comment by reflodark** [comment]
I think that this issue can be closed. Works on my app and was implemented with v8.04-v8.11,
