### ISSUE TITLE
Modifying the Genesis Block Accessing Your Own Chain Your own chain is not the same as the other in the creation block. Then you can transfer the currency on your own chain. The transaction has not been confirmed.

### ISSUE THREAD

**Issue by yuzhongrong** [bitcoin-wallet/bitcoin-wallet#597]
![image](https://user-images.githubusercontent.com/7382234/65784088-e5919700-e183-11e9-8fed-6460fc210033.png)

![image](https://user-images.githubusercontent.com/7382234/65784325-605ab200-e184-11e9-9472-21bd851d2b10.png)

**Comment by yuzhongrong** [comment]
Our chain is basically the same as btc fork

**Comment by yuzhongrong** [comment]
I guess that the coin was not received. It is the ECONOMIC mode.

**Comment by charlyeruined** [comment]
@yuzhongrong

**Comment by schildbach** [comment]
This is obviously from a fork of Bitcoin Wallet (for "CMC"). Also, I don't understand the problem description. As no one else jumped in, I'm closing this.

If you can reproduce this problem on Bitcoin Mainnet or Testnet, feel free to open another issue and provide a clear and concise description of the problem.

**Comment by AndreV84** [comment]
@yuzhongrong 
were you able to solve it?
@schildbach I do not see that you could provide a solution for connecting the bitcoin-wallet to own bitcoin form crypto server node, do you? Regular bitcoin desktop wallet kind of have .config file that could be used to specify a custom server, but the android app doesn't have it, right?

**Comment by schildbach** [comment]
Config files are uncommon for mobile apps. Also, it would take more than a declarative configuration (wether via config file or not) to support a different coin. Usually other coins come with different rules too.

The way to support this is fork bitcoinj and implement the coin. Then fork Bitcoin Wallet and use your fork of bitcoinj.

**Comment by AndreV84** [comment]
@schildbach  are you able to provide any pointers
at which exactly files, lines of the code to hardcode the custom server port for connection by bitcoinj/ bitcoin-wallet for android?
