### ISSUE TITLE
Payment Protocol support?

### ISSUE THREAD

**Issue by kuba-orlik** [bitcoin-wallet/bitcoin-wallet#600]
I'm trying to make a transaction using BitPay, and after scanning the QR code in the app it shows an error message:

```
FETCHING PAYMENT REQUEST FAILED

The payee (bitpay.com) is using an incompatible payment protocol (reason: address, amount)
```

The [bitpay docs](https://support.bitpay.com/hc/en-us/articles/115005701523-Which-Wallets-Work-Best-for-a-BitPay-Payment-) mention that only wallets that support Payment Protocol are supported. Does that mean that this here Bitcoin Wallet does not support this protocol?

**Comment by schildbach** [comment]
Bitcoin Wallet fully supports BIP70 and BIP71, but only a slightly modified version of BIP72 (due to security concerns with the original BIP72). However the reason for the failure is BitPay doesn't support BIP21 any more.
