### ISSUE TITLE
Wallet backup not listed when trying to restore on Android 10

### ISSUE THREAD

**Issue by Apehaenger** [bitcoin-wallet/bitcoin-wallet#601]
My Smartphone died.
Restored/reinstalled all stuff, placed my wallet backup into the /Download folder, but the backup isn't listed in the wallet recovery window. It only says that I shall ensure that it's located in the "external" storage within the "/Download" folder.
My new phone does not have an external storage. Trying to simply copy my backup file to /sdcard/Download also did not helped.

Lastly I made a new backup from the empty wallet and it got placed within my internal storage /Download folder (beside my old backup).
Tried again the wallet recover function but it still can't see the backup (neither the newly created one)... that's why I'm writing here.

Any suggestions please?!

BTW: I'm on an Xiaomi Mii 9 with Android 10

**Comment by Apehaenger** [comment]
Personally doesn't harm me anymore, cause I could reanimate my old smartphone in safe-mode. Immediately transferred all BTC's to another wallet.

However, backup/restore should work for better user satisfaction.

I'll let the App installed for later testing possibility if you guys have some kind of solution.

**Comment by schildbach** [comment]
**What version of the app have you been using?**

One thing to note is that if you create a backup that file isn't created in the filesystem any more. It gets saved to a SAF (storage access framework) provider of your choice. For most users this will be Google Drive.

The easy way to restore from a backup on Google Drive is simply to tap that file in the Drive app. That should work with other SAF providers too. The Options→Safety→Restore option is only meant for restoring from old backups or if you manually copy the file to `/sdcard/Download`.

**Comment by Apehaenger** [comment]
Hi.
Thanks a lot for responding.

I'm using Version 7.24.

Google Drive is in my opinion the worst place where I would store any BTC Wallet, even if it's encrypted.
However, I unfortunately don't have Google Drive but I've a personal Nextcloud on an private Server.
I already tried to open it from there, but I wasn't able to choose Bitcoin as responsible Application. It's simply not in the list of "open with" applications and I'm not able to choose it.

I simply thought it should work the way as the restore window says, by placeing it in the /Download folder.

**Comment by schildbach** [comment]
Do you have a "NextCloud" app installed? Can you provide a link to that app so I can test this combination?

With Android 10, Google has more or less restricted file access to the storage access framework. This doesn't necessarly mean Google Drive, SAF targets can also be provided by oder SAF providers, e.g. a NextCloud app.

**Comment by Apehaenger** [comment]
I'm using the normal official Nextcloud App from https://play.google.com/store/apps/details?id=com.nextcloud.client
Currently I've version 3.9.0 installed.

If you're interested in an account for easier testing, please drop me a short note to joerg at ebeling dot ws

**Comment by schildbach** [comment]
Ok great. Then you should be able to tap your backup file in the NextCloud app and a wallet restore dialog should pop up.

**Comment by Apehaenger** [comment]
I worry that I'm not that dumb than assumed.
![Screenshot_2019-11-15-17-57-00-503_android](https://user-images.githubusercontent.com/23478605/68961178-11b7b480-07d2-11ea-9115-671341ee3b78.jpg)

**Comment by schildbach** [comment]
Looks like the Nextcloud app has lost the file association. In this case this method won't work. Instead, we suggest updating our app to version 7.32 and use Options→Safety→Restore wallet. It should more or less open the same dialog but you can pick any file.

**Comment by Apehaenger** [comment]
Quite cool!
Just installed version 7.32 as advised, and now I'm able to load the backup file.
Restore succeed and sync is running now.

Thanks a looot for the quick solution!!
