### ISSUE TITLE
Lot of data usage

### ISSUE THREAD

**Issue by Boerny** [bitcoin-wallet/bitcoin-wallet#602]
Today the app used more than 19GB of data over my mobile connection.
The last months i had 0 traffic.

Any clue how the app would use such an amount of data?

**Comment by schildbach** [comment]
This should be fixed in version 7.31 via 42a5d10bdbec4cbcf172449519bf1d903476a01b and e1ab3fae9705704b0517f3856467fdd2f06ae9fc.

**Comment by madduck** [comment]
Any idea when 7.31 will be on FDroid? I upgraded to 7.27 today (from 7.22), and it chewed up all my mobile data allowance for the month on the first day :((

**Comment by schildbach** [comment]
I don't know. I uploaded it weeks ago, but unfortunately F-Droid is stuck.

**Comment by madduck** [comment]
Okay, thanks for the update. I guess I'll cut my losses and disable the app for now. Cheers, -m
