### ISSUE TITLE
Exchange rate window won't open

### ISSUE THREAD

**Issue by fufik** [bitcoin-wallet/bitcoin-wallet#606]
I can't see exchange rates nor price in the main activity of my assets in fiat. I don't know why, it did work before...

**Comment by fufik** [comment]
Lmao, that's because bloody Roskomnadzor blocked BitcoinAverage.com.

**Comment by fufik** [comment]
Wait, it's worse, I can't even find it in the block list. It just won't open on some providers and shows "blocked legally" dummy page on others. Okay.

**Comment by schildbach** [comment]
In any case, a blocked BitcoinAverage.com is nothing we can change. You're advised to get in contact with your Internet provider then.
