### ISSUE TITLE
Inconsistency when reproducing the build for version `7.43`

### ISSUE THREAD

**Issue by Giszmo** [bitcoin-wallet/bitcoin-wallet#612]
Verifying version 7.23 went smooth but now with 7.43 I get some tiny discrepancies and wonder why.

```
$ git fetch
$ git checkout $( git tag | grep 7.43 )
$ docker run -it --volume $PWD:/mnt --workdir /mnt --rm mycelium-wallet bash
root@209f3ccda71a:/mnt# yes | /opt/android-sdk/tools/bin/sdkmanager "build-tools;29.0.2"
root@209f3ccda71a:/mnt# apt update && apt install gradle -y
root@209f3ccda71a:/mnt# gradle clean :wallet:assProdRel
root@209f3ccda71a:/mnt# exit
$ apktool d -o fromBuild wallet/build/outputs/apk/prod/release/bitcoin-wallet-prod-release-unsigned.apk
$ apktool d -o fromGoogle Bitcoin\ Wallet\ 7.43\ \(de.schildbach.wallet\).apk 
$ diff --recursive from*
diff --recursive fromBuild/apktool.yml fromGoogle/apktool.yml
2c2
< apkFileName: bitcoin-wallet-prod-release-unsigned.apk
---
> apkFileName: Bitcoin Wallet 7.43 (de.schildbach.wallet).apk
Only in fromGoogle/original/META-INF: BITCOIN-.RSA
Only in fromGoogle/original/META-INF: BITCOIN-.SF
diff --recursive fromBuild/original/META-INF/MANIFEST.MF fromGoogle/original/META-INF/MANIFEST.MF
4a5,523
> Name: AndroidManifest.xml
> SHA-256-Digest: SMUmCowM699Ms38Sg/3p7NzuN0tqLZ6NEsyzGPdLdsI=
> 
> Name: META-INF/services/java.security.Provider
> SHA-256-Digest: tQoHBUCrFboIZe48gchWFvVN/Ox53Piv2CIFeI9FLaw=

...

diff --recursive fromBuild/res/layout/custom_dialog.xml fromGoogle/res/layout/custom_dialog.xml
2,5c2
< <RelativeLayout android:layout_width="fill_parent" android:layout_height="fill_parent"
<   xmlns:android="http://schemas.android.com/apk/res/android">
<     <Button android:id="@id/dialog_button" android:layout_width="100.0px" android:layout_height="wrap_content" android:layout_marginTop="5.0dip" android:layout_marginRight="5.0dip" android:text=" Ok " />
< </RelativeLayout>
\ No newline at end of file
---
> <x />
\ No newline at end of file
diff --recursive fromBuild/res/layout/spinner_item.xml fromGoogle/res/layout/spinner_item.xml
2,3c2
< <TextView android:id="@android:id/text1" android:paddingLeft="4.0dip" android:paddingRight="4.0dip" android:layout_width="fill_parent" android:layout_height="wrap_content"
<   xmlns:android="http://schemas.android.com/apk/res/android" />
\ No newline at end of file
---
> <x />
\ No newline at end of file
Only in fromBuild/res: mipmap-hdpi
Only in fromBuild/res: mipmap-xhdpi
```

That diff is manageable:

* All files in META-INF differ due to signature not being reproducible by design.
* Our APK has 4 extra PNGs. Although that is surprising, there is probably not
  a backdoor in the absence of those binaries.
* Our APK has some tiny bit of extra content in two layout xml files. Again, that
  cannot be critical.
* apktool.yml is generated when unpacking the APK and no content of the APKs.

but still surprising to me.

**Comment by schildbach** [comment]
Thanks for verifying the APK. I was able to reproduce your findings by comparing three builds:

1. Outside Docker, like described in the Bitcoin Wallet readme.
2. Within Docker, like you did.
3. APK as downloaded from Google Play.

Comparing 1 and 2 yields this difference:

```
--- docker/
+++ outside-docker/
├── apktool.yml
│ @@ -1,9 +1,9 @@
│  !!brut.androlib.meta.MetaInfo
│ -apkFileName: bitcoin-wallet-prod-release-unsigned_build-in-docker.apk
│ +apkFileName: bitcoin-wallet-prod-release-unsigned_build-outside-of-docker.apk
│  compressionType: false
│  doNotCompress:
│  - arsc
│  - res/drawable-hdpi-v4/notification_bg_low_normal.9.png
│  - res/drawable-hdpi-v4/notification_bg_low_pressed.9.png
│  - res/drawable-hdpi-v4/notification_bg_normal.9.png
│  - res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png
```

I would assume this is due to a difference in your 'mycelium-wallet' image. You use 'latest' rather than a specific version – can you specify the exact version?

Comparing 1 and 3 yields the mipmaps as difference. I currently cannot say for sure, but likely this is due to my signing build not properly clearing. I know that the files should not exist any more, but they existed in previous versions. I will verify this assumption this weekend and release a fixed version.

**Comment by Giszmo** [comment]
I built the image from the Dockerfile in current mycelium-com/wallet-android master, so ... no well defined version.

I have a dilemma with Docker: If I build the image from the Dockerfile, I can trust it but it's not the same as the one you build. If I just pull it from docker.io(?), I trust whoever built it to not have baked in some backdoor. (Not sure how or if `ubuntu:18.04` or any of those base images is scrutinized.)

Especially in the case of apps that don't provide a Docker image, I use Docker to protect my system from whatever 30 wallets' `gradle build` might do to it.

If you don't get what I get, even when using some mycelium-wallet Docker image, the best approach would probably be to use an image that does reproduce the original build and share the build instructions accordingly.

**Comment by schildbach** [comment]
Ok, I investigated into this more thoroughly. The issue is you didn't do a clean checkout of the sources – rather you updated from an earlier version. I know `gradle clean` should do, but in the case of SVG to PNG conversion it unfortunately doesn't. Alternatively, you can simply remove these directories (including contents) before your next build:

```
	res-prod/mipmap-hdpi/
	res-prod/mipmap-xhdpi/
	res-prod/mipmap-xxhdpi/
	res-prod/mipmap-xxxhdpi/
	res/mipmap-hdpi/
	res/mipmap-xhdpi/
	res/mipmap-xxhdpi/
	res/mipmap-xxxhdpi/
```

After you've done this, and tried reproducing version 7.43 again, can you report any remaining diff via `diffoscope`? It includes more useful information than just `diff`.

**Comment by schildbach** [comment]
I've also been looking at this diff:

```
├── res/layout/spinner_item.xml
│ ├── res/layout/spinner_item.xml
│ │ @@ -1,2 +1,2 @@
│ │  <?xml version="1.0" encoding="utf-8"?>
│ │ -<x/>
│ │ +<TextView android:id="@android:id/text1" android:layout_height="wrap_content" android:layout_width="fill_parent" android:paddingLeft="4.0dip" android:paddingRight="4.0dip" xmlns:android="http://schemas.android.com/apk/res/android"/>
├── res/layout/custom_dialog.xml
│ ├── res/layout/custom_dialog.xml
│ │ @@ -1,2 +1,4 @@
│ │  <?xml version="1.0" encoding="utf-8"?>
│ │ -<x/>
│ │ +<RelativeLayout android:layout_height="fill_parent" android:layout_width="fill_parent" xmlns:android="http://schemas.android.com/apk/res/android">
│ │ +  <Button android:id="@id/dialog_button" android:layout_height="wrap_content" android:layout_marginRight="5.0dip" android:layout_marginTop="5.0dip" android:layout_width="100.0px" android:text=" Ok "/>
│ │ +</RelativeLayout>
```

I'm pretty sure these two files are unused. They likely stem from an AndroidX library. I have no idea why there is a diff, but the `<x/>` looks like a shrinked version of the full resource XML.

**Comment by schildbach** [comment]
I tried to get `disorderfs` to work with Docker. This is currently required to produce reproducible output. Unfortunately for mounting a FUSE filesystem inside a container extensive privileges need to be granted. I tried to apply disorderfs outside of Docker and then mounting the volume on top, but that doesn't work either.

Given the above problems, I'm afraid currently I can only recommend to build _without_ Docker.

**Comment by Giszmo** [comment]
:D Andreas you went on the same ugly journey around disorderfs like me this weekend. I found it to work almost the way I wish it does by disorderfs mounting the folder and starting the container on that mount point:

Run the following in the project root dir:

```
$ mkdir /tmp/sorted
$ sudo disorderfs --sort-dirents=yes --multi-user=no $PWD /tmp/sorted/
$ cd /tmp/sorted/
$ docker run --rm --volume $(pwd):/project --workdir /project ...
```

... no scary permissions required. Only ugly part is that you have to disorderfs on the host, so it's an extra burden on the verifier.

(Mycelium's upcoming release also turns non-verifiable if disorderfs is not acceptable. I'm not sure yet how to handle it.)

**Comment by Giszmo** [comment]
> The issue is you didn't do a clean checkout of the sources – rather you updated from an earlier version. I know gradle clean should do, but in the case of SVG to PNG conversion it unfortunately doesn't.

Noted. Clearly then I should by default do a fresh checkout instead of just updating for all the projects. I remember jenkins also had this "fresh checkout" option on by default.

I hope you excuse the noise caused and hope we can establish standards of what's the burden we can put on projects to count as verifiable. And this is only the beginning. I kept this wallet marked as "verifiable", so please excuse me if I don't update the Analysis until the next release's check. Finding standards and automating stuff has priority ;)

**Comment by schildbach** [comment]
> sudo disorderfs --sort-dirents=yes --multi-user=yes $PWD /tmp/sorted/

You should be able to do this without `sudo`. It's a FUSE filesystem (user space).

I suggest adding `--reverse-dirents=no` because the default appears to be reverse ordering.

You can unmount the mount with `fusermount --unmount`.

In your case maybe Jenkins can provide the "wrapping inside disorderfs", just like it provides the checkout from git?

**Comment by Giszmo** [comment]
Try without sudo and run the Docker. That's how I lost 3h or so :D

```
$ man disorderfs
...
           --multi-user=yes requires disorderfs to run as root.
```

**Comment by schildbach** [comment]
> `docker: Error response from daemon: error while creating mount source path '/tmp/builddir': mkdir /tmp/builddir: file exists.`

I finally solved my problem with disorderfs by adding `-o allow_root` as an additional argument.

**Comment by schildbach** [comment]
…but in the end, it doesn't help. The diff is still there.

**Comment by schildbach** [comment]
Finally, if I disable resource shrinking in `wallet/build.gradle`, the diff is gone:

```
--- wallet/build/outputs/apk/prod/release/bitcoin-wallet-prod-release-unsigned.apk
+++ reproducible-output/bitcoin-wallet-prod-release-unsigned.apk
├── zipinfo -v {}
│ @@ -5051,15 +5051,15 @@
│    version of encoding software:                   0.0
│    minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
│    minimum software version required to extract:   0.0
│    compression method:                             none (stored)
│    file security status:                           not encrypted
│    extended local header:                          no
│    file last modified on (DOS date/time):          1980 000 0 00:00:00
│ -  32-bit CRC value (hex):                         14cc6a43
│ +  32-bit CRC value (hex):                         64942254
│    compressed size:                                997788 bytes
│    uncompressed size:                              997788 bytes
│    length of filename:                             14 characters
│    length of extra field:                          0 bytes
│    length of file comment:                         0 characters
│    disk number on which file begins:               disk 1
│    apparent file type:                             binary
```

Turns out the option is ignored in a Docker container, for whatever reason. Since the space savings of resource shrinking is neglible, I will disable it for the next Bitcoin Wallet version.

**Comment by yramoris** [comment]
Вы немаглыби присилать на руско языке присилать

пн, 13 Янв 2020, 17:08 Andreas Schildbach <notifications@github.com>:

**Comment by schildbach** [comment]
Version 7.45 is now rolling out, which I expect will fix this issue. Can you retry? If some of these problems remain, don't hesitate to comment and I'll re-open the issue. Thanks again for your report!

**Comment by Giszmo** [comment]
I could verify the latest build with [this script](https://gitlab.com/walletscrutiny/walletScrutinyCom/blob/master/test.sh). Ideally this script keeps working with minor changes only, so I can quickly and ideally in an automated way verify future releases.

I still need a mechanism by which I get new APKs asap, as alarming users after 100% rollout is probably not helpful.

**Comment by schildbach** [comment]
On GitHub and GitLab, I tag new versions as soon as their APK is about to touch the Play Store Console. Then I usually upload APKs to the beta channel first (and wait until it is published which can take several days sometimes), so I suggest you to join beta testing.

As soon as you have both, you should be ready to go.

I think ideally we'd find a way to distribute the APK to verifiers _before_ the Google Play review is happening but in a way such that the APK cannot be altered any more. Then you'd have more time to verify before actual rollout happens. I wonder if any of the closed (alpha) channels could be used for that.

**Comment by Giszmo** [comment]
> so I suggest you to join beta testing

I guess that would work for now as there are only 4 wallets we succeeded to verify and as people don't rely much on the verdict meaning anything.

> I think ideally we'd find a way to distribute the APK to verifiers before the Google Play review is happening but in a way such that the APK cannot be altered any more. Then you'd have more time to verify before actual rollout happens. I wonder if any of the closed (alpha) channels could be used for that.

I hope so, too. My idea was to even further decelerate the release process, with a higher category in WalletScrutiny that would be a commitment by the app providers to submit future updates a week before releasing them, with further delays if concerns are raised ("Can't review 20k lines of code in one week"...). With only 4 wallets in the top category there would not be much incentive to such a commitment though.

> in a way such that the APK cannot be altered any more

What you mean? It's open source, so people can compile what they want and with the signature on it, they can't but people might update to that still in quarantine apk.

As long as Google doesn't get on board, providers can always release whatever they want. If people would care, verifiers sounding the alarm if an unsubmitted apk was found in the wild should be enough of an incentive to not alter the app without submitting to verifiers and hopefully verifiers sounding alarm will one day be enough for Google to halt rollouts.

**Comment by schildbach** [comment]
> > in a way such that the APK cannot be altered any more
> 
> What you mean? It's open source, so people can compile what they want and with the signature on it, they can't but people might update to that still in quarantine apk.

Think of what your service provides. It asserts some property of a specific version. What's the value of this information, if the specific version could be silently exchanged by me or someone else? Google Play provides some protection against this attack by limiting upload access to developers. Also, once a versionCode has been used on Production, Beta or Alpha channels it can't be reused.

However, a versionName can be reused without problems. An authorized developer could release a malicious version to Google Play, increasing versionCode but not versionName. Perhaps you should start referencing versions by versionCode to mitigate against this?

> As long as Google doesn't get on board…

If Google were to get on board properly, they would add an "open source" category of apps which would allow developers to upload the source rather than the binary APK, build the APK on Google infrastructure and slap the developer-provided signature on it (verifying if it matches). That's basically the F-Droid process.

As a bonus, they would offer a system for collecting certifications, like yours. Or by actual code reviewers. Or by automated scans, like Play Protect.

**Comment by Giszmo** [comment]
> Perhaps you should start referencing versions by versionCode to mitigate against this?

So far all tags I have seen matched the versionName and not the versionCode and your change is not sufficient neither as a developer can release version 12 to China and a different version 12 to India. I have to collect all those and yes, the reporting needs to get more faceted.

Also App Bundles will be a challenge: Here I expect many many APKs to match the same git revision and hopefull all those are subsets of the version I can compile from the code.
