### ISSUE TITLE
bitpay: incompatible payment protocol (address, amount)

### ISSUE THREAD

**Issue by matevz** [bitcoin-wallet/bitcoin-wallet#615]
Trying out the payment protocol using https://bitpay.com/demos gives me an error in bitcoin-wallet
```
The payee (bitpay.com) is using an incompatible payment protocol (reason: address, amount).
```

So the QR code contains `bitcoin:?r=https://bitpay.com/i/2ciEurEMxg6WrQJTxGZrmD` without `address` and `amount` parameters. Should those be mandatory and is bitpay demo broken? If not, I suggest we make those optional in bitcoin-wallet settings so users can use bitpay services.

**Comment by schildbach** [comment]
See https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.specs.md#unsupported-or-partially-supported-specifications

BitPay needs to either include a matching address and amount or a hash of the payment request message. Or, they could skip BIP72 and just send a BIP70 payment request message with the correct MIME type (see BIP71).

If we remove that check, we would be vulnerable to coin theft by payment request forgery.

**Comment by matevz** [comment]
> If we remove that check, we would be vulnerable to coin theft by payment request forgery.

Um... how would one be vulnerable to request forgery, if the provided URL is secure over https? Isn't the secure connection there to prevent such MITM attacks or am I missing something?

**Comment by mrgreywater** [comment]
Couldn't there just be a warning with manual approval instead? Something like "This payment request is not secure and could be forged. Do you really want to continue? Y/N"

**Comment by schildbach** [comment]
When you use BIP21, your trust anchor is the QR-code (or the bare link). That's what users expect. They can safely assume their money will be sent to the person who just showed you her/his QR code. A man in the middle would literally have to stand between the camera and the screen, or your eyes and your fingers.

BIP72 breaks this assumption by adding an indirection and forcing the CA industry as a new trust anchor. The CAs have proven over and over that they are not worth this trust. Also, the CA model simply doesn't work for person-to-person payments or person-to-small-businesses: if you're buying a computer from Dell, you might be able to recognize/validate their name in the shown certificate. But when it comes to kiosks, bakeries, second hand markets, anonymous persons etc. it's unlikely you know their name so how should you verify?

It would be super easy for BitPay to add the address and the amount, and it would have the added benefit of also serving wallets that don't support the payment protocol.

**Comment by mrgreywater** [comment]
@schildbach Well, as it stands as a user I will just have to switch to a more insecure app to do these payments, or manually enter the address and amount, which involves far more risks. 
I agree Bitpay should change their requests, but on the other hand, there should be some kind of manual override or everyone will just switch to far worse workarounds.

**Comment by schildbach** [comment]
You could also switch to a more secure payment provider. Seriously, please complain to BitPay about this! It's really easy for them to change this.

**Comment by mrgreywater** [comment]
The offered payment provider is not something a customer has control over. Except rejecting payment with Bitcoin/BitPay alltogether. If someone offers payment via Bitcoin, there is usually only one provider offered.
As I said, this decision only drives me and probably others to find less secure and more cumbersome ways to complete these transactions.

**Comment by matevz** [comment]
I have to agree with @mrgreywater here. In Slovenia there is Elipay service crypto provider in brick&mortar markets and they too offer only `bitcoin:?r=https://elipay.com/something` QR form. Eventually I will have to switch to BitPay or bitcoin.com wallet for such payments. It would seem more prudent for bitcoin-wallet to show a big warning about potential security risks involved to the user and let him pay anyway (similar to what browsers do when a certificate expires or is self-signed). This way users would know Elipay is doing something wrong (and they will file complaints), but they would still be able to use crypto.

**Comment by schildbach** [comment]
This BitPay announcement might be related: https://bitpay.com/blog/p2p-payments/

I assume they will enable BIP21. Once their update goes live and if there is still some incompatibility feel free to ping me here and I'll have a look at the situation.

**Comment by mrgreywater** [comment]
That's great news for BitPay (when it's rolled out). For now I'm using this: https://alexk111.github.io/DeBitpay/ to transform the payment links of BIP72 (with additional secondary manual verification by `curl -H "Accept: application/payment-request" https://bitpay.com/i/PAYMENTCODE`). I don't like it, especially since that really opens the door for man in the middle, but what can you do... *shrug*

**Comment by matevz** [comment]
Hey guys. So afther the BitPay's announcement that it will support other wallets I tested the new BitPay interface at their [demo site](https://bitpay.com/demos). Now it asks which wallet are you using and I could roughly categorize them in the following categories:
1) bitpay, copay, btc.com, bitcoin.com, electrum and most other wallets which support BIP-72,
2) bitcoin core and electrum wallet for which BIP-72 is generated, but a notice is put that you should disable replace-by-fee option,
3) Green wallet, Trezor wallet and some others for which BIP-21 address is generated and that you should use high network fee to speed up confirmation time,
4) bitstamp, kraken, binance and other exchanges which are not supported at all and a message saying you should move your coins to a wallet first and then make a payment from there.

I contacted bitpay support to also list bitcoin-wallet in either category 1) and fixing their BIP-72 by also adding address and amount to their URI/QR code, or 3).

**Comment by schulzemic** [comment]
I paid a Bitpay invoice a few weeks ago, so this is probably fixed now.
