### ISSUE TITLE
Could you provide signed builds (apks) outside of play store

### ISSUE THREAD

**Issue by eloyesp** [bitcoin-wallet/bitcoin-wallet#620]
I can't access play store, so I cannot download new versions, could you provide signed apk to download?

https://github.com/bitcoin-wallet/bitcoin-wallet/issues/197 mentions releases, but there are no apks to download and f-droid is outdated.

**Comment by joydeep2899** [comment]
[Bitcoin Wallet_v8.01.zip](https://github.com/bitcoin-wallet/bitcoin-wallet/files/4479820/Bitcoin.Wallet_v8.01.zip)
i  provided a apk file inside zip...see if this helps

**Comment by micressor** [comment]
I would love to have .apk's on github for download until the build process on f-droid works reliably again.

I'm not sure if the latest version has security issues, which is currently available on f-droid?

**Comment by make-free-code** [comment]
Are there any plans to publish APKs here on GitHub or on F-Droid again?

**Comment by schildbach** [comment]
As soon as F-Droid publishes the APK, yes.

**Comment by make-free-code** [comment]
Thank you for your answer.
What is currently preventing it from being published on F-Droid? Would providing APKs via GitHub releases be a suitable option?

**Comment by rabner** [comment]
Any idea when woudl that be?

**Comment by schildbach** [comment]
No idea, sorry. F-Droid successfully builds the app on each cycle, but then fails to publish it on their "store".

**Comment by alexanderadam** [comment]
For anyone looking for the upstream ticket. It's [fdroiddata/6058](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6058).

Maybe one F-Droid issue should kept open and pinned in the bitcoin-wallet issues.
This could avoid duplicates like [this](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/653), [this](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/650), [this](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/607), [this](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/573), [this](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/443) and so on. 😉

**Comment by Giszmo** [comment]
As proposed in #712, it would be nice to have the apk here on GitHub releases, too, independently of what's going on at Google or FDroid.

**Comment by schildbach** [comment]
Binaries can be downloaded from F-Droid, and F-Droid has been brought up-to-date again. So I'll close this.
