### ISSUE TITLE
Viewing transactions on Blockchain.com broken in Testnet wallet

### ISSUE THREAD

**Issue by alexeiZamyatin** [bitcoin-wallet/bitcoin-wallet#632]
What: Link for viewing transactions on Blockchain.com broken in Testnet wallet

Details: The URL for viewing a send/received transaction in the Blockchain.com explorer seems broken and leads the users to an error page. 

Reproduce: Select any transaction in the testnet wallet, click on the 3 dots at the bottom right, select "Browse". 

Since the wallet does not seem to show the raw txid, it is now impossible to check the status of the transaction outside of the wallet (important for debugging when building applications).

**Comment by schildbach** [comment]
Do you know the correct base URL for blockchain.com's Testnet explorer?

**Comment by alexeiZamyatin** [comment]
https://www.blockchain.com/**btc-testnet**/tx/<txid>

**Comment by schildbach** [comment]
Thanks! Fixed via a16e0e59f23d986fd4ac067221a80261b363f57b.
