### ISSUE TITLE
Can't build bitcoinj/tools/wallet-tool to recover private keys

### ISSUE THREAD

**Issue by ctar** [bitcoin-wallet/bitcoin-wallet#633]
Having a heck of a time building ./wallet-tool per your guide. I've tried in Intellij and using cli on Mac and Ubuntu and get different errors in all. I was able to successfully decrypt, but unable to build bitcoinj/tools/wallet-tool. Any help appreciated. On Ubuntu 20.04:

_me@host:~/bitcoinj/tools$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
me@host:~/bitcoinj/tools$ gradle -version

Gradle 4.4.1

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.17
Ant:          Apache Ant(TM) version 1.10.7 compiled on October 24 2019
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 5.4.0-42-generic amd64

me@host:~/bitcoinj/tools$ ./wallet-tool
Skipping wallettemplate: Gradle 4.4.1 and Java 1.8

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
me@host:~/bitcoinj/tools$_ 

After adding this to dependencies per a stackexchange thread I found re the tools.jar error:

runtime files(org.gradle.internal.jvm.Jvm.current().toolsJar)

_me@host:~/bitcoinj/tools$ ./wallet-tool 
Skipping wallettemplate: Gradle 4.4.1 and Java 1.8

FAILURE: Build failed with an exception.

* Where:
Build file '/home/me/bitcoinj/tools/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':tools'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
me@host:~/bitcoinj/tools$_

**Comment by ctar** [comment]
I was finally able to build & run using Maven and release-0.14. Using Gradle either via CLI or via Intellij gave the above error on release-0.15. Using the most recent version gave errors about protobuf plugin.

**Comment by schildbach** [comment]
Modifying the classpath should not be necessary; the Ubuntu openjdk-8-jdk package comes ready-to-go. Maybe you've got some custom configuration that causes the classpath problem?

Looking at the `release-0.15` branch:

Does a full build (`gradle clean build` in the project root directory) succeed? If yes, can you try running `./wallet-tool` from within the `tools/` directory again?

**Comment by ctar** [comment]
Ok, I think I had a problem w/ my Java install being only JRE, despite installing openjdk. It's working for me now. I do think in a later Java version I had another problem, but I'm not in a position to test it now. release-0.15 is working w/ 1.8 using Gradle (4.4.1). Thanks
