### ISSUE TITLE
Feature request: Import wallet from electrum

### ISSUE THREAD

**Issue by recolic** [bitcoin-wallet/bitcoin-wallet#635]
I already have a bitcoin wallet in electrum (desktop). Are there anyway to import a existing btc wallet from electrum?

**Comment by schildbach** [comment]
The recommended and safest way to move Bitcoins between wallets is using a standard Bitcoin transaction.

**Comment by nicolasmaia** [comment]
That would entail losing money, though. Is there no other way?
