### ISSUE TITLE
Problem after restoring old backup

### ISSUE THREAD

**Issue by zmp2000** [bitcoin-wallet/bitcoin-wallet#636]
Hi, I've restored a backup from 2017, and after network synchronization it's missing the earliest transactions,
Is There a reason for that?

I'mean it's missing some values. I'm really confused on how a restore wallet works
Can somebody gives me a light ?
I've already decrypted the backup on my computer and I do have all private keys and the phrase

But it's like there are missing some addresses as I can't see all transactions I've made
Is There a way I can restore a wallet from this seed words? I've tried on Electrum but it's a non go.

**Comment by AlldayBoutique** [comment]
U need backup private keys and phrase

**Comment by schildbach** [comment]
Can you use Options→Report issue and in the report include the txid of some of the missing transactions?
