### ISSUE TITLE
Restore old saved wallet failed.

### ISSUE THREAD

**Issue by ClementHector** [bitcoin-wallet/bitcoin-wallet#640]
Hello,

I attempted to restore a backed up wallet from 2013 but it fails with error: `Could not decrypt bytes`

My backup is named `bitcoin-wallet-keys-2013-06-06`

I tried with this command [`openssl enc -d -aes-256-cbc -a -in "backupfile" -out "backupfile.out" -k password`](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/135) and it works fine on my computer.

Do you have any solution for me?

thanks a lot.

**Comment by ClementHector** [comment]
is this application discontinued?

**Comment by dongyanghe** [comment]
Have you solved the problem?

**Comment by ClementHector** [comment]
Not yet!

**Comment by Noodeloo** [comment]
I have this same issue , with the correct password it says unreadable wallet instead of can't decrypt bytes , how can it be opened and recovered , if I transferred bitcoins out would I have a new address that perhaps I didn't back up properly ? ive almost given up on it! help anyone?

**Comment by gr01d** [comment]
Try older version of the app.
See: https://github.com/bitcoin-wallet/bitcoin-wallet/issues/644

**Comment by schildbach** [comment]
As always, can you use Options→Report issue to report issues? Such reports contain the necessary information to be able to help.

**Comment by btc2dogecom** [comment]
> I have this same issue , with the correct password it says unreadable wallet instead of can't decrypt bytes , how can it be opened and recovered , if I transferred bitcoins out would I have a new address that perhaps I didn't back up properly ? ive almost given up on it! help anyone?

do you get that back? we may help you if you have the backup
www.btc2doge.com
