### ISSUE TITLE
How to recover BCH from this wallet ?

### ISSUE THREAD

**Issue by ArthurBTC** [bitcoin-wallet/bitcoin-wallet#645]
Hello,
I had BTC on your wallet before the BCH fork. I would like to claim them (late if better than never, wouldn't you agree ? :-))
How can I do that ? I dont know how to recover the private keys since they are encrypted when i generate a backup, and i dont find other options.
Thanks for your help mate, and all the work you did with this wallet
Arthur

**Comment by arafat877** [comment]
Hello,

Do you mean by that, that I have your bitcoins ??? If that's the case I can
give you my password to recover your private keys, and then you return me
back my password.

King regards
