### ISSUE TITLE
old backup of private key

### ISSUE THREAD

**Issue by Spheren** [bitcoin-wallet/bitcoin-wallet#649]
I found a file on my old phone that called "Bitcoin Wallet backup of private key" from 2013. It's a small file with 349 Byte and contains this: (I changed a few letters to XXX in case that I can restore this file.)

U2FsdGVkX18GOmsvXXXXXXXXXXXXXXXXXXXXXXXXXXXR/fEwbsJuMMVmpeBgxGj66bDQVOn+
9UoAA9CWeJaNMFBl/n3v3HBq7qameVHze6iZ6rx+1idrphhRkLf/VQ1d46rJqPjxqRSCPMtmHoSQ
5IzkO/3BQbsIyYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXmU8w3FLi4EOIffT0NVISlL8ZLBeWQncMY
AfH4zdpMKvUwoJfXqba45e9+5gJbyt3jfmXYsxTtJJkY7w7qhlvEeV7UjW+mTGtOEfVnefuTbjlW
80MZaT3/K2fp5aPydwz6awhw5UvQkK5TVfYUHg==

I know the public address from this private key and it contains 1BTC. Can I restore this "backup" somehow? Has someone an idea? Thank you very much!

**Comment by keychainx** [comment]
I have just done exact. Its a bit complicated but doable. We have helped several people in similar situations. You can read more on our blog https://keychainx.medium.com

**Comment by schildbach** [comment]
@Spheren Do you still have your backup password?

**Comment by kryptonitechic** [comment]
even if u do and ur email they claim they cant6help

**Comment by Wagnard** [comment]
I have the same issue, old backup from 2013, cant seem to restore it with the app and I have the password.

**Comment by schildbach** [comment]
Old backup files named `bitcoin-wallet-keys-<yyyy-mm-dd>` can – if you have the correct backup password – either

1. be decrypted manually using OpenSSL. It will yield the private keys in WIF format, which can be imported into Bitcoin Core. See the [recovery instructions](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md) for the exact commands. Or
2. be restored using [version 6.35](https://wallet.schildbach.de/downloads/bitcoin-wallet-v6.35-prod.apk) of the app. After restore, make sure to upgrade to the latest version via F-Droid or Google Play asap.

If you don't have the backup password however, then indeed there is no way to restore your wallet, as the password is meant to protect your backup.

**Comment by btc2dogecom** [comment]
> I have the same issue, old backup from 2013, cant seem to restore it with the app and I have the password.

do you get that back? we may help you if you have the backup
www.btc2doge.com

**Comment by btc2dogecom** [comment]
> I found a file on my old phone that called "Bitcoin Wallet backup of private key" from 2013. It's a small file with 349 Byte and contains this: (I changed a few letters to XXX in case that I can restore this file.)
> 
> U2FsdGVkX18GOmsvXXXXXXXXXXXXXXXXXXXXXXXXXXXR/fEwbsJuMMVmpeBgxGj66bDQVOn+
> 9UoAA9CWeJaNMFBl/n3v3HBq7qameVHze6iZ6rx+1idrphhRkLf/VQ1d46rJqPjxqRSCPMtmHoSQ
> 5IzkO/3BQbsIyYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXmU8w3FLi4EOIffT0NVISlL8ZLBeWQncMY
> AfH4zdpMKvUwoJfXqba45e9+5gJbyt3jfmXYsxTtJJkY7w7qhlvEeV7UjW+mTGtOEfVnefuTbjlW
> 80MZaT3/K2fp5aPydwz6awhw5UvQkK5TVfYUHg==
> 
> I know the public address from this private key and it contains 1BTC. Can I restore this "backup" somehow? Has someone an idea? Thank you very much!

do you get that back? we may help you if you have the backup
www.btc2doge.com
