### ISSUE TITLE
f-droid's repository seems to have a very outdated version

### ISSUE THREAD

**Issue by AndySchroder** [bitcoin-wallet/bitcoin-wallet#650]
f-droid's repository seems to have a very outdated version. Would be nice to have that updated, or if you are having a problem with f-droid, maybe consider following NewPipe's example and create your own repository dedicated to bitcoin wallet.

https://newpipe.schabi.org/blog/announcement/f-droid/pinned/f-droid-repo/

**Comment by schildbach** [comment]
Duplicate of https://gitlab.com/fdroid/fdroiddata/-/issues/1884

I will keep that issue up to date.

I'm afraid managing a custom repository is currently not planned because of the addtional work involved.
