### ISSUE TITLE
How to recover old bitcoin wallet

### ISSUE THREAD

**Issue by davidspies** [bitcoin-wallet/bitcoin-wallet#652]
I have a bitcoin wallet I emailed myself a recovery key for in 2014.
How do I recover it? I don't see any options in the app

**Comment by davidspies** [comment]
It's just a file with a big long base64 string and nothing else titled "bitcoin-wallet-backup-2014-08-30"

**Comment by schildbach** [comment]
Use Options→Safety→Restore wallet to restore your wallet from a backup.

**Comment by davidspies** [comment]
@schildbach I don't remember the password. Is it still possible to tell which addresses it's associated to so I can know how bad I should feel about having lost it?

**Comment by davidspies** [comment]
Is it possible that the backup didn't have a password somehow?

**Comment by schildbach** [comment]
The app always asked for a backup password.

**Comment by btc2dogecom** [comment]
> Is it possible that the backup didn't have a password somehow?

do you get that back? we can bruteforce if the password not too complex
www.btc2doge.com
