### ISSUE TITLE
Problem with unbroadcast transaction.

### ISSUE THREAD

**Issue by Hisspa** [bitcoin-wallet/bitcoin-wallet#656]
I wanted to send some satoshis to an automated exchange, I scanned the code and tried to send, but the transaction got stuck as "not broadcast yet" because of a synchronization error due to the lack of storage, it seems. I cancelled the order on the exchange but I was afraid since I could not cancel the transaction on the app. So I uninstalled the app and did the recovery process on other phone without connection and it worked well (did not show any balance because I did not allow synchronization) But I am afraid that once I turn on the Wi-Fi the transaction might be sent even though It is not the same phone.

I Have checked the address I was supposed to send the satoshis to and it is empty.

I just want to avoid the broadcasting. And I don't know it will happen if I allow the app to synch.

**Comment by eloyesp** [comment]
Most automated exchanges should return invalid transactions to the cancel address (or to the sending address if no return address given), so the risk should not be more than twice the fee. The exchange should not reuse that address for other exchange.

On the other hand, once you uninstall the app, anything that was not broadcasted or backuped is lost forever (as the wallet does not store anything on public storage but backups).

So as far as I understand, you can restore the backup without any risk, specially if the backup was created _before_ creating the transaction.
