### ISSUE TITLE
Decrypt wallet

### ISSUE THREAD

**Issue by culdesacab2020** [bitcoin-wallet/bitcoin-wallet#662]
Hello

I need to decrypt my wallet offline but do not understand how to add the spending pin to the decrypt password.

openssl enc -d -aes-256-cbc -md md5 -a -in bitcoin-wallet-backup-testnet-2014-11-01 > bitcoin-wallet-decrypted-backup

it asks for password. but if my password is hello and the pin 1234 how do I enter this?

**Comment by schildbach** [comment]
For decrypting your backup, you only need to provide your backup password to openssl.

You will need the spending PIN for spending Bitcoins, after you have restored from the backup.
