### ISSUE TITLE
How do I export a xpub key from the wallet?

### ISSUE THREAD

**Issue by RwSgxx** [bitcoin-wallet/bitcoin-wallet#668]
If I go to Diagnostics->Show extended public key, I get a zpub key. I can't use this with my portfolio tracker, neither with any chain explorer.
Is there a way to get the xpub public key? 
Or any chain explorer that supports the zpub public key?

Thank you!

**Comment by schildbach** [comment]
There is no xpub any more. With SegWit, zpub is used.

**Comment by khokho1986** [comment]
3AhLfoVCK1UcA8VjCDu6r1ZQTLEdVq3LPc
