### ISSUE TITLE
Backup/Export: Use universal format

### ISSUE THREAD

**Issue by My1** [bitcoin-wallet/bitcoin-wallet#671]
wouldnt it be kinda useful to have the wallet export to a format that works in other wallets as well like electrum or btc core rather than needing to go through big ways of exporting the private keys individually something that can likely very easily be done wrong?

**Comment by monstro805** [comment]
https://docs.google.com/open?id=1MyuVyW66219MkD3md37mqe6ximA-lG36pFYPQrkNvg4&usp=drive_fs

**Comment by schildbach** [comment]
The 12 word phrases have been invented for that. However, it turns out there are always differences between the wallets, some of the subtle. Which leads to users loosing coins by not seeing them in the next wallet (technically they still own the private keys, but the balance is not shown correctly). So the industry has given up on that (except for simple one-address paper wallets).

**Comment by My1** [comment]
> https://docs.google.com/open?id=1MyuVyW66219MkD3md37mqe6ximA-lG36pFYPQrkNvg4&usp=drive_fs

@monstro805 
no access



> The 12 word phrases have been invented for that

@schildbach and how to get those out of the app? as far as I am aware you can only export the keys in some semi-special encrypted format.

**Comment by schildbach** [comment]
You can get the deterministic seed from a backup using openssl and wallet-tool, the same way you get the private keys.

**Comment by My1** [comment]
why not make it also possible to just show it rather than making the user go through a bunch of hoops that can go wrong rather easily?

**Comment by schildbach** [comment]
Why show it to the average user? What's your usecase?

**Comment by My1** [comment]
for example to be able to use it on a different wallet software like on a different operating system as this is android only.

**Comment by schildbach** [comment]
Like I described, this usecase won't work.

If you want to move coins to another wallet, please use a standard Bitcoin transaction.
