### ISSUE TITLE
Recovering wallet from old android device

### ISSUE THREAD

**Issue by JeanValjean6** [bitcoin-wallet/bitcoin-wallet#673]
Hello everyone,

Please forgive me my utter foolishness in the matter and probably most newbie question possible, but there is much at stake for me and I have run out of alternatives.

Around the year 2014 I had Bitcoin Wallet app installed on my old Samsung GT-S7580 and there was some money in this wallet which today is worth couple times more. Unfortunately for the reasons I cannot recall, I deleted the app without any backup. Just yesterday I happened to find this old phone and tried to recover some data from it. I haven't made many operations on this phone so I think that the data may not be erased, but I can't find a way to locate it. I installed the app from the apk (because this phone model is no longer supported) but the wallet is empty. Is there a way to find the wallet if I deleted the app back then? I used some of the recovery software for android but it mostly finds popular files like photos and messages. I rooted my phone and tried DiskRigger Pro but I don't know what I'm looking for exactly. From what I gathered there should be some .data or .bin file but maybe I am wrong.

I know that I'm in this place because of my stupidity, but maybe some good soul will take pity on me and try to help.

Thank you in advance.

**Comment by 5ans989** [comment]
No understand I am haouli farouk. Email Farouk.lancien@gmail.com

**Comment by leopheard** [comment]
Be careful when you reply to people directly like the above, they might try and scam you

**Comment by schildbach** [comment]
Please use Options→Report issue.
