### ISSUE TITLE
Wallet address keeps changing after payments are done

### ISSUE THREAD

**Issue by jhiver** [bitcoin-wallet/bitcoin-wallet#674]
Crypto-noob here... is there a way to disable the fact that bitcoin address is changing after every transaction received?

What happens if someone sends you BTC to a previous address?

e.g. your address to receive funds is A, you send it to Person P1 and Person P2, person p1 makes a payment to  A, now your address becomes B, and person p2 makes a payment to A...

It seems to me it would prevent transmitting wallet address to different parties from which you're expected to receive payments, but maybe it doesn't matter?

Thanks for enlightening me...

**Comment by schildbach** [comment]
It can't be disabled, but all old addresses stay valid for receiving.
