### ISSUE TITLE
Getting an "You've got a bad connection to the Electrum network" error when doing wallet sweep

### ISSUE THREAD

**Issue by KernelSight** [bitcoin-wallet/bitcoin-wallet#676]
This isn't one I saw earlier. Googling shows only one other hit (from two weeks back). I see the network connection is fine, and I see the number of peers in the notification is non-zero. This is from the Google Play mainnet install

**Comment by schildbach** [comment]
If you've got no P2P peers connected then chances are you've got a bad connection.

**Comment by KernelSight** [comment]
Thanks for the quick reply. As I said, I do see a nonzero number of P2P peers . Ranging from 2 to 7 the times I have observed. Is there any tab or screen I can check to see exactly how many peers there are?

**Comment by schildbach** [comment]
Sorry, I missed the "non". Actually the Electrum network is a separate network (ElectrumX, electrs). At some point we should add P2P discovery for Electrum peers too. Currently those are hardcoded and need to be updated from time to time.

**Comment by KernelSight** [comment]
If hardcoded, does this mean there is a specific time of day where the chances of finding these peers is higher?

**Comment by ristein** [comment]
getting the same error trying to sweep a paper wallet. Any possibilities?
![photo_2021-08-02_14-26-35](https://user-images.githubusercontent.com/55446611/127861752-5ddcdf81-33ea-4954-bb5c-baa219dc59e2.jpg)

**Comment by schildbach** [comment]
Everyone: Please make sure you're on the last available version, then try to reproduce the problem, then if the error appears please use Options→Report issue to report it. Keep "log files" ticked.

**Comment by ristein** [comment]
[bitcoin wallet issue.zip](https://github.com/bitcoin-wallet/bitcoin-wallet/files/6917536/bitcoin.wallet.issue.zip)

**Comment by schildbach** [comment]
@ristein Could you join the beta channel of the app, update to v8.16, and try again?

**Comment by ristein** [comment]
sure, no prob. How to?

**Comment by schildbach** [comment]
The Beta channel is an option on Google Play, e.g. within the Play Store app.

**Comment by ristein** [comment]
I got the beta app via aurora store and manual downloading version 816.
Sweeping is working now.
Here are logs:
[bitcoin wallet 2.zip](https://github.com/bitcoin-wallet/bitcoin-wallet/files/6922177/bitcoin.wallet.2.zip)

**Comment by schildbach** [comment]
The list of Electrum servers was updated, so this issue should not exist on the latest version. Thus, I'm closing this. If it still (or again) happens to you, please comment with your logfile and I'll re-open.
