### ISSUE TITLE
Problem with buying bitcoins from shitcoins

### ISSUE THREAD

**Issue by tsjuddy** [bitcoin-wallet/bitcoin-wallet#677]
I bought yesterday from a shitcoin machine.
But after 16hours I still not see the incoming transaction in my wallet. Alsow its not confirmed alsow.
Normal you should see the incoming payment while you wait confirmation. What is wrong?

![Screenshot_20210209-101247_Chrome](https://user-images.githubusercontent.com/61463742/107341529-658d7800-6abf-11eb-83b0-73779ce8bf12.jpg)

**Comment by schildbach** [comment]
Please use Options → Report issue.

**Comment by tsjuddy** [comment]
I cant see the option because the transaction is not showen in my wallet. That is the issue.

**Comment by tsjuddy** [comment]
Why close the problem isnt solved...

**Comment by tsjuddy** [comment]
Omg....

**Comment by schildbach** [comment]
The options menu is always seen. It's the "three dots" in the upper right.
