### ISSUE TITLE
Restore Wallet Delete Old Wallet?

### ISSUE THREAD

**Issue by JonMontgo** [bitcoin-wallet/bitcoin-wallet#679]
Hi I just restored an old backup I had of a wallet but what seems to have happened is that the old sending and receiving addresses on the phone disappeared. Does restoring a wallet not merge the sending and receiving addresses and are these private keys gone?... I unfortunately did not backup the wallet before restore...

**Comment by andressalas93** [comment]
Restore

**Comment by JonMontgo** [comment]
So I see that I missed the message saying that the old wallet would be deleted https://github.com/bitcoin-wallet/bitcoin-wallet/issues/483

This is really disappointing...
