### ISSUE TITLE
Restore Schildbach Wallet Backup

### ISSUE THREAD

**Issue by solrac7611** [bitcoin-wallet/bitcoin-wallet#681]
Hello, 
I have found an old Backup from Schildbach Bitcoin Wallet (From 01.07.2014), the Backup ist 240 Bytes but i dont have the Password, is any chance for me to recover my Wallet?.

**Comment by schildbach** [comment]
Use Options→Report issue.

**Comment by btc2dogecom** [comment]
> Hello,
> I have found an old Backup from Schildbach Bitcoin Wallet (From 01.07.2014), the Backup ist 240 Bytes but i dont have the Password, is any chance for me to recover my Wallet?.

can brute force it if you have clues
www.btc2doge.com
