### ISSUE TITLE
lost password for backup bitcoin wallet, have the backup file. 

### ISSUE THREAD

**Issue by esbar73** [bitcoin-wallet/bitcoin-wallet#684]
@schildbach  if you could help me get my password back or help me decrypt everything, i have all the files you sent me in 2016, but i was incarcerated since and just got out. thanks.

**Comment by axelsimon** [comment]
Do you have *no idea* of the password, or some idea of possibilities?
I'm really no expert here, but the password is used to encrypt the backup file, so without it it's going to be very hard to decrypt the backup and reach what's inside (seed / keys).

**Comment by esbar73** [comment]
trying to use btcrecover but having trouble getting it started, i downloaded everything needed. but it still wont run

**Comment by schildbach** [comment]
Please use Options→Report issue. Thanks.

**Comment by btc2dogecom** [comment]
> @schildbach if you could help me get my password back or help me decrypt everything, i have all the files you sent me in 2016, but i was incarcerated since and just got out. thanks.

hello, 
do you get that back? we can brute force it if you have some clues
www.btc2doge.com

**Comment by anderson6470** [comment]
@esbar73 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by axelsimon** [comment]
Warning: do not email your wallet to a random person on the Internet, especially one that asks for it.

@schildbach please remove the comment above (and this one once that's done :))
