### ISSUE TITLE
NullPointerException when importing to Intellij IDEA

### ISSUE THREAD

**Issue by fredboy** [bitcoin-wallet/bitcoin-wallet#685]
When trying to import project to intellij idea it throws a NullPointerException. It imports fine, if i change android gradle plugin version to 4.0.1, if i do that the wallet will also build succesfully, but crash when launched on device. If i keep plugin version as it is 3.1.4, it builds and works fine from terminal, but not in the IDE. The latest android studio can import the project succesfully, but cannot install on device, i found out that the issue here is that gradle plugin is too old for this version of android studio (4.1.2), and if i change it, the app will crash when launched, trying to inflate wallet balance fragment with ClassNotFoundException. I tryed invalidating caches, and reinstalling the intellij, but it didn't help. Also tryed different versions of gradle, down to oldest supported 4.4. What can i do to resolve this?

**Gist with the stacktrace**: https://gist.github.com/fredboy/da8617ec0cc80cdba9525eccc03fc45f
**Intellij IDEA version**: 2020.3.2
**Gradle version**: 6.8.2
**JVM 12**

**Comment by schildbach** [comment]
To install to the device, use `gradle iDD` on the command line.

**Comment by fredboy** [comment]
Not exactly what I was looking for, but thanks for the reply. Am I the only one facing that issue, or somebody also have to deal with it?

**Comment by schildbach** [comment]
I'm closing this, as building the APK from within Android Studio is currently not supported. Please use support toolchain, that is Gradle 4.4.1, OpenJDK 8 or 11 from Debian or Ubuntu.

That said, I can at least build all the classes without issues (Ctrl-F9 in IntelliJ).
