### ISSUE TITLE
BIP38 encoded keys can be 59 characters long

### ISSUE THREAD

**Issue by chr15m** [bitcoin-wallet/bitcoin-wallet#688]
Currently 59 character BIP38 encrypted keys are rejected. I noticed in an older version of the code the regex looks for "6P" followed by 58 characters, but it should be 58 or 59 i.e. `{58,59}`.

To replicate this issue: generate some BIP38 encrypted keys until you find one that is 59 characters long. Try to sweep it and observe the error message.

**Comment by schildbach** [comment]
Do you have an example for a 59 character BIP38 encrypted key that is worthless?

**Comment by chr15m** [comment]
@schildbach my apologies this must have been user/transcription error. BIP38 says:
> 58 characters always starting with '6P'
and I am unable to generate an example.
