### ISSUE TITLE
old backup, need help getting in

### ISSUE THREAD

**Issue by esbar73** [bitcoin-wallet/bitcoin-wallet#690]
have my old back up on i saved on my email, was created in 2016, but i have been incarcerated since and have no idea what i would have set my password to then, please help me get in to my old wallet. life has been rough since getting out and i dont wanna have to do things that will send me back

**Comment by schildbach** [comment]
Use Options→Report issue. Thanks.

**Comment by btc2dogecom** [comment]
> have my old back up on i saved on my email, was created in 2016, but i have been incarcerated since and have no idea what i would have set my password to then, please help me get in to my old wallet. life has been rough since getting out and i dont wanna have to do things that will send me back

hello. do you fixed your backup? we can bruteforce you password. please contact us: 
www.btc2doge.com

**Comment by nichole1892** [comment]
@esbar73 
i have recovered many old wallet backup files for my clients. if you haven't recovered your backup contact me I can recover it
walletsrecoveryservice@gmail.com
