### ISSUE TITLE
Old backup private keys don’t import all addresses 

### ISSUE THREAD

**Issue by NORcoin** [bitcoin-wallet/bitcoin-wallet#693]
Hello,

I’m having this strange problem, I hope someone can help me figure it out.

I found an old backup private key from 2013 backed up from android app, I downloaded the new android version and attempted to import the key, I got an error message saying unreadable wallet.

Password is correct, because I went on to decrypt the file with openssl and I got four private keys, and I imported these private keys to Electrum I got all the addresses but one is missing, and the reason I know that one address is missing is because I had a screenshot with the backup showing the right addresses and they are all there except one and of course it’s the one with bitcoins in it.

I hope someone can help me with this weird problem 

Thank you in advance

**Comment by schildbach** [comment]
Use Options→Report issue.

**Comment by btc2dogecom** [comment]
do you get that back? we may help you if you have the backup
www.btc2doge.com

**Comment by absentio** [comment]
Did you get to resolve the issue? @NORcoin @schildbach

**Comment by Niaga16** [comment]
Belum berhasil
Saya bingung menggunakan bitcoin nya bagaimana dan Seperti apa sistem
aplikasi tersebut?

Pada tanggal Sel, 23 Nov 2021 16.49, absentio ***@***.***>
menulis:
