### ISSUE TITLE
Mandar

### ISSUE THREAD

**Issue by 13kwW39n5SSosGfZb2pCSGD1TdfXqGkJFC** [bitcoin-wallet/bitcoin-wallet#702]
Mandar

_Originally posted by @13kwW39n5SSosGfZb2pCSGD1TdfXqGkJFC in https://github.com/bitcoin-wallet/bitcoin-wallet/issues/695#issuecomment-817573814_

**Comment by Giszmo** [comment]
@schildbach this and #697 look like vandalism to me. OP maybe you want to explain?
