### ISSUE TITLE
New version not in F-Droid

### ISSUE THREAD

**Issue by mrpg** [bitcoin-wallet/bitcoin-wallet#704]
Current behavior: When starting the wallet, one is reminded to update to the most recent version. But no such version is available.

Expected behavior: This message should only appear if an update is actually possible (i.e. available at F-Droid).

Possibly related to https://gitlab.com/fdroid/fdroiddata/-/issues/1884

**Comment by nicolasmaia** [comment]
@rudloff Any idea why the new version wasn't picked up?

**Comment by Rudloff** [comment]
Auto update is not enabled for this app. So someone has to submit a merge request for every release.
That said, 7.69 [has been added recently](https://gitlab.com/fdroid/fdroiddata/-/commit/3d289d1f089cc4bb3f91e7cb1fc7e5178c70cb6d) and should be available soon.

**Comment by schildbach** [comment]
Yes, version 7.69 is a new test pilot for if F-Droid can publish Bitcoin Wallet after a number of issues have been fixed in the F-Droid build process. If it gets published, we will advance to the 8.x branch quickly.

**Comment by schildbach** [comment]
7.69 was just published on F-Droid.

**Comment by schildbach** [comment]
8.15 is now published. So I'll close this.
