### ISSUE TITLE
Lost spending PIN: faster way to check possible PIN candidates with wallet-tool from bitcoinj?

### ISSUE THREAD

**Issue by cricktor** [bitcoin-wallet/bitcoin-wallet#709]
Apologies if this is the wrong place to ask.

I have a wallet backup which I decrypted with success according to the steps in the recovery manual (wallet's birthdate is from 2020-10-xx, if that matters for any reason).
Yes, I know but shit happens that the spending PIN (5 or 6 digits long) for this wallet got lost.
Currently wallet-tool takes too many seconds to check one PIN candidate. I'd rather like to use something more efficient like hashcat or similar. Any hints on how and what to extract from the wallet to make brute-forcing the PIN way faster?
(I'm not trying to steal someone else's wallet funds. There's no point to accuse me of that here.)

**Comment by schildbach** [comment]
This is actually a bitcoinj question, since encryption of wallets is provided by the framework.

Can you take the question to the bitcoinj chat? It's at https://matrix.to/#/#bitcoinj:matrix.org

**Comment by nichole1892** [comment]
@cricktor 
I have previously cracked spending pin for bitcoinj wallet, if you still have this problem send me email so I can crack it for you walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
> Apologies if this is the wrong place to ask.
> 
> I have a wallet backup which I decrypted with success according to the steps in the recovery manual (wallet's birthdate is from 2020-10-xx, if that matters for any reason). Yes, I know but shit happens that the spending PIN (5 or 6 digits long) for this wallet got lost. Currently wallet-tool takes too many seconds to check one PIN candidate. I'd rather like to use something more efficient like hashcat or similar. Any hints on how and what to extract from the wallet to make brute-forcing the PIN way faster? (I'm not trying to steal someone else's wallet funds. There's no point to accuse me of that here.)

you may reach https://btc2doge.org/ for help. They recovered my 368k doge in 2021. mention Doge2021 when you reach them. thanks.
