### ISSUE TITLE
Fail to build on Ubuntu ( java.lang.NullPointerException )

### ISSUE THREAD

**Issue by mammix2** [bitcoin-wallet/bitcoin-wallet#710]
Hi, 
i keep getting this build error message after following the build instructions.

I'm following the Gradle build instructions from this repo on ubuntu 20..

Any help will be great.
thanks

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':sample-integration-android'.
> java.lang.NullPointerException (no error message)
```

**Comment by schildbach** [comment]
Can you paste the output of these commands?
```lsb_release -a```
```gradle --version```
```java -version```
```git status```
Thanks.

**Comment by mammix2** [comment]
You mentioning to check 'java -version' pointed out that mine was linked to JRE11.... Which i have now changed
`sudo update-alternatives --config java `
Then select the 1.8 JDK needed for the build.

Thanks for the help :)
