### ISSUE TITLE
Build is not reproducible for 814

### ISSUE THREAD

**Issue by Giszmo** [bitcoin-wallet/bitcoin-wallet#713]
Following @emanuelb's [discovery that my current approach of unpacking APK files using apktools does not cover all the content of the APK](https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/238), I tried to reproduce Bitcoin Wallet 814 using unzip instead and got a diff in `resources.arsc`. Before getting all alarmist about this, I have to further investigate what is going on and what the implications of that might be. Your input, especially @schildbach would be highly welcome.

**Comment by emanuelb** [comment]
I commented about how to compare the `resources.arsc` files & possible reason at: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/238#note_591648472

**Comment by Giszmo** [comment]
All fine. `disorderfs` fixes it.
