### ISSUE TITLE
Gain access to old wallet when encrypted

### ISSUE THREAD

**Issue by grizzlyatoms** [bitcoin-wallet/bitcoin-wallet#797]
Gain access to old wallet when locked with android .asec file extension?
I believe the wallet is locked with android. I think once its broken down were able to gain access to the wallet but this is way past anything i'm familiar with. Looking for some advice. 
File is on an sd card named de.schildbach.wallet.asec

**Comment by RolandTMJ** [comment]
Same issues.

**Comment by RolandTMJ** [comment]
Gain access to old wallet when locked with android .asec file extension?
I believe the wallet is locked with android. I think once its broken down
were able to gain access to the wallet but this is way past anything i'm
familiar with. Looking for some advice.
File is on an sd card named de.schildbach.wallet.asec

**Comment by anywalletrecovery** [comment]
@grizzlyatoms 
@RolandTMJ 
I have powerful machine to crack password of all versions of bitcoin core wallets.
I have recovered many bitcoin wallets. and some of the had corrupt file. for fast response text me in telegram or gmail
Telegram: @walletrecover
anywalletrecovery@gmail.com

**Comment by schildbach** [comment]
I believe .asec files are encrypted by Android. I'm afraid there is nothing we can do here.

What you need is the backup file that you've (hopefully) created by following the app's instructions.
