### ISSUE TITLE
Translation Update

### ISSUE THREAD

**Issue by SerdarSaglam** [bitcoin-wallet/bitcoin-wallet#802]
Hi
Is it possible for you to update the translations? No translation has been updated for about 5 months, thank you.

**Comment by Yuttana12wr** [comment]
Ngigroub

**Comment by SerdarSaglam** [comment]
Note: I'm talking about the translations we made on Transifex.

**Comment by SerdarSaglam** [comment]
Still not updated, what are they trying to do.

**Comment by schildbach** [comment]
Most translations have been synched with version 9.13, released a couple of days ago.
