### ISSUE TITLE
Changing receiving address 

### ISSUE THREAD

**Issue by martino2002** [bitcoin-wallet/bitcoin-wallet#812]
Can I change my current address for receiving from the address book? If so, can somebody tell me how, since it's not so clear?
If it's not possible I urge the developers to add this functionality ASAP, because it is quite an issue if you ask me.

UPDATE: It would be nice to also being able to delete addresses from your address book.

**Comment by schildbach** [comment]
All the addresses listed under "your addresses" are valid for receiving. If you want to use a fresh address for each payment, always use the address from the QR code on the main screen.

Deleting addresses is technically impossible.

**Comment by martino2002** [comment]
I wrote deleting addresses from your address book, not deleting addresses.

<All the addresses listed under "your addresses" are valid for receiving. 
This is apparently not true for me, a payment of today to an address in my address book has not been received by the wallet.

**Comment by martino2002** [comment]
And if what you are saying is true why there is only one address with the subtitle "This is your current address for receiving"?

**Comment by martino2002** [comment]
Can somebody else help me please, since it seems like this contributor isn't much interested in continuing to answer?
@jonathancross @fynngodau @oscarguindzberg (tagged the next main contributors because since this is a closed issue it was more difficult that someone encountered it)

**Comment by jonathancross** [comment]
>  it seems like this contributor isn't much interested in continuing to answer?

This entire project is basically Schildbach's baby.

@martino2002 
It seems he responded to you within 2 hours -- extremely fast for a github issue, it seems your expectations are a bit unrealistic.  Just to be clear, you are not a "paying customer" of his and none of us are here to serve you.

**Comment by schildbach** [comment]
About the missing payment, please within the app use Options→Report issue and include the transaction ID of the missing payment.
