### ISSUE TITLE
Will we ever have neutrino support?

### ISSUE THREAD

**Issue by AndySchroder** [bitcoin-wallet/bitcoin-wallet#868]
Will Bitcoin Wallet ever support Neutrino ( [BIP157](https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki) / [BIP158](https://github.com/bitcoin/bips/blob/master/bip-0158.mediawiki) )? This has been in bitcoin core for a while now and it seems like it would be worth taking advantage of as it's supposed to be a lot better than SPV.

There is a mode now "a blockchain synchronization mode that prioritizes privacy vs data usage", but it's unclear what that new mode does.
[](url)

**Comment by AndySchroder** [comment]
Sorry, I don't have matrix working yet! I don't have any technical input to provide, just wondering if this was part of a roadmap or not.

**Comment by schildbach** [comment]
There is no roal roadmap, but supporting BIP157/158 is not off the table either. It has severe disadvantages compared to BIP37 and is also not that much more efficient than downloading the entire blockchain. So if you're privacy sensitive, for now I suggest to switch "Data usage vs. Privacy" to the latter.
