### ISSUE TITLE
F-Droid build not updating

### ISSUE THREAD

**Issue by janilowski** [bitcoin-wallet/bitcoin-wallet#869]
Good morning,
is the F-Droid build kept up to date? I have noticed an update from the Aurora Store (Google Play) on 25th August from version 9.03 (903) to 9.05 (905). I have not downloaded that version from Google since I prefer using F-Droid as much as possible.
F-Droid has been stuck on 9.03 for more than a week now. Is this just F-Droid being slow to build the app or is the F-Droid entry abandoned?

**Comment by schildbach** [comment]
Because it can take a long time to get a new version into F-Droid, I'm only updating F-Droid when I feel confident the current release is (almost) free of issues. I've just put up version 9.06, feel free to track progress there:

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11667

**Comment by janilowski** [comment]
> Because it can take a long time to get a new version into F-Droid, I'm only updating F-Droid when I feel confident the current release is (almost) free of issues.
Thank you very much, just wanted to know if it's actively maintained.
Most developers release updates on both platforms at the same time so this had me a little worried :p
