### ISSUE TITLE
Forgot Pin I'm using that app which is Uploaded on google play store 

### ISSUE THREAD

**Issue by ali040** [bitcoin-wallet/bitcoin-wallet#903]
I Forgot Pin I'm using that app which is Uploaded on the google play store https://play.google.com/store/apps/details?id=de.schildbach.wallet&pli=1 so some one can help me about this

**Comment by kirito2411** [comment]
Can You Please Elaborate on the issue

**Comment by schildbach** [comment]
I'm afraid you need to remember your PIN. It is used to encrypt the Bitcoin private keys, so it's not possible to simply remove the PIN without knowing it.
