### ISSUE TITLE
I have forgotten my SPENDING PIN

### ISSUE THREAD

**Issue by aliumairdev** [bitcoin-wallet/bitcoin-wallet#911]
I own an Android Bitcoin wallet, but unfortunately, I have forgotten my SPENDING PIN and am unable to access my wallet funds. I need someone to guide me through the process of recovering my wallet online.

Please note that I am the rightful owner of the wallet, and I simply forgot my PIN. I have already tried btcrecover with no success. The lost PIN could be a number six digits or greater, so I need someone with experience in Bitcoin wallet recovery who can help me unlock it.

**Comment by aliumairdev** [comment]
@patheticpat @Macarse @haplo @ligi

**Comment by schildbach** [comment]
We're afraid you need to remember your spending PIN. There is no way for us to know or reset the PIN.

**Comment by doge2021** [comment]
can brute force the spending PIN if it is your own wallet. you can reach https://btc2doge.com/ for help. he recovered mine in 2021.

**Comment by doge2021** [comment]
can brute force the spending PIN if it is your own wallet. you can reach https://btc2doge.com/ for help. he recovered mine in 2021.
@aliumairdev @ali040
