### ISSUE TITLE
IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.

### ISSUE THREAD

**Issue by schildbach** [bitcoin-wallet/bitcoin-wallet#921]
This happened in the network monitor / blocks list while watching a lengthy replay.

```
03-26 18:22:12.201 20689 20689 E AndroidRuntime: FATAL EXCEPTION: main
03-26 18:22:12.201 20689 20689 E AndroidRuntime: Process: de.schildbach.wallet_test, PID: 20689
03-26 18:22:12.201 20689 20689 E AndroidRuntime: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
03-26 18:22:12.201 20689 20689 E AndroidRuntime:  ViewHolder 1:ViewHolder{d284798 position=3 id=-4933008270983517139, oldPos=-1, pLpos:-1} 
03-26 18:22:12.201 20689 20689 E AndroidRuntime:  View Holder 2:ViewHolder{46cb007 position=2 id=-4933008270983517139, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{2a2e3d6 VFED.V... ......ID 0,0-1080,1928 #7f090078 app:id/peer_list}, adapter:de.schildbach.wallet.ui.monitor.PeerListAdapter@e4a6657, layout:androidx.recyclerview.widget.LinearLayoutManager@f264544, context:de.schildbach.wallet.ui.monitor.NetworkMonitorActivity@2fe662d
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4442)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4366)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2017)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-26 18:22:12.202 20689 20689 W CrashReporter: [main] crashing because of uncaught exception
03-26 18:22:12.202 20689 20689 W CrashReporter: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
03-26 18:22:12.202 20689 20689 W CrashReporter:  ViewHolder 1:ViewHolder{d284798 position=3 id=-4933008270983517139, oldPos=-1, pLpos:-1} 
03-26 18:22:12.202 20689 20689 W CrashReporter:  View Holder 2:ViewHolder{46cb007 position=2 id=-4933008270983517139, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{2a2e3d6 VFED.V... ......ID 0,0-1080,1928 #7f090078 app:id/peer_list}, adapter:de.schildbach.wallet.ui.monitor.PeerListAdapter@e4a6657, layout:androidx.recyclerview.widget.LinearLayoutManager@f264544, context:de.schildbach.wallet.ui.monitor.NetworkMonitorActivity@2fe662d
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4442)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4366)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2017)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.os.Handler.handleCallback(Handler.java:942)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.os.Looper.loopOnce(Looper.java:201)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.os.Looper.loop(Looper.java:288)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-26 18:22:12.202 20689 20689 W CrashReporter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-26 18:22:12.204 20689 20689 I CrashReporter: [main] saved crash trace to /data/user/0/de.schildbach.wallet_test/cache/crash.trace
03-26 18:22:12.208  1937 10722 W ActivityTaskManager:   Force finishing activity de.schildbach.wallet_test/de.schildbach.wallet.ui.monitor.NetworkMonitorActivity
03-26 18:22:12.208  1937 20946 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```

**Comment by ailalexail** [comment]
> این اتفاق در لیست مانیتور / بلوک های شبکه هنگام تماشای یک پخش طولانی مدت رخ داد.
> 
> ```
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: FATAL EXCEPTION: main
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: Process: de.schildbach.wallet_test, PID: 20689
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime:  ViewHolder 1:ViewHolder{d284798 position=3 id=-4933008270983517139, oldPos=-1, pLpos:-1} 
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime:  View Holder 2:ViewHolder{46cb007 position=2 id=-4933008270983517139, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{2a2e3d6 VFED.V... ......ID 0,0-1080,1928 #7f090078 app:id/peer_list}, adapter:de.schildbach.wallet.ui.monitor.PeerListAdapter@e4a6657, layout:androidx.recyclerview.widget.LinearLayoutManager@f264544, context:de.schildbach.wallet.ui.monitor.NetworkMonitorActivity@2fe662d
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4442)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4366)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2017)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 03-26 18:22:12.201 20689 20689 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: [main] crashing because of uncaught exception
> 03-26 18:22:12.202 20689 20689 W CrashReporter: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
> 03-26 18:22:12.202 20689 20689 W CrashReporter:  ViewHolder 1:ViewHolder{d284798 position=3 id=-4933008270983517139, oldPos=-1, pLpos:-1} 
> 03-26 18:22:12.202 20689 20689 W CrashReporter:  View Holder 2:ViewHolder{46cb007 position=2 id=-4933008270983517139, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{2a2e3d6 VFED.V... ......ID 0,0-1080,1928 #7f090078 app:id/peer_list}, adapter:de.schildbach.wallet.ui.monitor.PeerListAdapter@e4a6657, layout:androidx.recyclerview.widget.LinearLayoutManager@f264544, context:de.schildbach.wallet.ui.monitor.NetworkMonitorActivity@2fe662d
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4442)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4366)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2017)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.os.Handler.handleCallback(Handler.java:942)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.os.Looper.loopOnce(Looper.java:201)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.os.Looper.loop(Looper.java:288)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at java.lang.reflect.Method.invoke(Native Method)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 03-26 18:22:12.202 20689 20689 W CrashReporter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> 03-26 18:22:12.204 20689 20689 I CrashReporter: [main] saved crash trace to /data/user/0/de.schildbach.wallet_test/cache/crash.trace
> 03-26 18:22:12.208  1937 10722 W ActivityTaskManager:   Force finishing activity de.schildbach.wallet_test/de.schildbach.wallet.ui.monitor.NetworkMonitorActivity
> 03-26 18:22:12.208  1937 20946 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
> ```

**Comment by schildbach** [comment]
Worked around via 059f0a798500435e2db38f3affec97db34c9d187. The real reason is duplicate peers, which probably should be prevented within bitcoinj.
