### ISSUE TITLE
Does bitcoin testnet wallet support redirections?

### ISSUE THREAD

**Issue by vineetaparodkar** [bitcoin-wallet/bitcoin-wallet#934]
We are trying to integrate this wallet with react native dapp using deeplink. So a user clicks transfer on react native dapp which intiates a deep link to open testnet wallet app and once user clicks send on wallet app user is redirected back to originating react native dapp. 

The deeplink used is 

`bitcoin:<address>?amount=<amount>&callback=<callback>
`

Above deeplink redirects user from react native dapp to wallet app but doesn't redirect back to react native dapp after clicking send on wallet app (i.e. when transaction is submitted). Is there any other configuration parameter that needs to be sent in the above deeplink url?

**Comment by schildbach** [comment]
On Android, you'd use `startActivityForResult()`. That way, in your app `onActivityResult()` is called as soon as the user accepts or rejects your payment.
 
See https://developer.android.com/training/basics/intents/result

**Comment by rezam22** [comment]
934
