### ISSUE TITLE
Incorrect transifex link on https://wallet.schildbach.de/

### ISSUE THREAD

**Issue by jindam-vani** [bitcoin-wallet/bitcoin-wallet#981]
@schildbach transifex link https://www.transifex.com/projects/p/bitcoin-wallet/ is redirecting to transifex landing page

**Comment by minimayki6232** [comment]
> @schildbach transifex link https://www.transifex.com/projects/p/bitcoin-wallet/ is redirecting to transifex landing page

**Comment by schildbach** [comment]
Thanks! Seems like the correct URL is now https://explore.transifex.com/bitcoin-wallet/bitcoin-wallet/ – updated.
